### ISSUE TITLE
DocComment XML not shipping in Microsoft.NETCore.App.Ref 9.0.100-rc1

### ISSUE THREAD

**Issue by JoeRobich** [dotnet/runtime#106825]
This breaks hover support in the VSCode C# extension.

**Expected** 
to see .XML files for each of the libraries like we shipped with 9.0.0-preview.7.

![Image](https://github.com/user-attachments/assets/c18d1c38-c617-4375-8dbe-41e3cf5e5da8)

**Actual** 
see no .XML files.

![Image](https://github.com/user-attachments/assets/0fb7fc9f-aa2a-42b3-8b6f-c1694dd31148)

**Comment by carlossanlop** [comment]
Thanks for reporting. We're aware of this. We just got that fixed with https://github.com/dotnet/runtime/pull/106179

[The fix](https://github.com/dotnet/runtime/commit/fa33eddf3533dac554e959da92f54104c0568c1e) will go [into RC1](https://github.com/dotnet/runtime/commits/release/9.0-rc1?after=c4a79875fcb2c76b2e92ff50940d4ea9264e2eeb+104).

Note that there are also many docs that we haven't updated yet, which will get start showing up on RC2.

**Comment by ericstj** [comment]
@carlossanlop I spot checked https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet9/NuGet/Microsoft.NETCore.App.Ref/overview/9.0.0-rc.1.24421.1
And https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet9/NuGet/Microsoft.NETCore.App.Ref/overview/9.0.0-rc.2.24423.10

DOC XML is still missing.  Can you double check that there's not something else broken here?

**Comment by ericstj** [comment]
I had a look:
https://github.com/dotnet/runtime/blob/5026865050d0535cacda3826505111d08c9acdb2/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Ref.sfxproj#L20

Is trying to grab the files from `MicrosoftNetCoreAppRefPackRefDir` which is `artifacts\bin\microsoft.netcore.app.ref\ref\net9.0`

Inspecting this folder the problems files exist with the name `System.*.intellisense-package.xml` instead of `System.*.xml`.  This was caused by https://github.com/dotnet/runtime/commit/9477e949594c9746b8d99389c4b5ef3065d51fa9.  I'll see if I can make a fix.

**Comment by ericstj** [comment]
Yeah, that change regressed it.  I think that was a bad change as the build process doesn't actually rename the file when copying:
https://github.com/dotnet/msbuild/blob/7cf66090a764f0f239671e4877255efe7ba91155/src/Tasks/Microsoft.Common.CurrentVersion.targets#L398
https://github.com/dotnet/msbuild/blob/7cf66090a764f0f239671e4877255efe7ba91155/src/Tasks/Microsoft.Common.CurrentVersion.targets#L4942-L4944

Nor does the phase that copies to the shared framework:
https://github.com/dotnet/runtime/blob/6e68f9233bb408e2862251858aabe87dd68532fd/src/libraries/sfx.proj#L63-L66
