### ISSUE TITLE
XmlSerializer has different behavior when deserializing an empty XML tag to a collection when `DynamicCodeSupport` is false

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/runtime#107252]
# Description

As the title says, deserializing an empty XML tag to a collection gives different behavior when `DynamicCodeSupport` feature switch is enabled or disabled.

Considering the following code of a `dotnet new console` app:
```cs
using System.Xml.Serialization;
using System.Diagnostics.CodeAnalysis;

Test.TestSerialization("<MyClass></MyClass>");

class Test
{
    public static XmlSerializer GetSerializer([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] Type sourceType)
    {
        return new XmlSerializer(sourceType);
    }

    public static void TestSerialization(string input)
    {
        string msg = string.Empty;
        var serializer = GetSerializer(typeof(MyClass));
        using (StringReader reader = new StringReader(input))
        {
            MyClass? result = (MyClass?)serializer.Deserialize(reader);
            if (result!.Items is null)
            {
                msg += "Items is null";
            }
            else
            {
                msg += $"Items has {result.Items.Count} elements";
            }
        }
        Console.WriteLine(msg);
    }
}

public class MyClass
{
    public List<string>? Items { [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(List<>))] get; set; }
}
```

- When built/run with `-p:DynamicCodeSupport=true` gives:
```
ivanpovazan@EONE-MAC-ARM64 ~/tmp/net8/CoreCLRXmlSerializer $ rm -rf bin obj ; dotnet run -p:DynamicCodeSupport=true 
Items has 0 elements
```

- When built/run with `-p:DynamicCodeSupport=false` gives:
```
ivanpovazan@EONE-MAC-ARM64 ~/tmp/net8/CoreCLRXmlSerializer $ rm -rf bin obj ; dotnet run -p:DynamicCodeSupport=false
Items is null
```

- Same behavior is observed with NativeAOT (which has `DynamicCodeSupport=false` set by default) giving:
```
ivanpovazan@EONE-MAC-ARM64 ~/tmp/net8/CoreCLRXmlSerializer $ rm -rf bin obj ; dotnet publish -r osx-arm64 -p:PublishAot=true
  Determining projects to restore...
  Restored /Users/ivan/tmp/net8/CoreCLRXmlSerializer/CoreCLRXmlSerializer.csproj (in 1.02 sec).
/Users/ivan/tmp/net8/CoreCLRXmlSerializer/Program.cs(20,41): warning IL2026: Using member 'System.Xml.Serialization.XmlSerializer.Deserialize(TextReader)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from deserialized types may be trimmed if not referenced directly. [/Users/ivan/tmp/net8/CoreCLRXmlSerializer/CoreCLRXmlSerializer.csproj]
/Users/ivan/tmp/net8/CoreCLRXmlSerializer/Program.cs(11,16): warning IL2026: Using member 'System.Xml.Serialization.XmlSerializer.XmlSerializer(Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly. [/Users/ivan/tmp/net8/CoreCLRXmlSerializer/CoreCLRXmlSerializer.csproj]
  CoreCLRXmlSerializer -> /Users/ivan/tmp/net8/CoreCLRXmlSerializer/bin/Release/net8.0/osx-arm64/CoreCLRXmlSerializer.dll
  Generating native code
/Users/ivan/tmp/net8/CoreCLRXmlSerializer/Program.cs(20): Trim analysis warning IL2026: Test.TestSerialization(String): Using member 'System.Xml.Serialization.XmlSerializer.Deserialize(TextReader)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from deserialized types may be trimmed if not referenced directly. [/Users/ivan/tmp/net8/CoreCLRXmlSerializer/CoreCLRXmlSerializer.csproj]
/Users/ivan/tmp/net8/CoreCLRXmlSerializer/Program.cs(11): Trim analysis warning IL2026: Test.GetSerializer(Type): Using member 'System.Xml.Serialization.XmlSerializer.XmlSerializer(Type)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Members from serialized types may be trimmed if not referenced directly. [/Users/ivan/tmp/net8/CoreCLRXmlSerializer/CoreCLRXmlSerializer.csproj]
/Users/ivan/.nuget/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/8.0.8/framework/System.Private.Xml.dll : warning IL3053: Assembly 'System.Private.Xml' produced AOT analysis warnings. [/Users/ivan/tmp/net8/CoreCLRXmlSerializer/CoreCLRXmlSerializer.csproj]
  CoreCLRXmlSerializer -> /Users/ivan/tmp/net8/CoreCLRXmlSerializer/bin/Release/net8.0/osx-arm64/publish/
ivanpovazan@EONE-MAC-ARM64 ~/tmp/net8/CoreCLRXmlSerializer $ bin/Release/net8.0/osx-arm64/publish/CoreCLRXmlSerializer
Items is null
```

- More importantly, this specifically impacts mobile device scenarios with Mono where:
    - DynamicCodeSupport=true:
        - when JIT is available, which covers:
            - debug/release builds for .NET Android or .NET MAUI Android apps on both devices and simulators
        - when AOT is required and interpreter enabled, which covers:
            - debug builds for .NET MAUI iOS apps on both devices and simulators (hot reload enabled by default)
    
    - DynamicCodeSupport=false:
        - when AOT is required and interpreter disabled, which covers:
            - release builds for .NET iOS or .NET MAUI iOS apps on both devices and simulators
            - debug builds for .NET iOS apps on both devices and simulators (hot reload disabled by default)

# Additional notes

Switching `DynamicCodeSupport` on and off changes the serialization mode, where when:
- `DynamicCodeSupport=true` serialization mode is `ReflectionAsBackup` 
- `DynamicCodeSupport=false` serialization mode is `ReflectionOnly` 

This was introduced in: https://github.com/dotnet/runtime/commit/b3ab2eb4db830f6c520340f80651b806fd9dfce8 
I haven't looked deeper than this, but if I am not mistaken `ReflectionAsBackup` uses RefEmit which could be producing the different result.

# Workaround 

As mentioned in my comment one workaround could be to add an initalizer on problematic type members.

# For reference: MAUI repro for mobile

<details>
  <summary>Click to expand a repro example for a MAUI app</summary>

This is observable in `.NET9` as well (tested with net9-p7).

1. Create a new MAUI app:
2. Exchange `MainPage.xaml.cs` with:
```cs
using System.Collections.Generic;
using System.IO;
using System.Xml.Serialization;
namespace MauiXmlSerial;

public partial class MainPage : ContentPage
{
	public MainPage()
	{
		InitializeComponent();
	}

	private void OnCounterClicked(object sender, EventArgs e)
	{
		string msg;
		string xml = "<MyClass></MyClass>";

		XmlSerializer serializer = new XmlSerializer(typeof(MyClass));
		using (StringReader reader = new StringReader(xml))
		{
			MyClass result = (MyClass)serializer.Deserialize(reader);
			if (result.Items == null)
			{
				msg = "Items is null";
			}
			else
			{
				msg = $"Items have {result.Items.Count} elements";
			}
		}

		CounterBtn.Text = msg;

		SemanticScreenReader.Announce(CounterBtn.Text);
	}
}

public class MyClass
{
    public List<string> Items { get; set; }
}
```
3. Build/run on iOS simulator with:
```
dotnet build -f net9.0-ios -t:Run
```
4. Click the button on the startup page and observe that it shows: `Items have 0 elements`
5. Build/run on a iOS device with:
```
dotnet build -c Release -f net9.0-ios -r ios-arm64 -t:Run
```
6. Click the button on the startup page and observe that it shows: `Items is null`

</details>

**Comment by ivanpovazan** [comment]
Just reporting some findings on a possible workaround.
Adding a property initializer like:
```cs
public List<string> Items { get; set; } = new();
```
makes the behavior on iOS devices match iOS simulators - deserializing into an empty collection.

**Comment by MichalStrehovsky** [comment]
> * `DynamicCodeSupport=true` is the default setting for Android / iOS simulators / or when interpreter is enabled

Why do we set `DynamicCodeSupport=true` in iOS simulator, but `DynamicCodeSupport=false` in iOS physical device?

**Comment by ivanpovazan** [comment]
> Why do we set DynamicCodeSupport=true in iOS simulator, but DynamicCodeSupport=false in iOS physical device?

Sorry, I wasn't clear enough.

In general, we set `DynamicCodeSupport=true`:
- when JIT is available, which covers:
    - debug/release builds for .NET Android or .NET MAUI Android apps on both devices and simulators
- when AOT is required and interpreter enabled, which covers:
    - debug builds for .NET MAUI iOS apps on both devices and simulators (hot reload enabled by default)

On the other hand, we set `DynamicCodeSupport=false`:
- when AOT is required, which covers:
    - release builds for .NET iOS or .NET MAUI iOS apps on both devices and simulators
    - debug builds for .NET iOS apps on both devices and simulators (hot reload disabled by default)

**Comment by arlm** [comment]
Dear @ivanpovazan and @MichalStrehovsky,

I hope this message finds you well.

I am writing to inquire about the implications of setting the `DynamicCodeSupport=true` feature switch on regular iOS applications as a temporary workaround for the XML deserialization issue. Specifically, I am interested in understanding any potential impacts this setting may have on the process of publishing these applications on the Apple App Store, particularly in the context of compliance with Apple's guidelines and performance considerations.

Given that this workaround is intended to be a temporary measure until the release of .NET 9, your insights on any risks or best practices associated with this approach would be greatly appreciated.

Thank you for your time and assistance.

**Comment by ivanpovazan** [comment]
Hello @arlm,

I am happy to assist you in this.

I would first like to align and understand better the issue you are experiencing, in order to make the right decision.
Therefore, could you please answer a couple of questions?
1. What is the exact problem you are experiencing?
2. Can you provide a crash log and a reproduction steps or a sample code showcasing the issue?
3. What version of .NET are you using?
4. Are you experiencing this when migrating from Xamarin iOS to a MAUI iOS app?
5. Are you experiencing this in Debug and/or Release builds?
6. What is the expected behavior on:
    - iOS device in Release mode
    - iOS device in Debug mode 
    - iOS simulator in Release mode
    - iOS simulator in Debug mode

7. What is the actual behavior on: 
    - iOS device in Release mode
    - iOS device in Debug mode 
    - iOS simulator in Release mode
    - iOS simulator in Debug mode

**Comment by arlm** [comment]
Hi, I will answer inline with your quoted questions:

> I would first like to align and understand better the issue you are experiencing, in order to make the right decision. Therefore, could you please answer a couple of questions?

Sure

> 1. What is the exact problem you are experiencing?

I am experiencing exactly this issue as reported: .NET 6 and above have non-MAUI iOS Apps deserializing missing XML tags from collections (lists or arrays) to null instead of an empty list or array.

> 2. Can you provide a crash log and a reproduction steps or a sample code showcasing the issue?

The sample code was sent to Microsoft through support, I am from the company that reported the issue initially to Microsoft support.

> 3. What version of .NET are you using?

I tried that on .NET 6, 7 and 8 and can confirm the same happens for all the versions. .NET 5 with Xamarin iOS does not behave like that. Also, I have noticed that it only happens when the project is migrated from the old `cdproj`-style to the new SDK-project style.

> 4. Are you experiencing this when migrating from Xamarin iOS to a MAUI iOS app?

.NET 5 with Xamarin iOS => does not happen.
.NET 6, 7 and 8 without MAUI => bug does happen.
.NET 6, 7 and 8 with MAUI => not tested by us yet.

> 5. Are you experiencing this in Debug and/or Release builds?

It happened for both Release and Debug

> 6. What is the expected behavior on:
>    
>    * iOS device in Release mode
>    * iOS device in Debug mode
>    * iOS simulator in Release mode
>    * iOS simulator in Debug mode

All of them should always deserialize empty or missing XML tags as empty collections (list or array), never to `null`

> 7. What is the actual behavior on:
>    
>    * iOS device in Release mode
>    * iOS device in Debug mode
>    * iOS simulator in Release mode
>    * iOS simulator in Debug mode

I will test it thoroughly on Monday and reply with that information (also for MAUI and non-MAUI projects).

**Comment by ivanpovazan** [comment]
Thank you @arlm for the answers, I will reach out to our support team to get the repro project.

At the same time, could you please provide answers to questions 6,7 when you get a chance. 

Thank you in advance.

**Comment by arlm** [comment]
The ticket for you to look for has the TrackingID #2404230030006956

I tested the iOS without MAUI and found that the bug persists across all four configurations:
1. iOS device in Release mode
2. iOS device in Debug mode
3. iOS simulator in Release mode
4. iOS simulator in Debug mode

Additionally, we are not using MAUI, and when I enable the flag, it does not compile at all, preventing me from testing further.

Best regards.

**Comment by arlm** [comment]
But initially, I would like just to understand which would be the consequences or risks of enabling the `DynamicCodeSupport` flag for a regular iOS .NET app without MAUI. I understand it is about JIT versus AOT compilation, but are there more implications?

**Comment by ivanpovazan** [comment]
Thank you for the confirmation.

There are two possible work arounds before this issue is not addressed.

### Option 1 - changing the model

Change your model, by including initializers for collections. 
For example:
    
- instead of:
    
```cs
public List<string> Items { get; set; }
```
    
- use:
    
```cs
public List<string> Items { get; set; } = new();
```

This way, the default configuration for iOS should deserialize to empty collections - achieving the same behavior as on Android.

### Option 2 - enabling the interpreter

Manually altering `DynamicCodeSupport` for iOS is not recommended. This feature switch enables code paths with dynamic code which require either JIT or interpreter execution engines during runtime, without which the app could crash. On iOS, JIT is not allowed by design, and the default execution engine is AOT.

Having said this, as a possible work around, you could enable interpreter for your iOS application by adding the following in your project file:
```xml
<UseInterpreter>true</UseInterpreter>
``` 
which implicitly sets `DynamicCodeSupport=true`. 
However, enabling the interpreter can negatively impact app performance regarding speed and app size.

More info at: https://learn.microsoft.com/en-us/dotnet/maui/macios/interpreter?view=net-maui-8.0

**Comment by arlm** [comment]
Hi @ivanpovazan, on the reproduction project I have sent we have a solution like the Option 1 but using reflection to do that on a custom XML serializer. Unfortunately, option 2 did not work on that reproduction project. Have you tried there? I keep receiving null as deserializing the absent XML elements for collections, instead of an empty collection.

**Comment by arlm** [comment]
Hello @ivanpovazan

I have added you to a private project reproducing all the options you have suggested for issues 1 and 3 so that you can run the same way I am doing (there are scripts for running on device and on simulator).

Baseline is:

Project | DynamicCodeSupport=true | DynamicCodeSupport=false | UseInterpreter=true | UseInterpreter=false
-- | -- | -- | -- | --
issue-107252 | works | bug appears | works | works
issue-108432 | works | bug appears | works | works
XmlSerializationSample on Device | bug appears | bug appears | bug appears | bug appears
XmlSerializationSample on Simulator | works | bug appears | bug appears | bug appears

**Comment by ivanpovazan** [comment]
> [@ivanpovazan](https://github.com/ivanpovazan) even after fixing the wrong assumption, it still does not work on the device. I have a crash because the List is still null.

1. Could you share the stack trace you are getting when the crash happens?
2. Does the crash happen even if you enable the interpreter?

**Comment by arlm** [comment]
> 1. Could you share the stack trace you are getting when the crash happens?
```
2024-10-16 11:33:26.101 XmlSerializationSample[3164:2088908] Error adding Person recursivelly:

============================================
Object reference not set to an instance of an object
2024-10-16 11:33:26.101 XmlSerializationSample[3164:2088908]    at XmlSerializationSample.ResultTableViewSource.AddPersonRecursively(Person person) in /Users/alexandremarcondes/git/XmlProblem-Reproduction/XmlSerializationSample/ResultTableViewSource.cs:line 44
============================================
2024-10-16 11:33:26.101 XmlSerializationSample[3164:2088908] Error adding Person recursivelly:

============================================
Object reference not set to an instance of an object
2024-10-16 11:33:26.101 XmlSerializationSample[3164:2088908]    at XmlSerializationSample.ResultTableViewSource.AddPersonRecursively(Person person) in /Users/alexandremarcondes/git/XmlProblem-Reproduction/XmlSerializationSample/ResultTableViewSource.cs:line 62
2024-10-16 11:33:26.101 XmlSerializationSample[3164:2088908]    at XmlSerializationSample.ResultTableViewSource.AddPersonRecursively(Person person) in /Users/alexandremarcondes/git/XmlProblem-Reproduction/XmlSerializationSample/ResultTableViewSource.cs:line 46
============================================
2024-10-16 11:33:26.101 XmlSerializationSample[3164:2088908] 
============================================
Object reference not set to an instance of an object
2024-10-16 11:33:26.101 XmlSerializationSample[3164:2088908]    at XmlSerializationSample.ResultTableViewSource.AddPersonRecursively(Person person) in /Users/alexandremarcondes/git/XmlProblem-Reproduction/XmlSerializationSample/ResultTableViewSource.cs:line 62
   at XmlSerializationSample.ResultTableViewSource.AddPersonRecursively(Person person) in /Users/alexandremarcondes/git/XmlProblem-Reproduction/XmlSerializationSample/ResultTableViewSource.cs:line 62
2024-10-16 11:33:26.101 XmlSerializationSample[3164:2088908]    at XmlSerializationSample.ResultTableViewSource.LoadXml(XmlSerializer serializer) in /Users/alexandremarcondes/git/XmlProblem-Reproduction/XmlSerializationSample/ResultTableViewSource.cs:line 23
2024-10-16 11:33:26.101 XmlSerializationSample[3164:2088908]    at XmlSerializationSample.ViewController.DefaultXmlReaderButton_TouchUpInside(Object sender, EventArgs e) in /Users/alexandremarcondes/git/XmlProblem-Reproduction/XmlSerializationSample/ViewController.cs:line 210
============================================
```

> 2. Does the crash happen even if you enable the interpreter?

As you can see from the scripts, if you run the script `./run-with-fix-device.sh DEVICE-UUID` you will receive the same error.

**Comment by ivanpovazan** [comment]
@arlm I am sorry but I cannot reproduce your crash. 

I checked out your latest commit: https://github.com/arlm/XmlProblem-Reproduction/commit/a7b84dc5567cae3004b0e2b0eac7181fb764717e
and run the script `./run-with-fix-device.sh DEVICE-UUID`. 
The app successfully starts and clicking each button produces result without a crashing.

Which version of .NET8 are you using?

**Comment by arlm** [comment]
```
❯ dotnet --version
9.0.100-preview.6.24328.19
```

```
❯ dotnet --list-sdks
3.1.426 [/usr/local/share/dotnet/sdk]
5.0.408 [/usr/local/share/dotnet/sdk]
6.0.420 [/usr/local/share/dotnet/sdk]
6.0.421 [/usr/local/share/dotnet/sdk]
6.0.422 [/usr/local/share/dotnet/sdk]
6.0.424 [/usr/local/share/dotnet/sdk]
6.0.425 [/usr/local/share/dotnet/sdk]
7.0.314 [/usr/local/share/dotnet/sdk]
7.0.315 [/usr/local/share/dotnet/sdk]
7.0.316 [/usr/local/share/dotnet/sdk]
7.0.317 [/usr/local/share/dotnet/sdk]
8.0.204 [/usr/local/share/dotnet/sdk]
9.0.100-preview.6.24328.19 [/usr/local/share/dotnet/sdk]
```

```
❯ dotnet --list-runtimes
Microsoft.AspNetCore.App 3.1.32 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.17 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.28 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.29 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.30 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.32 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.33 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.17 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.18 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.19 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.20 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 9.0.0-preview.6.24328.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.32 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.28 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.29 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.30 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.32 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.33 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 9.0.0-preview.6.24327.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

```
❯ dotnet workload list

Installed Workload Id      Manifest Version                         Installation Source  
-----------------------------------------------------------------------------------------
macos                      14.2.9714-net9-p6/9.0.100-preview.6      SDK 9.0.100-preview.6
ios                        17.2.9714-net9-p6/9.0.100-preview.6      SDK 9.0.100-preview.6

Use `dotnet workload search` to find additional workloads to install.
```

**Comment by ivanpovazan** [comment]
Thank you for checking it out. 

The problem is you are using `9.0.100-preview.6.24328.19` which unfortunately had an issue with resolving `UseInterpreter` correctly - and got fixed in: https://github.com/xamarin/xamarin-macios/commit/261a603bc1efa0f444acbfe4e5fec1750ddf7ee4 
The fix became available in the next release (preview 7) and that is the reason I couldn't reproduce.

Could you please try updating to a newer .NET version and try again?

PS You might need to add `<SupportedOSPlatformVersion>17.2</SupportedOSPlatformVersion>` to your project file once you update to a newer version of .NET

**Comment by arlm** [comment]
I installed the `9.0.100-rc.2.24474.11` and have tried both `<SupportedOSPlatformVersion>17.2</SupportedOSPlatformVersion>` and `<SupportedOSPlatformVersion>16.0</SupportedOSPlatformVersion>` and both worked fine for me.

I have noticed that if I start the app by running from the scripts on my reproduction project it works fine, and I have no error both for the serialization and for the deserialization problems. But if I add `<UseInterpreter>true</UseInterpreter>` to the project and start it using Visual Studio for Mac, it does not work and both fail.

**Comment by ivanpovazan** [comment]
> I installed the 9.0.100-rc.2.24474.11 and have tried both <SupportedOSPlatformVersion>17.2</SupportedOSPlatformVersion> and <SupportedOSPlatformVersion>16.0</SupportedOSPlatformVersion> and both worked fine for me.

I am glad it worked.

Regarding:
> But if I add <UseInterpreter>true</UseInterpreter> to the project and start it using Visual Studio for Mac, it does not work and both fail. Do you have any idea why?

What I think happens is that VS for Mac does not support .NET 9 SDK, and that it picks up your latest .NET 8 installation instead (which is `8.0.204` from what you posted above). So I would try installing the latest - `8.0.403` version and try again.

**Comment by arlm** [comment]
> What I think happens is that VS for Mac does not support .NET 9 SDK, and that it picks up your latest .NET 8 installation instead (which is `8.0.204` from what you posted above). So I would try installing the latest - `8.0.403` version and try again.

I have installed the `8.0.403` version and uninstalled all the older versions. I still have the same result when running from Visual Studio.

I also added a `global.json` configuration file and tried running the fix with the `8.0.403` version, and it does not work. Should I expect some kind of fix for that flag on a future version of .NET 8 SDK ?

**Comment by ivanpovazan** [comment]
Does it work when built from CLI? 
Can you generate binlog and share it https://github.com/xamarin/xamarin-macios/wiki/Diagnosis ?

**Comment by arlm** [comment]
Yes, if I changed on the `global.json` configuration file to the `8.0.403` version and the fix does not work on this circumstance.

Here is the binlog, as requested: [msbuild.binlog.zip](https://github.com/user-attachments/files/17546019/msbuild.binlog.zip)

**Comment by ivanpovazan** [comment]
From the binlog I can see you have an older version of iOS workloads `17.2.8078` which is causing the problem.
To have all the necessary bits you will need to use newer workloads version.
There are two options:

- Use the latest workloads by:
    - Upgrading your Xcode to `16.0`
    - Installing the iOS workloads `18.0.*` which can be accomplished by running:  
        ```bash
        dotnet workload update
        ```

Or if you don't want to upgrade to Xcode `16.0`
- Use the workloads version which included the fix by:
    - Upgrading your Xcode to `15.4`
    - Installing the iOS workloads `17.5.*` which can be accomplished by running:
        ```bash
        dotnet workload install ios --version 8.0.402
        ```

**Comment by arlm** [comment]
Hi @ivanpovazan,

I have tested the option with Xcode `15.4` with the following workloads:

```
❯ dotnet workload list

Installed Workload Id      Manifest Version       Installation Source
---------------------------------------------------------------------
macos                      14.0.8478/8.0.100      SDK 8.0.400        
ios                        17.0.8478/8.0.100      SDK 8.0.400        
android                    34.0.43/8.0.100        SDK 8.0.400        
```

And the following `global.json` file:

```json
{
    "sdk": {
        "version": "8.0.403",
        "rollForward": "latestFeature"
    }
}
```

It worked perfectly on the device, but Visual Studio could not load them.

![Image](https://github.com/user-attachments/assets/e09fb822-0b8f-4d22-ab28-528fdd2e3cae)
![Image](https://github.com/user-attachments/assets/4cadf238-71f4-45e3-8d41-100e34e50b6b)
![Image](https://github.com/user-attachments/assets/ab17e1db-71ea-43bf-8c7c-8f802206a03c)

**Comment by ivanpovazan** [comment]
I am glad you managed to resolve it. 

Regarding the issue on Visual Studio for Mac - the IDE has reached EOL and is no longer maintained or supported ([source](https://learn.microsoft.com/en-us/visualstudio/releases/2022/what-happened-to-vs-for-mac)), so it is possible that new workloads (or SDK) are not compatible. Alternative solutions for developing on Mac is to use VS Code and [.NET MAUI extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-maui).

**Comment by arlm** [comment]
OK, I tried that, but as our app is not MAUI I could not use it to debug it.

Now that we have a working workaround, which are the plans to have a fix on .NET 9 that does not need the flag/property to be set to true on the project or on the command-line? Shouldn't it be the default value of this property for native/non-MAUI iOS apps?

**Comment by ivanpovazan** [comment]
> Now that we have a working workaround, which are the plans to have a fix on .NET 9 that does not need the flag/property to be set to true on the project or on the command-line? Shouldn't it be the default value of this property for native/non-MAUI iOS apps?

I am afraid I cannot answer that, as both of the reported issues (this and https://github.com/dotnet/runtime/issues/108432) are XmlSerializer-specific and out of my scope. Maybe @HongGit could provide an answer.
