### ISSUE TITLE
[Wasm] Satellite assemblies for localization are not used

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/runtime#107742]
### Description

When adding `.withConfig({ loadAllSatelliteResources: true })`, satellite assemblies are all downloaded and loaded by the runtime, but using resources from those satellites resources does not work properly.

### Reproduction Steps

The following:

```csharp
var r = new System.Resources.ResourceManager("FxResources.System.Web.Services.Description.SR", typeof(System.Web.Services.Description.Binding).Assembly);
Console.WriteLine($"Res(en): {r.GetString("WebDescriptionMissing", new CultureInfo("en-US"))}");
Console.WriteLine($"Res(fr): {r.GetString("WebDescriptionMissing", new CultureInfo("fr"))}");
```

Repro: [107742-testresources01.zip](https://github.com/user-attachments/files/16981704/107742-testresources01.zip)

### Expected behavior

The second line should return french.

### Actual behavior

```
Res(en): Cannot find definition for {0}.  Service Description with namespace {1} is missing.
Res(fr): Cannot find definition for {0}.  Service Description with namespace {1} is missing.
```

### Regression?

Feels like it is, net8 got it available.

### Known Workarounds

None.

### Configuration

.NET 9 RC1

**Comment by lewing** [comment]
should be fixed in https://github.com/dotnet/runtime/pull/107398

**Comment by jeromelaban** [comment]
The issue is still present with today's rc2:

```
Installed Workload Id      Manifest Version                      Installation Source
------------------------------------------------------------------------------------
wasm-experimental          9.0.0-rc.2.24461.16/9.0.100-rc.2      SDK 9.0.100-rc.2
wasm-tools                 9.0.0-rc.2.24461.16/9.0.100-rc.2      SDK 9.0.100-rc.2
```

**Comment by lewing** [comment]
> The issue is still present with today's rc2:
> 
> ```
> Installed Workload Id      Manifest Version                      Installation Source
> ------------------------------------------------------------------------------------
> wasm-experimental          9.0.0-rc.2.24461.16/9.0.100-rc.2      SDK 9.0.100-rc.2
> wasm-tools                 9.0.0-rc.2.24461.16/9.0.100-rc.2      SDK 9.0.100-rc.2
> ```

fix just merged, tomorrow's sdk should have it

**Comment by jeromelaban** [comment]
@lewing I've tried RC2 again (9.0.100-rc.2.24468.2-win-x64)

```
Installed Workload Id      Manifest Version                     Installation Source
-----------------------------------------------------------------------------------
wasm-experimental          9.0.0-rc.2.24468.6/9.0.100-rc.2      SDK 9.0.100-rc.2
wasm-tools                 9.0.0-rc.2.24468.6/9.0.100-rc.2      SDK 9.0.100-rc.2
```

And the issue is still present.

**Comment by maraf** [comment]
I'll take a look

**Comment by maraf** [comment]
It works with `9.0.100-rc.2.24473.20`. Can you please validate it with this version?

**Comment by jeromelaban** [comment]
@maraf yes, it's needed in production cases. Wouldn't it also affect partial eager loading of some languages?

**Comment by maraf** [comment]
No, it uses a different path in codebase. We have test coverage for his path. The `loadAllSatelliteResources=true` option was added mostly for runtime tests.
