### ISSUE TITLE
.netframework4.7.2 Problem with webrequest asynchronous request

### ISSUE THREAD

**Issue by att1008** [dotnet/runtime#107835]
### Description

When making asynchronous requests, I found that if Task.Factory.FromAsync is used to wrap the request, it will become unresponsive after running for a period of time. My program uses semaphore concurrent 200 to request, and when running for a period of time, it is all blocked. If you use IAsyncResult and ThreadPool.RegisterWaitForSingleObject to request, there is no problem, but after running for a period of time, my memory has increased a lot. I checked with dotmemory and found that the WaitOrTimerCallback was leaked. there are a large number of WaitOrTimerCallback objects. there are 8000 WaitOrTimerCallback in the memory after about 60000 requests.

### Reproduction Steps

        public async Task<HttpResponse?> PostInternalAsync(string method, CancellationToken cancellationToken) {
            HttpWebRequest? webRequest = null;
            try {
                webRequest = ConfigureAsyncWebRequest(method, Url);
                PreparePostBody(webRequest);
                return await WriteRequestBodyTaskAsync(webRequest, cancellationToken).ConfigureAwait(false);
            }
            catch (ObjectDisposedException) {
                webRequest?.Abort();
                var response = new HttpResponse { ResponseStatus = ResponseStatus.TimedOut };
                return ExecuteCallback(response);
            }
            catch (OperationCanceledException) {
                webRequest?.Abort();
                var response = new HttpResponse { ResponseStatus = ResponseStatus.TimedOut };
                return ExecuteCallback(response);
            }
            catch (Exception ex) {
                webRequest?.Abort();
                return ExecuteCallback(CreateErrorResponse(ex));
            }
        }

        async Task<HttpResponse?> WriteRequestBodyTaskAsync(HttpWebRequest webRequest, CancellationToken cancellationToken) {
            if (HasBody || HasFiles || AlwaysMultipartFormData) {
                webRequest.ContentLength = CalculateContentLength();
                var requestStream = await webRequest.GetRequestStreamAsync().WithCancellation(cancellationToken).ConfigureAwait(false);

                using (requestStream) {
                    if (HasFiles || AlwaysMultipartFormData)
                        WriteMultipartFormData(requestStream);
                    else if (RequestBodyBytes != null)
                        await requestStream.WriteAsync(RequestBodyBytes, 0, RequestBodyBytes.Length, cancellationToken).ConfigureAwait(false);
                    else if (RequestBody != null)
                        await requestStream.WriteStringAsync(RequestBody, Encoding, cancellationToken).ConfigureAwait(false);
                }
            }

            return await GetResponseAsync(webRequest, cancellationToken).ConfigureAwait(false);

        }

        async Task<HttpResponse?> GetResponseAsync(HttpWebRequest webRequest, CancellationToken cancellationToken) {
            try {
                var raw = (HttpWebResponse)await webRequest.GetResponseAsync()
                    .WithCancellation(cancellationToken)
                    .ConfigureAwait(false);

                using (raw) {
                    return await ExtractResponseDataAsync(raw, cancellationToken).ConfigureAwait(false);
                }
            }
            catch (WebException ex) {
                if (ex.Status == WebExceptionStatus.RequestCanceled)
                    throw;
                if (ex.Response is not HttpWebResponse exResponse) throw;

                var responseDataAsync = await ExtractResponseDataAsync(exResponse, cancellationToken).ConfigureAwait(false);
                exResponse?.Dispose();
                return responseDataAsync;

            }
        }

        void SetTimeout(IAsyncResult asyncResult) {
            
            if (Timeout != 0) {
                _timeoutState.WaitHandle = asyncResult.AsyncWaitHandle;
                _timeoutState.Handle = ThreadPool.RegisterWaitForSingleObject(
                    asyncResult.AsyncWaitHandle,
                    TimeoutCallback,
                    _timeoutState,
                    Timeout,
                    true
                );
            }

            static void TimeoutCallback(object state, bool timedOut) {
                if (!(state is TimeOutState tos))
                    return;

                lock (tos) {
                    if (!timedOut) {
                        if (tos.Handle != null) {
                            tos.Handle.Unregister(tos.WaitHandle ?? null);
                        }
                        return;
                    }

                    tos.TimedOut = true;
                }

                tos.Request?.Abort();
            }
        }

### Expected behavior

I called the Unregister method to release, but there are still many objects in memory.

### Actual behavior

![image](https://github.com/user-attachments/assets/04299f1b-f5db-4ea5-a17a-5927746694dd)

**Comment by att1008** [comment]
My question is similar to his. He described it in more detail. My English is not very good. Sorry.
[https://stackoverflow.com/questions/41985312/threadpool-registerwaitforsingleobject-httpwebrequest-proxy-c-sharp-net-mem](url)

**Comment by att1008** [comment]
It has been solved. The reason why Task.Factory.StartNew runs slowly for a period of time after packaging is that I also read and write the GetRequestStream and GetResponseStream steams asynchronously and gave cancellationToken, but this cancellationToken did not take effect, causing all Task to be blocked. I wrapped a cancellationToken method behind steam reading and writing to force a timeout, so there is no problem. It seems that the cancellationToken under the steam default method of HTTP request does not work.

**Comment by huoyaoyuan** [comment]
Also reminder that `WebRequest` has been deprecated for a long time. `HttpClient` is the current preferred method and has decent async support.

**Comment by att1008** [comment]
> 另外提醒一下，该方法`WebRequest`已被弃用很长时间。`HttpClient`是当前首选的方法，并且具有良好的异步支持。

Yes, I know that HttpClient is the latest preferred asynchronous solution at present, but my program needs to make HTTP requests with high concurrency, and each request needs different Proxy and Cookie, and HTTP is known to need as few instantiations as possible.

**Comment by am11** [comment]
> HTTP is known to need as few instantiations as possible.

`HttpClientFactory` can be used to produce the `HttpClient` instances with either `DefaultRequestHeaders` per- named client (for group of requests sharing the same cookie/proxy settings), `HttpRequestMessage` for per-request cookie/proxy settings (and still getting client instances from the factory) or using a custom `HttpClientHandler` overriding `SendAsync()`method to accomplish different settings.

**Comment by att1008** [comment]
> > HTTP is known to need as few instantiations as possible.
> 
> `HttpClientFactory` can be used to produce the `HttpClient` instances with either `DefaultRequestHeaders` per- named client (for group of requests sharing the same cookie/proxy settings), `HttpRequestMessage` for per-request cookie/proxy settings (and still getting client instances from the factory) or using a custom `HttpClientHandler` overriding `SendAsync()`method to accomplish different settings.

My program is a crawler program, each request requires different Proxy and Cookie, and my program requires high concurrency and a large number of requests. I cannot set a HttpClientFactory for each Proxy. My requests may have 100000 or more.
