### ISSUE TITLE
Intermittent AccessViolation and NullReference exceptions in reflection-based JsonSerializer

### ISSUE THREAD

**Issue by 0xfeeddeadbeef** [dotnet/runtime#108926]
### Description

I was [benchmarking](https://github.com/0xfeeddeadbeef/STJsonAVRepro) System.Text.Json's reflection-based serializer vs. source-generated one (Bug hunting was not my intention), when I noticed that roughly 2 out of 10 times the reflection-based benchmark crashes when serializing [an object](https://github.com/0xfeeddeadbeef/STJsonAVRepro/blob/master/src/Repro/TestData.cs#L206)[^1] to string. The source-generated benchmark always runs to completion without any errors.

So far, I've seen these two exceptions:

#### `NullReferenceException`

From BenchmarkDotNet output:

```plain
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.ArrayConverter`2.OnWriteResume(Utf8JsonWriter writer, TElement[] array, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.ArrayConverter`2.OnWriteResume(Utf8JsonWriter writer, TElement[] array, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Serialize(Utf8JsonWriter writer, T& rootValue, Object rootValueBoxed)
   at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at STJsonAVRepro.SerializerBenchmarks.UseReflection() in _redacted_\STJsonAVRepro\SerializerBenchmarks.cs:line 38
   at BenchmarkDotNet.Autogenerated.Runnable_0.WorkloadActionNoUnroll(Int64 invokeCount) in _redacted_\STJsonAVRepro\bin\x64\Release\net8.0\60b26e70-14c8-483b-8a6c-9f458c9900a9\60b26e70-14c8-483b-8a6c-9f458c9900a9.notcs:line 316
   at BenchmarkDotNet.Engines.Engine.Measure(Action`1 action, Int64 invokeCount)
   at BenchmarkDotNet.Engines.Engine.RunIteration(IterationData data)
   at BenchmarkDotNet.Engines.EngineStage.RunIteration(IterationMode mode, IterationStage stage, Int32 index, Int64 invokeCount, Int32 unrollFactor)
   at BenchmarkDotNet.Engines.EngineStage.Run(IStoppingCriteria criteria, Int64 invokeCount, IterationMode mode, IterationStage stage, Int32 unrollFactor)
   at BenchmarkDotNet.Engines.EngineWarmupStage.Run(Int64 invokeCount, IterationMode iterationMode, Int32 unrollFactor, RunStrategy runStrategy)
   at BenchmarkDotNet.Engines.EngineWarmupStage.RunWorkload(Int64 invokeCount, Int32 unrollFactor, RunStrategy runStrategy)
   at BenchmarkDotNet.Engines.Engine.Run()
   at BenchmarkDotNet.Autogenerated.Runnable_0.Run(IHost host, String benchmarkName) in _redacted_\STJsonAVRepro\bin\x64\Release\net8.0\60b26e70-14c8-483b-8a6c-9f458c9900a9\60b26e70-14c8-483b-8a6c-9f458c9900a9.notcs:line 181
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in _redacted_\STJsonAVRepro\bin\x64\Release\net8.0\60b26e70-14c8-483b-8a6c-9f458c9900a9\60b26e70-14c8-483b-8a6c-9f458c9900a9.notcs:line 57
```

#### `AccessViolationException`

From Windows Event Log:

```plain
Application: dotnet.exe
CoreCLR Version: 8.0.1024.46610
.NET Version: 8.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Stack:
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, Void**, System.Signature, Boolean)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(System.Object, System.Span`1<System.Object>, System.Reflection.BindingFlags)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Reflection.MethodBase.Invoke(System.Object, System.Object[])
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(System.String[])
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.Main(System.String[])
```

#### `Access Violation C0000005`

Sometimes, the benchmark runner is unable to catch an exception and the entire process crashes.

From Windows Event Log:

```plain
Faulting application name: dotnet.exe, version: 8.0.1024.46610, time stamp: 0x66e8bd32
Faulting module name: coreclr.dll, version: 8.0.1024.46610, time stamp: 0x66e8b9ff
Exception code: 0xc0000005
Fault offset: 0x00000000001c830e
Faulting process id: 0x1fcc
Faulting application start time: 0x01db1fc1161b5bd6
Faulting application path: C:\Program Files\dotnet\dotnet.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\coreclr.dll
Report Id: a912bf7b-32a9-4c32-ab23-3169897bb5c7
Faulting package full name: 
Faulting package-relative application ID: 
```

[^1]: The class definition has been borrowed from [System.Text.Json's unit tests](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/tests/Common/TestClasses/TestClasses.SimpleTestClass.cs) with some modifications.

### Reproduction Steps

1. Clone the repository: https://github.com/0xfeeddeadbeef/STJsonAVRepro
2. Run it multiple times until it crashes (Keep an eye on BenchmarkDotNet's output window)
3. Search for errors using Windows Event Viewer

### Expected behavior

The benchmark finishes without any problems.

### Actual behavior

Sometimes it crashes either with AccessViolationException or NullReferenceException.

### Known Workarounds

Use the source-generated serializer. It never crashed (so far).

### Configuration

.NET Runtime `8.0.10`
.NET SDK `8.0.403`
OS: Windows Server 2022, version 21H2 (`10.0.20348.2762`)
Architecture: x64

```plain
Processor	Intel(R) Core(TM) i9-14900K   3.20 GHz
System type	64-bit operating system, x64-based processor
```

**Comment by eiriktsarpalis** [comment]
Would it be possible to isolate your repro to a console app that doesn't use BDN? If it's intermittent you could try running the same workload in a loop or parallel loop depending on what triggers this.

**Comment by 0xfeeddeadbeef** [comment]
> Would it be possible to isolate your repro to a console app that doesn't use BDN? If it's intermittent you could try running the same workload in a loop or parallel loop depending on what triggers this.

Wrote a simple loop: https://github.com/0xfeeddeadbeef/STJsonAVRepro/blob/simple-loop/src/Repro/Program.cs

Ran it under [ProcDump](https://learn.microsoft.com/en-us/sysinternals/downloads/procdump) and this is what I got after several attempts:

```plain
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Text.Ascii.WidenAsciiToUtf16(Byte*, Char*, UIntPtr)
   at System.Text.Unicode.Utf8Utility.TranscodeToUtf16(Byte*, Int32, Char*, Int32, Byte* ByRef, Char* ByRef)
   at System.Text.UTF8Encoding.GetChars(Byte*, Int32, Char*, Int32)
   at System.Text.Json.JsonReaderHelper.TranscodeHelper(System.ReadOnlySpan`1<Byte>)
   at System.Text.Json.JsonSerializer.WriteString[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef, System.Text.Json.Serialization.Metadata.JsonTypeInfo`1<System.__Canon>)
   at Program.<Main>$(System.String[])
```

Unfortunately, it failed to capture the corresponding crash dump.

**Comment by eiriktsarpalis** [comment]
I tried running this a few times but haven't been able to reproduce. What architecture are you running? OS version? Debug or Release build? Any other information on the reproduction you could share?

**Comment by 0xfeeddeadbeef** [comment]
> I tried running this a few times but haven't been able to reproduce. What architecture are you running? OS version? Debug or Release build? Any other information on the reproduction you could share?

It is a Release build.

I've already shared the rest in 'Configuration' section of my original post.

I'm going to try to reproduce this on other computers to I have access to.

**Comment by tannergooding** [comment]
It is potentially worth running the `Intel Processor Diagnostic Tool` to validated the processor is operating as expected and is not missing any microcode patches: https://www.intel.com/content/www/us/en/download/15951/intel-processor-diagnostic-tool.html

There were other stability issues on a subset of 13th and 14th gen processors that were fixed by such microcode patches, for example: https://community.intel.com/t5/Blogs/Tech-Innovation/Client/Intel-Core-13th-and-14th-Gen-Desktop-Instability-Root-Cause/post/1633239

**Comment by 0xfeeddeadbeef** [comment]
> It is potentially worth running the `Intel Processor Diagnostic Tool` to validated the processor is operating as expected and is not missing any microcode patches: https://www.intel.com/content/www/us/en/download/15951/intel-processor-diagnostic-tool.html
> 
> There were other stability issues on a subset of 13th and 14th gen processors that were fixed by such microcode patches, for example: https://community.intel.com/t5/Blogs/Tech-Innovation/Client/Intel-Core-13th-and-14th-Gen-Desktop-Instability-Root-Cause/post/1633239

Thank you for pointing me in the right direction.

I've applied the microcode patch. Intel Diagnostic Tool tests did pass both before and after applying the patch, but my repro is still failing. Looks like the CPU is already severely damaged and cannot be fixed by a microcode update. I was aware of Intel's FDIV and F00F bugs, but this new one takes the cake.

**Comment by jkotas** [comment]
> Looks like the CPU is already severely damaged and cannot be fixed by a microcode update.

FWIW, I do not think we have proven conclusively that this is a hardware issue.

It would be useful to collect several crash dumps to see where the crash is.

Also, you can try disabling hardware intrinsics e.g. by setting `DOTNET_EnableAVX2=0` env variable to check whether the crash only repros when the runtime uses more recent hardware intrinsics.

**Comment by 0xfeeddeadbeef** [comment]
> I'm going to try to reproduce this on other computers to I have access to.

Unable to reproduce on these systems:

```plain
Intel Core i7-8700  (Windows 10)
Intel Core i5-8600K (Windows 10)
Intel Core i7-8565U (Windows 10)
Intel Core i3-8100  (Windows 8.1)
Intel Core i7-4771  (Windows 8.1)
```

> Also, you can try disabling hardware intrinsics e.g. by setting DOTNET_EnableAVX2=0 env variable[...]

Tried that and also went even further by disabling more intrinsics:

```batch
@echo off
set DOTNET_EnableAES=0
set DOTNET_EnableAVX=0
set DOTNET_EnableAVX2=0
set DOTNET_EnableAVX512F=0
set DOTNET_EnableBMI1=0
set DOTNET_EnableBMI2=0
set DOTNET_EnableFMA=0
set DOTNET_EnableHWIntrinsic=0
set DOTNET_EnableIncompleteISAClass=0
set DOTNET_EnableLZCNT=0
set DOTNET_EnablePCLMULQDQ=0
set DOTNET_EnablePOPCNT=0
set DOTNET_EnableSSE=0
set DOTNET_EnableSSE2=0
set DOTNET_EnableSSE3=0
set DOTNET_EnableSSE3_4=0
set DOTNET_EnableSSE41=0
set DOTNET_EnableSSE42=0
set DOTNET_EnableSSSE3=0
.\STJsonAVRepro.exe
```

and it was still crashing on my system (`Intel Core i9-14900K`) with same exceptions.

Meanwhile, my motherboard vendor, ASUS, released a new BIOS update, containing additional over-voltage protections, which I promptly installed.

As a result, I can no longer reproduce this issue on my system and didn't get a change to capture a dump.

Looks like, after all, it was a hardware issue specific to my motherboard + CPU configuration.
