### ISSUE TITLE
IOptionsMonitor<T>.OnChange is fired whenever anything changes in IConfiguration - pit of failure

### ISSUE THREAD

**Issue by petrroll** [dotnet/runtime#109445]
`IOptionsMonitor<T>` is the .NET abstraction to handle dynamically changing configuration. That means changes to config file on filesystem during development but also potentially frequent changes through a dynamic config service s.a. Microsoft's internal ones or others. 

It provides an option to register callback `IOptionsMonitor<T>.OnChange(...)` which is fired when the configuration that's bound to T changes. 

One would assume that the callback is only called when the config section specific to the `IOptionsMonitor` changes. As the [docs don't say otherwise](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.options.ioptionsmonitor-1.onchange?view=net-8.0).

That is, however, not true (see [github issue](https://github.com/dotnet/extensions/issues/2671)). The .OnChange callbacks can be invoked even if an unrelated section for some other T changes. Essentially as long as any part of configuration changes, all `IOptionsMonitorcan` trigger their `.OnChange` callbacks. 

It wouldn't be a problem if everyone handled this correctly and actually did rebuilding only if the config actually changes. But regrettably that's not happening. 

I think it's not happening because it's almost impossible to not fall into this pit of failure as nothing in the API suggests it would be necessary. And furthermore, doing the right thing is surprisingly, if not difficult, then cumbersome. OnChange for some reason doesn't surface last version of config, only current; so anyone wanting to properly guard against non-changes needs to save the old version themselves, ... .

It's not a huuuuge problem because usually it's just recreating stuff. In case of polly a stateful policies there might be some impact but genenerally it should be functionally ok. The issue is that if all components start rebuilding with each update, service owners will see spikes that don't make much sense. 

What to do with it (some random ideas): 

- Update docs to make sure this caveat is documented. Ideally added as remark even for intellisense on that method.
- Surface old version of config objects on the callback (separate overload, for backwards compatibility).
- ?Provide better API for config providers to only raise the event for relevant sub-sections?
- ?If T is IComparible<T> then only raise the event if something actually changed?

**Comment by rjgotten** [comment]
>Provide better API for config providers to only raise the event for relevant sub-sections?

This applies in general to the _entirety_ of `Microsoft.Extensions.Configuration` and how it manages its data into 'sections' - because the entire approach is flawed, ground-up.

Sections aren't actually sections. They are _projections_ that filter part of a key.
This also means that things like collection iteration, in particular for large pools of items, have to iterate linearly over **EVERY** key in the entire config system, up from the root to the leaf, and and have to manually perform a `StartsWith` check on a prefix, followed by an index or dictionary key value.

It can be an **incredibly** big performance killer, and has in fact been reported before as such in #65885

**Comment by petrroll** [comment]
Yet again, another code was written that doesn't take this into account. This time any config change evicts caches of all logging samplers which can have rather nontrivial perf impact in terms of sudden hiccups:

https://source.dot.net/#Microsoft.Extensions.Telemetry/Sampling/RandomProbabilisticSampler.cs,365c43912fa08496,references

**Comment by akoeplinger** [comment]
@petrroll might be worth raising a separate issue for that one

**Comment by petrroll** [comment]
My point wasnt to raise the issue about that code being written differently. For that I engaged the author directly internally :) 

My point was to illustrate that the api design currently is unfortunate.

**Comment by aragia** [comment]
I'd really like to see this fixed in some manner, this is essentially a blocker for IOptionsMonitor for me :/

OnChange probably works fine if you're not recreating a bunch of stuff (like feature flagging a piece of code), but if I don't do duplicated guard logic in every worker of mine, they'll all re-create / re-run even though nothing changed
Even if it's not fatal and it all works out, it's all at once and noisy for no reason

**Comment by rjgotten** [comment]
> @aragia 
> OnChange probably works fine if you're not [..]

Unless the old issue with the resulting config keys 'some times' being `null` when `OnChange` happens, was actually resolved and I missed it &mdash; no: it still doesn't work well. Completely unreliable.

And that's [not the only way](https://github.com/dotnet/runtime/issues/119883) in which it is flaky.

**Comment by rosebyte** [comment]
I happened to make some changes and had to learn how the whole mechanism of propagating changes through the configuration stack works. I agree with @rjgotten that at the level where changes are fired, there are no sections, and even if we wanted to compare what changed, we do not really have any way to do so.
