### ISSUE TITLE
System.Text.Json Can't deserialize decimal properties (possibly a bug)

### ISSUE THREAD

**Issue by ollie10** [dotnet/runtime#1366]
Hi, I'm stuck on this problem
**.Net Core 3.1 Web App** with a page that uses **Google Maps Autocomplete** and I need to save the address and coordinates (**Latitude / Longitude as decimals**).

Creating an **object in javascript** and sending it to the controller via **jQuery Ajax**.

The problem is the following:

- I'm using the default **System.Text.Json** serializer / deserializer
- The decimal values returned by **google Js** API are in this format: _**55.7539619**_ (for example)
- I use a **route parameter to set statically the Culture** like site.com/spain/ for **es-ES** site.com/russia/ for **ru-RU**

In the controller all the other properties arrive correctly except the latitude and longitude which are **decimals**

The problem arises when a culture is being used and the number is not in the format of that culture in the way that the separator is comma (for Spain for example) and not the point (which is standard for javascript)

So i looked for some solutions but none of them seems solving completely the problem:

- i could replace the dot with comma before sending but it won't work for US culture for example, and besides that I would lose precision

In Newtonsoft Json there was the possibility to specify the Culture as options of the serializer but System.Text.Json doesn't have a property like that.
I think that System.Text.Json should deserialize Json in the correct format more than 'interpreting' the culture

This is the code I'm using:

```javascript
propertyToSave.OtherProp = 'text' // arrives correctly as all the other properties
propertyToSave.Latitude = selectedPlace.geometry.location.lat(); //val: 55.7539619
propertyToSave.Longitude = selectedPlace.geometry.location.lng();// val: 37.60819619999995

$.ajax({
	url: "/" + countryInfo.EnglishName.toLowerCase() + "/submit",
	dataType: "json",
	method: "POST",
	data: { property: propertyToSave, __RequestVerificationToken: $("input[name=__RequestVerificationToken]").val() },
	....
```
I specify that if i replace dots with commas the values arrive correctly to the controller, in any other case the **properties are always 0**

Any suggestion? Is a known problem? I suppose the Web API should suffer of this problem too

**Comment by bCamba** [comment]
I am also having problems with this issue. Will this only be fixed in 5.0?

**Comment by massamino** [comment]
I have the same error when I get a request from a remote API.
JSON has numbers as `0.1234`, but when I put it in a `decimal` parameter, it becomes `0`.

Json:
`{ ..., "prices": [{"from": 0, "to": 10, "cost": 0.123}, ... ]}`

Class
```cs
Class Price {
   public int From { get; set; }
   public int To { get; set; }
   public decimal Cost { get; set; }
}
```
Class output: `From = 0, To = 10, Cost = 0`

**Comment by layomia** [comment]
Moving this to future - adding built-in logic for culture-aware number handling is currently not on the roadmap for System.Text.Json. It looks like OP had a workaround which involved changing the property type from `decimal` to `double`. Another workaround here is to write a [custom converter](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to) to provide handling needed for each specific scenario.

Any support that involves allowing commas in number payloads would need to build atop support for [deserializing quoted numbers](https://github.com/dotnet/runtime/issues/30255). The numbers would need to be quoted, otherwise the JSON payload would be malformed.

**Comment by eiriktsarpalis** [comment]
If I'm understanding the OP correctly, the issue boils to the following reproduction:
```csharp
const double number = 3.1415926;
string numberStr = number.ToString(System.Globalization.CultureInfo.GetCultureInfo("de-DE")); // 3,1415926
JsonSerializer.Deserialize<double>(numberStr); // throws JsonException: ',' is invalid after a single JSON value. Expected end of data.
```
We might want to consider adding adding a `CultureInfo` property to `JsonSerializerOptions` like [Json.NET is doing](https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonSerializer_Culture.htm).

**Comment by ollie10** [comment]
Hello @eiriktsarpalis @layomia @danmoseley , any news on this topic? I just posted a [question on StackOverflow](https://stackoverflow.com/questions/71967431/system-text-json-unable-to-deserialize-doubles-properly-with-culture) becuas it's still happening, 2 years after has been reported...

Nothing to do? Many thanks

**Comment by eiriktsarpalis** [comment]
@ollie10 we haven't been able to prioritize this issue yet. Have you considered trying some of the suggested workarounds, like using a custom converter for decimal?

**Comment by ollie10** [comment]
At the moment i'm passing it as a string as another parameter and then deserializing it manually but it's as said a workaround...

**Comment by eiriktsarpalis** [comment]
That should not be necessary if you register a custom converter for your type, see https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-6-0

**Comment by ollie10** [comment]
many thanks @eiriktsarpalis I used this solution which is more elegant even if it remains a workaround and it's weird it hasn't been covered yet. I mean, these are numbers coming from javascript, javascript doesn't allow culture when serializing / deserializing, why the default behaviour it should?
Anyway if it is useful for someone this is my code and I added the DataAnnotation the the properties I want to deserialize

```csharp 
public class DoubleJsonConverter : JsonConverter<double>
{
	public override double Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
	{
		return double.Parse(reader.GetString(), CultureInfo.InvariantCulture);
	}

	public override void Write(Utf8JsonWriter writer, double doubleValue, JsonSerializerOptions options)
	{
		writer.WriteStringValue(doubleValue.ToString(CultureInfo.InvariantCulture));
	}
}
```

**Comment by eiriktsarpalis** [comment]
FWIW it should be possible to avoid annotating every single `double` property by adding the converter to the `JsonSerializerOptions.Converters` list.

**Comment by ollie10** [comment]
Thanks but those two were the only two in the whole application

**Comment by ollie10** [comment]
Hello again @eiriktsarpalis @danmoseley @layomia, I was double-checking the issue and seems is not solved.
I mean the solution of the converter works properly, but I just realized I was terribly wrong, I'm **not** sending data posting a JSON from jQuery, but it's been sent via a normal post form via jQuery so the deserializer doesn't enter the equation, in fact the method _Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)_ is never been called when the controller needs to bind the posted form to the object

So I further investigated to send the object as a JSON but without any success: the **[FromBody]** annotation in the controller it doesn't work in my case (don't know if I'm doing something wrong) but even if it would work then I would have another problem: sending the **object as JSON** and sending the **__RequestVerificationToken** as a normal POST parameter to pass the check **[ValidateAntiForgeryToken]**
As far as I know, I cannot send some objects as JSON and some as normal POST parameters in the same ajax call, so I don't see it an option.

The curious thing is that I realized that a normal post would work if the thread culture is set in **en-US** which is not my case as I mentioned you before, I have a custom **RequestCultureProvider** that map the route **/panama/ to es-PA**, **/dominicana/ to es-DO** and so on.

But the big problem which I think is causing a lot of headaches is that I don't have a way to change the culture to interpret the values in a specified culture, what I can eventually do is passing the **Accept-Language** header in the call specifying the culture and in this way the way numbers are red.

```js
$.ajax({
	url: 'url',
	data: { property: propertyToSave, __RequestVerificationToken: $('input[name=__RequestVerificationToken]').first().val() },
	timeout: DEFAULT_AJAX_TIMEOUT,
	dataType: 'json', // this is what I'm expecting from the server not the format is sent
	method: 'POST',
	beforeSend: function (request) {
		request.setRequestHeader('Accept-Language', 'en-US');
	},
...
```

I did it so but is not working, my question is: the framework shouldn't take this into account in order to bind objects instead of other things? This can cause a lot of troubles, for example, imagine if you have an application which doesn't set any culture on an American server which provides content to a browser which doesn't have the same culture.

In my case I'm setting it manually from the routing but if you don't do it so, it can take the one of the server or the browser depending on how it's configured and can cause a lot of troubles...
Don't know if you see my point

**Comment by eiriktsarpalis** [comment]
It would seem like this is an issue related to aspnetcore MVC model binding? I would suggest filing filing a separate issue on the [aspnetcore ](https://github.com/dotnet/aspnetcore/) repo, and possibly incorporate an application with a minimal reproduction in your report.

**Comment by ArthurMa1978** [comment]
The ask is adding a [CultureInfo](https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonSerializer_Culture.htm)  option into the [JsonDocumentOptions](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsondocumentoptions?view=net-7.0).
We got similar issue, all serialize / deserialize operations will fail if [set culture](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.currentculture) to some special region, like Russian (ru-RU).

**Comment by ollie10** [comment]
Problem notified 3,5 years ago, still not solved. Probably, MS thinks the world is only the United States and the whole world uses points instead of commas, which is actually the other way around: the whole world uses commas instead of points. Maybe they will make us a grace for .NET 15...

**Comment by ollie10** [comment]
5 Years still no solution, this is unbelievable...

**Comment by AkazaRenn** [comment]
Please...
