### ISSUE TITLE
dotnet bug on MacOS Catalina 10.15.2

### ISSUE THREAD

**Issue by kgkoutis** [dotnet/runtime#2250]
I just downloaded it today from https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial/install

<img width="568" alt="Screenshot 2020-01-27 at 21 27 42" src="https://user-images.githubusercontent.com/47277030/73211177-05de5c00-414c-11ea-8bbe-48908972a32d.png">

**Comment by jkotas** [comment]
cc @jeffschwMSFT

**Comment by jeffschwMSFT** [comment]
@kgkoutis we are working through getting our packages notarized.  As part of that change, we are also runtime hardening and providing a default set of entitlements for ./dotnet (which enable it to load dynamic libraries).  I offer that as I have seen similar failure paths on 10.5.* when not using our notarized package.

It is my understanding that regardless of notarization this should be working correctly.   I just installed 3.1.1 on my 10.15.2 system and I am not seeing this behavior.  I see that the commit is different (I am seeing b377529961).  Where did you get this package?

https://download.visualstudio.microsoft.com/download/pr/749db4bc-73c3-4ffb-a545-c315dc9a0ca8/5281258f5dcae636efe557b8b305e20b/dotnet-sdk-3.1.101-osx-x64.pkg

**Comment by kgkoutis** [comment]
@jeffschwMSFT I see the difference in the commit, however following the link that you gave me did not solve the issue. Also, the commit appears the same.

**Comment by kgkoutis** [comment]
@jeffschwMSFT Update: using `brew cask install dotnet-sdk` did the trick for me. Thanks for the help
