### ISSUE TITLE
ICorDebugManagedCallback::DebuggerError when unloading AssemblyLoadContext

### ISSUE THREAD

**Issue by chuckries** [dotnet/runtime#2317]
Running the following code in VS d16.5 typically fails with an error dialog due to the CLR's debugging interfaces returning DebuggerError with the error set to E_INVALIDARG.

```
using System;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Loader;

namespace PlugInTest
{
    class Program
    {
        //TODO: insert absolute path to managed dll
        static string pluginPath = @"C:\MyPlugin.dll";
        static AssemblyLoadContext AssemblyLoadContext;
        static Assembly Assembly;

        [MethodImpl(MethodImplOptions.NoInlining)]
        private static void Load()
        {
            AssemblyLoadContext = new AssemblyLoadContext("PluginLoader", true);
            Assembly = AssemblyLoadContext.LoadFromAssemblyPath(pluginPath);
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        private static WeakReference Unload()
        {
            Assembly = null;
            AssemblyLoadContext.Unload();
            WeakReference weakRef = new WeakReference(AssemblyLoadContext);
            AssemblyLoadContext = null;
            return weakRef;
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        private static void Test()
        {
            WeakReference weakRef;
            {
                Load();
                weakRef = Unload();
            }

            while (weakRef.IsAlive)
            {
                GC.Collect();
                GC.WaitForPendingFinalizers();
            }
            Console.WriteLine("Finished Test");
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        static void Main(string[] args)
        {
            Test();
            Test();
            Test(); //crashs here at GC.Collect
        }
    }
}
```

originally reported here: https://developercommunity.visualstudio.com/content/problem/698374/vs2019-and-fatal-error-has-occurred-and-debugging.html

**Comment by cedricmelancon** [comment]
Duplicate of https://github.com/dotnet/runtime/issues/535.

Not sure if it's a runtime issue or a Visual Studio issue, but it's a show stopper for us. Impossible to debug our plugin management except by putting console comments since it crashes.

**Comment by waldnercharles** [comment]
I don't believe this is a visual studio issue. The issue occurs when debugging in Visual Studio, VS Code, _or_ IntelliJ Rider.

I have not yet tested with Samsung's netcoredbg here: https://github.com/Samsung/netcoredbg

**Comment by chuckries** [comment]
There is a small chance that the root issue is somewhere in the VS Debugger portion of the managed debugger that is shared between VS/VS Code, but I need somebody on the runtime to investigate and confirm/deny.

**Comment by tommcdon** [comment]
@hoyosjs is investigating

**Comment by tommcdon** [comment]
possibly related to dotnet/coreclr#26830

**Comment by nxrighthere** [comment]
I've encountered the exact same problem in the application with `hostfxr` library. More information can be found starting from [this](https://github.com/dotnet/runtime/issues/11546#issuecomment-581017842) comment.

**Comment by hoyosjs** [comment]
Hey @baehny, I've reopened this issue to track a 3.1 port. Given that this has a developer experience report with some feedback I think I can justify it. Can you explain a bit here of how this affects you for when I try to explain the customer impact? Thanks 😄

**Comment by baehny** [comment]
In general when developing/using the usecases that where described in the .net core announcement
under Assembly Unloadability:
https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0/
Developing such scenarios is slowed down as it is not possible to debug any scenario that
requires assembly unloading.

I'm working on an application that allows plugin loading and because of
long loading times the application keeps running while only the plugin is
reloaded if a newer version should be tested.
Additionally some plugins were recompiled/reloaded to make use of generated IL.
Without this fix the application must be restarted or tested without a debugger attached.
This makes plugin development very annoying and less attractive.

**Comment by hoyosjs** [comment]
Thanks @baehny! Can you also confirm this is fixed if you use a 5.0 nightly runtime? Or do you not have a way to verify this.

**Comment by baehny** [comment]
I'm not sure. How can I get a nightly build of the runtime ?

I only found the preview SDK Version: 5.0.100-preview.2.20120.11 at
https://github.com/dotnet/core-sdk/blob/master/README.md

Sadly this build still crashs using Visual Studio16.5.0 Preview 2.0 and the test program described in https://developercommunity.visualstudio.com/content/problem/698374/vs2019-and-fatal-error-has-occurred-and-debugging.html

**Comment by baehny** [comment]
I can confirm the issue is fixed using the current preview version: 5.0.0-preview.2.20128.16

**Comment by nxrighthere** [comment]
@hoyosjs Any rough estimation when we can expect this to be backported to the 3rd version?

**Comment by hoyosjs** [comment]
@nxrighthere dotnet/coreclr#28023 is the PR that's porting it to 3.1 (not 3.0). As for when, I'd expect 3.1.4, exact dates are shifting a bit looks like but it's the April release. As I get more information I'll let you know.

**Comment by hoyosjs** [comment]
The fix got merged and will be available in 3.1.4

**Comment by nxrighthere** [comment]
@hoyosjs We are almost in May, any news about 3.1.4 release?

**Comment by hoyosjs** [comment]
@nxrighthere I just took a look at the release candidate for 3.1.4 and can confirm it contains the fix. However we are waiting for some teams to give their thumbs up for the release. Given the current situation worldwide we are trying to tread very carefully to make sure we don't anything that might regress customers.

**Comment by hoyosjs** [comment]
@nxrighthere I've been told May 12

**Comment by nxrighthere** [comment]
@hoyosjs Awesome, thanks!

**Comment by janvorli** [comment]
@nxrighthere it was released today.

**Comment by nxrighthere** [comment]
@janvorli Yes, thank you! We already upgraded, the issue is gone.

**Comment by rodrmoya** [comment]
This keeps happening for me on 3.1 on Mac with both vsmac and vscode, with 3.1.404 SDK.

**Comment by rodrmoya** [comment]
Same on Linux with 3.1.404, same crash after a few minutes debugging

**Comment by mari-dot-tj** [comment]
Same here. Running on macOS Catalina 10.15.7 and Visual Studio for Mac (Professional) 8.8.3.
_A fatal error has occurred and debugging needs to be terminated. For more details, please see the Microsoft Help and Support web site. HRESULT=0x80131c36. ErrorCode=0x0.The program '[21368] Core.dll' has exited with code -1 (0xffffffff)._
Running .net Core 3.1.404

**Comment by janvorli** [comment]
@mari-dot-tj than you for the details. @dotnet/dotnet-diag this error is different, the error code is CORDBG_E_TARGET_INCONSISTENT.

**Comment by mari-dot-tj** [comment]
@janvorli I see! Is this an already known issue?

**Comment by janvorli** [comment]
It doesn't seem like a known issue, but I've tagged the diagnostics folks who might know more and would most likely do the investigations. Can you please create a new issue for your problem? It will be better than piggy backing on a closed issue.

**Comment by mari-dot-tj** [comment]
Sure! I'll do that.
