### ISSUE TITLE
Restore failing on our projects

### ISSUE THREAD

**Issue by jaredpar** [dotnet/runtime#35057]
Failure from the restore

```
      Restore and Build Product (00:02:06.8766666) (CmdLine) Failed
        error Code: .dotnet\sdk\5.0.100-preview.4.20202.8\NuGet.RestoreEx.targets(10,5): error : (NETCORE_ENGINEERING_TELEMETRY=Restore) The project file could not be loaded. Could not find a part of the path 'F:\workspace\_work\1\s\src\libraries\Common\tests\CoreFx.Private.TestUtilities.Unicode\CoreFx.Private.TestUtilities.Unicode.csproj'.  F:\workspace\_work\1\s\src\libraries\Common\tests\CoreFx.Private.TestUtilities.Unicode\CoreFx.Private.TestUtilities.Unicode.csproj
   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)
   at Microsoft.Build.Shared.ProjectFileErrorUtilities.ThrowInvalidProjectFile(BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)
   at Microsoft.Build.Construction.ProjectRootElement.LoadDocument(String fullPath, Boolean preserveFormatting, Boolean loadAsReadOnly)
   at Microsoft.Build.Construction.ProjectRootElement..ctor(String path, ProjectRootElementCacheBase projectRootElementCache, Boolean preserveFormatting)
   at Microsoft.Build.Construction.ProjectRootElement.CreateProjectFromPath(String projectFile, ProjectRootElementCacheBase projectRootElementCache, Boolean preserveFormatting)
   at Microsoft.Build.Evaluation.ProjectRootElementCache.Get(String projectFile, OpenProjectRootElement openProjectRootElement, Boolean isExplicitlyLoaded, Nullable`1 preserveFormatting)
   at Microsoft.Build.Construction.ProjectRootElement.OpenProjectOrSolution(String fullPath, IDictionary`2 globalProperties, String toolsVersion, ProjectRootElementCacheBase projectRootElementCache, Boolean isExplicitlyLoaded)
   at Microsoft.Build.Evaluation.Project.ProjectImpl..ctor(Project owner, String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)
   at Microsoft.Build.Evaluation.Project.FromFile(String file, ProjectOptions options)
   at NuGet.Build.Tasks.Console.MSBuildStaticGraphRestore.<>c__DisplayClass37_1.<LoadProjects>b__0(String path, Dictionary`2 properties, ProjectCollection collection)
   at Microsoft.Build.Graph.GraphBuilder.ParseProject(ConfigurationMetadata configurationMetadata)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Build.Graph.ParallelWorkSet`2.ExecuteWorkItem()
   at Microsoft.Build.Graph.ParallelWorkSet`2.<CreateProcessorItemTask>b__16_0()
   at Microsoft.Build.Graph.ParallelWorkSet`2.WaitForAllWorkAndComplete()
   at Microsoft.Build.Graph.GraphBuilder.FindGraphNodes()
   at Microsoft.Build.Graph.GraphBuilder.BuildGraph()
   at Microsoft.Build.Graph.ProjectGraph..ctor(IEnumerable`1 entryPoints, ProjectCollection projectCollection, ProjectInstanceFactoryFunc projectInstanceFactory, Int32 degreeOfParallelism, CancellationToken cancellationToken)
   at Microsoft.Build.Graph.ProjectGraph..ctor(IEnumerable`1 entryPoints, ProjectCollection projectCollection, ProjectInstanceFactoryFunc projectInstanceFactory)
   at NuGet.Build.Tasks.Console.MSBuildStaticGraphRestore.LoadProjects(IEnumerable`1 entryProjects)
```

|Build|Kind|Timeline Record|
|---|---|---|
|[601436](https://dev.azure.com/dnceng/public/_build/results?buildId=601436)|PR https://github.com/dotnet/runtime/pull/34984|Restore and Build|
|[601436](https://dev.azure.com/dnceng/public/_build/results?buildId=601436)|PR https://github.com/dotnet/runtime/pull/34984|Restore and Build|
|[601436](https://dev.azure.com/dnceng/public/_build/results?buildId=601436)|PR https://github.com/dotnet/runtime/pull/34984|Restore and Build|
|[601436](https://dev.azure.com/dnceng/public/_build/results?buildId=601436)|PR https://github.com/dotnet/runtime/pull/34984|Restore and Build Product|
|[600968](https://dev.azure.com/dnceng/public/_build/results?buildId=600968)|PR https://github.com/dotnet/runtime/pull/34837|Restore and Build|
|[600968](https://dev.azure.com/dnceng/public/_build/results?buildId=600968)|PR https://github.com/dotnet/runtime/pull/34837|Restore and Build|
|[600968](https://dev.azure.com/dnceng/public/_build/results?buildId=600968)|PR https://github.com/dotnet/runtime/pull/34837|Restore and Build|
|[601002](https://dev.azure.com/dnceng/public/_build/results?buildId=601002)|PR https://github.com/dotnet/runtime/pull/34974|Restore and Build|
|[601002](https://dev.azure.com/dnceng/public/_build/results?buildId=601002)|PR https://github.com/dotnet/runtime/pull/34974|Restore and Build|
|[601002](https://dev.azure.com/dnceng/public/_build/results?buildId=601002)|PR https://github.com/dotnet/runtime/pull/34974|Restore and Build|
|[601002](https://dev.azure.com/dnceng/public/_build/results?buildId=601002)|PR https://github.com/dotnet/runtime/pull/34974|Restore and Build Product|
|[601038](https://dev.azure.com/dnceng/public/_build/results?buildId=601038)|PR https://github.com/dotnet/runtime/pull/34965|Restore and Build|
|[601038](https://dev.azure.com/dnceng/public/_build/results?buildId=601038)|PR https://github.com/dotnet/runtime/pull/34965|Restore and Build|
|[601038](https://dev.azure.com/dnceng/public/_build/results?buildId=601038)|PR https://github.com/dotnet/runtime/pull/34965|Restore and Build|
|[601501](https://dev.azure.com/dnceng/public/_build/results?buildId=601501)|PR https://github.com/dotnet/runtime/pull/34985|Restore and Build|
|[601501](https://dev.azure.com/dnceng/public/_build/results?buildId=601501)|PR https://github.com/dotnet/runtime/pull/34985|Restore and Build|
|[601501](https://dev.azure.com/dnceng/public/_build/results?buildId=601501)|PR https://github.com/dotnet/runtime/pull/34985|Restore and Build|
|[601483](https://dev.azure.com/dnceng/public/_build/results?buildId=601483)|PR https://github.com/dotnet/runtime/pull/34344|Restore and Build|
|[601483](https://dev.azure.com/dnceng/public/_build/results?buildId=601483)|PR https://github.com/dotnet/runtime/pull/34344|Restore and Build|
|[601483](https://dev.azure.com/dnceng/public/_build/results?buildId=601483)|PR https://github.com/dotnet/runtime/pull/34344|Restore and Build|
|[601483](https://dev.azure.com/dnceng/public/_build/results?buildId=601483)|PR https://github.com/dotnet/runtime/pull/34344|Restore and Build Product|
|[601541](https://dev.azure.com/dnceng/public/_build/results?buildId=601541)|PR https://github.com/dotnet/runtime/pull/34986|Restore and Build|
|[601541](https://dev.azure.com/dnceng/public/_build/results?buildId=601541)|PR https://github.com/dotnet/runtime/pull/34986|Restore and Build|
|[601541](https://dev.azure.com/dnceng/public/_build/results?buildId=601541)|PR https://github.com/dotnet/runtime/pull/34986|Restore and Build Product|
|[601241](https://dev.azure.com/dnceng/public/_build/results?buildId=601241)|PR https://github.com/dotnet/runtime/pull/34969|Restore and Build|
|[601241](https://dev.azure.com/dnceng/public/_build/results?buildId=601241)|PR https://github.com/dotnet/runtime/pull/34969|Restore and Build|
|[601241](https://dev.azure.com/dnceng/public/_build/results?buildId=601241)|PR https://github.com/dotnet/runtime/pull/34969|Restore and Build|
|[601362](https://dev.azure.com/dnceng/public/_build/results?buildId=601362)|PR https://github.com/dotnet/runtime/pull/34919|Restore and Build|
|[601362](https://dev.azure.com/dnceng/public/_build/results?buildId=601362)|PR https://github.com/dotnet/runtime/pull/34919|Restore and Build|
|[601362](https://dev.azure.com/dnceng/public/_build/results?buildId=601362)|PR https://github.com/dotnet/runtime/pull/34919|Restore and Build|
|[601400](https://dev.azure.com/dnceng/public/_build/results?buildId=601400)|PR https://github.com/dotnet/runtime/pull/34822|Restore and Build|
|[601400](https://dev.azure.com/dnceng/public/_build/results?buildId=601400)|PR https://github.com/dotnet/runtime/pull/34822|Restore and Build|
|[601400](https://dev.azure.com/dnceng/public/_build/results?buildId=601400)|PR https://github.com/dotnet/runtime/pull/34822|Restore and Build|
|[601326](https://dev.azure.com/dnceng/public/_build/results?buildId=601326)|PR https://github.com/dotnet/runtime/pull/34980|Restore and Build|
|[601326](https://dev.azure.com/dnceng/public/_build/results?buildId=601326)|PR https://github.com/dotnet/runtime/pull/34980|Restore and Build|
|[601326](https://dev.azure.com/dnceng/public/_build/results?buildId=601326)|PR https://github.com/dotnet/runtime/pull/34980|Restore and Build|
|[601326](https://dev.azure.com/dnceng/public/_build/results?buildId=601326)|PR https://github.com/dotnet/runtime/pull/34980|Restore and Build Product|
|[601276](https://dev.azure.com/dnceng/public/_build/results?buildId=601276)|Rolling|Restore and Build Product|
|[601276](https://dev.azure.com/dnceng/public/_build/results?buildId=601276)|Rolling|Restore and Build|
|[601276](https://dev.azure.com/dnceng/public/_build/results?buildId=601276)|Rolling|Restore and Build|
|[601276](https://dev.azure.com/dnceng/public/_build/results?buildId=601276)|Rolling|Restore and Build Product|
|[601276](https://dev.azure.com/dnceng/public/_build/results?buildId=601276)|Rolling|Restore and Build|
|[601051](https://dev.azure.com/dnceng/public/_build/results?buildId=601051)|PR https://github.com/dotnet/runtime/pull/34204|Restore and Build|
|[601051](https://dev.azure.com/dnceng/public/_build/results?buildId=601051)|PR https://github.com/dotnet/runtime/pull/34204|Restore and Build|
|[601051](https://dev.azure.com/dnceng/public/_build/results?buildId=601051)|PR https://github.com/dotnet/runtime/pull/34204|Restore and Build|
|[601051](https://dev.azure.com/dnceng/public/_build/results?buildId=601051)|PR https://github.com/dotnet/runtime/pull/34204|Restore and Build Product|
|[601180](https://dev.azure.com/dnceng/public/_build/results?buildId=601180)|PR https://github.com/dotnet/runtime/pull/34979|Restore and Build|
|[601180](https://dev.azure.com/dnceng/public/_build/results?buildId=601180)|PR https://github.com/dotnet/runtime/pull/34979|Restore and Build|
|[601180](https://dev.azure.com/dnceng/public/_build/results?buildId=601180)|PR https://github.com/dotnet/runtime/pull/34979|Restore and Build|
|[601180](https://dev.azure.com/dnceng/public/_build/results?buildId=601180)|PR https://github.com/dotnet/runtime/pull/34979|Restore and Build Product|
|[601118](https://dev.azure.com/dnceng/public/_build/results?buildId=601118)|PR https://github.com/dotnet/runtime/pull/34840|Restore and Build|
|[601118](https://dev.azure.com/dnceng/public/_build/results?buildId=601118)|PR https://github.com/dotnet/runtime/pull/34840|Restore and Build|
|[601118](https://dev.azure.com/dnceng/public/_build/results?buildId=601118)|PR https://github.com/dotnet/runtime/pull/34840|Restore and Build|
|[601118](https://dev.azure.com/dnceng/public/_build/results?buildId=601118)|PR https://github.com/dotnet/runtime/pull/34840|Restore and Build Product|
|[600804](https://dev.azure.com/dnceng/public/_build/results?buildId=600804)|PR https://github.com/dotnet/runtime/pull/34666|Restore and Build|
|[600804](https://dev.azure.com/dnceng/public/_build/results?buildId=600804)|PR https://github.com/dotnet/runtime/pull/34666|Restore and Build|
|[600804](https://dev.azure.com/dnceng/public/_build/results?buildId=600804)|PR https://github.com/dotnet/runtime/pull/34666|Restore and Build|
|[600923](https://dev.azure.com/dnceng/public/_build/results?buildId=600923)|PR https://github.com/dotnet/runtime/pull/34927|Restore and Build|
|[600923](https://dev.azure.com/dnceng/public/_build/results?buildId=600923)|PR https://github.com/dotnet/runtime/pull/34927|Restore and Build|
|[600923](https://dev.azure.com/dnceng/public/_build/results?buildId=600923)|PR https://github.com/dotnet/runtime/pull/34927|Restore and Build|
|[601159](https://dev.azure.com/dnceng/public/_build/results?buildId=601159)|PR https://github.com/dotnet/runtime/pull/34825|Restore and Build|
|[601159](https://dev.azure.com/dnceng/public/_build/results?buildId=601159)|PR https://github.com/dotnet/runtime/pull/34825|Restore and Build|
|[601159](https://dev.azure.com/dnceng/public/_build/results?buildId=601159)|PR https://github.com/dotnet/runtime/pull/34825|Restore and Build Product|
|[600844](https://dev.azure.com/dnceng/public/_build/results?buildId=600844)|PR https://github.com/dotnet/runtime/pull/34972|Restore and Build|
|[600844](https://dev.azure.com/dnceng/public/_build/results?buildId=600844)|PR https://github.com/dotnet/runtime/pull/34972|Restore and Build|
|[600844](https://dev.azure.com/dnceng/public/_build/results?buildId=600844)|PR https://github.com/dotnet/runtime/pull/34972|Restore and Build|
|[600844](https://dev.azure.com/dnceng/public/_build/results?buildId=600844)|PR https://github.com/dotnet/runtime/pull/34972|Restore and Build Product|
|[600971](https://dev.azure.com/dnceng/public/_build/results?buildId=600971)|PR https://github.com/dotnet/runtime/pull/34976|Restore and Build|
|[600971](https://dev.azure.com/dnceng/public/_build/results?buildId=600971)|PR https://github.com/dotnet/runtime/pull/34976|Restore and Build|
|[600971](https://dev.azure.com/dnceng/public/_build/results?buildId=600971)|PR https://github.com/dotnet/runtime/pull/34976|Restore and Build|
|[600954](https://dev.azure.com/dnceng/public/_build/results?buildId=600954)|PR https://github.com/dotnet/runtime/pull/34536|Restore and Build|
|[600954](https://dev.azure.com/dnceng/public/_build/results?buildId=600954)|PR https://github.com/dotnet/runtime/pull/34536|Restore and Build|
|[600954](https://dev.azure.com/dnceng/public/_build/results?buildId=600954)|PR https://github.com/dotnet/runtime/pull/34536|Restore and Build|
|[600962](https://dev.azure.com/dnceng/public/_build/results?buildId=600962)|PR https://github.com/dotnet/runtime/pull/34975|Restore and Build|
|[600962](https://dev.azure.com/dnceng/public/_build/results?buildId=600962)|PR https://github.com/dotnet/runtime/pull/34975|Restore and Build|
|[600962](https://dev.azure.com/dnceng/public/_build/results?buildId=600962)|PR https://github.com/dotnet/runtime/pull/34975|Restore and Build Product|
|[600876](https://dev.azure.com/dnceng/public/_build/results?buildId=600876)|PR https://github.com/dotnet/runtime/pull/34933|Restore and Build|
|[600876](https://dev.azure.com/dnceng/public/_build/results?buildId=600876)|PR https://github.com/dotnet/runtime/pull/34933|Restore and Build|
|[600876](https://dev.azure.com/dnceng/public/_build/results?buildId=600876)|PR https://github.com/dotnet/runtime/pull/34933|Restore and Build|
|[600747](https://dev.azure.com/dnceng/public/_build/results?buildId=600747)|PR https://github.com/dotnet/runtime/pull/34973|Restore and Build|
|[600747](https://dev.azure.com/dnceng/public/_build/results?buildId=600747)|PR https://github.com/dotnet/runtime/pull/34973|Restore and Build|
|[600747](https://dev.azure.com/dnceng/public/_build/results?buildId=600747)|PR https://github.com/dotnet/runtime/pull/34973|Restore and Build|
|[600747](https://dev.azure.com/dnceng/public/_build/results?buildId=600747)|PR https://github.com/dotnet/runtime/pull/34973|Restore and Build Product|
|[600700](https://dev.azure.com/dnceng/public/_build/results?buildId=600700)|PR https://github.com/dotnet/runtime/pull/32107|Restore and Build Product|

Evaluated 100 builds
Impacted 25 builds
Impacted 84 jobs

**Comment by jaredpar** [comment]
@ViktorHofer this looks related to the static graph work.

**Comment by ViktorHofer** [comment]
Is the stack trace always the same? If yes then cc @GrabYourPitchforks who renamed that project recently.

**Comment by jaredpar** [comment]
@ViktorHofer 

For the ones I looked at yes these are all the same. That remnids me though that @safern and @GrabYourPitchforks had a post merge conflict yesterday. Possible this is just an artifact of that.

**Comment by ViktorHofer** [comment]
That was my assumption as well. I'm fairly certain this was fixed with https://github.com/dotnet/runtime/commit/dd22ce809f235b40f20737b56458bacdb8ec2b46. Closing, feel free to reopen if this pops up again.

**Comment by safern** [comment]
Yeah that was closed with the commit @ViktorHofer pointed above. That was a fallout of the rename merged while my PR was open and had green builds and then when I merged it started failing.

**Comment by jaredpar** [comment]
Gotcha. Looks like our CI just hasn't caught up with that yet

**Comment by safern** [comment]
Yeah. Note that all the PRs that were open in the timeframe of when the error was discovered and the PR with the merge was merged, will see this symptom unless they update with a push or rebase so that their builds have the fix, so that might be the reason why it still shows on those PRs.
