### ISSUE TITLE
HTTP request to API with windows authentication in .NET 5

### ISSUE THREAD

**Issue by Devnsyde** [dotnet/runtime#35678]
Can someone give a .NET 5 example on how to make an HTTP request to a an API that requires windows authentication? I have tried several examples from both Microsoft and Stack Overflow (Method A):

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1
https://stackoverflow.com/questions/4015324/how-to-make-http-post-web-request

I keep getting an error that says: 
“The token supplied to the function is invalid”

Here is my code:
In Startup.cs
```c#
services.AddHttpClient("LogService", c =>
            {
                c.BaseAddress = new Uri(Configuration.GetSection("UrlSettings:LoggingServiceUrl").Value);
                c.DefaultRequestHeaders.Add("Accept", "text/json");
            }).ConfigurePrimaryHttpMessageHandler(() =>
                {
                    return new HttpClientHandler()
                    {
                        UseDefaultCredentials = true
                    };
            });
```
In controller
```c#
    public class LogsController : BaseController
    {
        private readonly IHttpClientFactory _clientFactory;
        public LogsController(IHttpClientFactory clientFactory)
        {
            _clientFactory = clientFactory;
        }

        [Route("GetLog")]
        public async Task<ActionResult> GetLog()
        {
               string numberOfRecords = _logSettings.NumberOfLogRecordsToRetrieve;
                string param = "/all/" + numberOfRecords;
                string result = "";
                var client = _clientFactory.CreateClient("LogService");
                var request = new HttpRequestMessage(HttpMethod.Get, param);
                var response = await client.SendAsync(request);

                if (response.IsSuccessStatusCode)
                {
                    result = await response.Content.ReadAsStringAsync();
                } 
         }
```

Some code removed for brevity.

**Comment by davidsh** [comment]
@Devnsyde 

>I keep getting an error that says:
“The token supplied to the function is invalid”

This error is interesting because it usually indicates a problem with the implementation of the API calls for Windows authentication. We don't see this error very often at all.

There are several components needed in order to repro this scenario:

* Client machine
* Middle-tier server running the ASP.NET Core applications
* Destination server (i.e. destination of the outgoing HttpClient API calls)

Is it possible to verify that a simpler scenario using Windows authentication works. Can you write a small console application using HttpClient and run it on the middle-tier server. The objective would be to have a console app that uses HttpClient and default credentials and can call the destination server. Doing this would be helpful in order to isolate what is going on here.

**Comment by karelz** [comment]
@Devnsyde will you be able to look at a repro we could use?

**Comment by Devnsyde** [comment]
Yea, sorry, I'll try to write a small app today.

**Comment by Devnsyde** [comment]
I wrote a very small console app in .net core 5 preview that is doing the same thing, and its calling a totally different web service with a sayhello method. This same method works from .net framework 4.7+ and also works with basic auth in .net core 5. I am not sure how to provide you with my environment but I could share the console app I just wrote if needed?

**Comment by davidsh** [comment]
>but I could share the console app I just wrote if needed?

Yes, please share the console app. You can create a ZIP file and attach it to this issue.

**Comment by Devnsyde** [comment]
Here ya go.

[WindowsAuthTestConsoleApp.zip](https://github.com/dotnet/runtime/files/4690840/WindowsAuthTestConsoleApp.zip)

**Comment by Devnsyde** [comment]
I should probably point out that I did not try this app from the server it is calling, I did try it from my laptop on the VPN running Windows 10 Pro version 10.0.18363 Build 18363 and on a virtual desktop hosted in the office running Windows 10 Enterprise 2016 LTSB version 10.0.14393 Build 14393. Both of these computers are calling a web service that is hosted on windows 2012 R2 server version 6.2 (Build 9200) using IIS version 8.5.9600.16384 The web service uses the following authentication schemes: Anonymous, Basic, and Windows only.

**Comment by mconnew** [comment]
I just ran into this problem for WCF Core Client. We have 2 test scenarios which work on .NET Core 3.1, but are failing on .NET 5. I've ran both failing scenarios against a WCF self hosted server as well as an IIS hosted server so I believe this is NOT a server side issue as this is using server side implementations which have been around for years. The same client code works on .NET Core 3.1 (and earlier) but fails on .NET 5 so this is a regression.
  
**Scenario 1**
Server configured to use Windows authentication with only the NTLM protocol enabled. HttpClient is using ambient credentials (so CredentialsCache,DefaultCredentials).  

**Scenario 2**
Server configured to use Windows authentication with only the Negotiate protocol enabled. HttpClient is using ambient credentials (CredentialsCache,DefaultCredentials).  

I'm not quite sure exactly which version we're running on. We specify .NET SDK version 5.0.100-preview.8.20362.3 but that apparently comes bundled with runtime version 5.0.0-preview.8.20361.2. The runtimeconfig.json file for the test says 5.0.0-preview.8.20361.2 so I would presume that's the version we're running the tests with.

In both cases the failing call stack is the same. I'm only including the relevant HttpClient call stack here:
```c#
System.ComponentModel.Win32Exception : The token supplied to the function is invalid
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
   at System.Net.NTAuthentication.GetOutgoingBlob(String incomingBlob)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsync(ValueTask`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts, Boolean buffered, Boolean async, CancellationToken callerToken, Int64 timeoutTime)
```

If you want instructions how to replicate the problem with the WCF repo, let me know. My intention is to add more data and to show this is a regression in .NET 5 and not a client usage or environment issue.

**Comment by wfurt** [comment]
This looks like dup of #39011. (fixed very recently with #40222)
Could you please check with daily builds @mconnew?

**Comment by karelz** [comment]
@wfurt if you suspect even the original report as a dupe, we should mark it so and wait for confirmation.

**Comment by mconnew** [comment]
@wfurt, yes this is fixed with the latest daily build.

**Comment by karelz** [comment]
Duplicate of #39011

**Comment by wfurt** [comment]
Thanks for confirmation @mconnew. Can you please try it as well @Devnsyde? I read through the issues and it may be same problem. I'm inclined to close this unless we can prove it otherwise. I'm trying to figure out plan to get some automated test coverage as current test suite is not capable of covering this.

**Comment by wfurt** [comment]
it seems like @karelz beat me by minute. confirmation would be still good @Devnsyde

**Comment by Devnsyde** [comment]
Hey guys,

Using the console app that I attached above I am still getting the same error.

`
fail: WindowsAuthTestConsoleApp.App[0]
      Test failed with message: The token supplied to the function is invalid
`

I am using version 5.0.0-preview.7.20364.11

**Comment by wfurt** [comment]
That is too old @Devnsyde. I don't think the fix is in any preview yet. Can you grab build from https://github.com/dotnet/installer and give it another try?

**Comment by Devnsyde** [comment]
@wfurt I installed the runtime version 5.0.100-rc.1.20413.9 that you linked above, not sure if that is what you were wanting me to try? I am getting an error now with my test solution that I'll need to work through as the error only says "Warning level must be in the range 0-4". I'll write back one I can get a good test going again.

**Comment by Devnsyde** [comment]
I looked at the error and it takes me to a document written in 2015, I don't really have the time to work through more bugs so I re-downloaded the preview version of the .net 5 sdk from https://dotnet.microsoft.com/download/dotnet/5.0 and after a closer look it looks like this version is a higher version anyway so maybe I downloaded something super old.

The version I had downloaded/installed from the github link was: dotnet-sdk-5.0.100-rc.1.20413.9
I rolled back(or forward?) to: dotnet-sdk-5.0.100-preview.7.20366.6
Now my test app is working again just still getting the token error as expected.

Maybe you can tell me which sdk version to install?

**Comment by wfurt** [comment]
It seems like some regression slipped to the sdk. if building from command line you can do `dotnet build  /p:analysisLevel=0` or add `<AnalysisLevel>0</AnalysisLevel>` to your project file. It seems like the fix is available but it will take some time to roll into builds.

**Comment by Devnsyde** [comment]
Okay added `AnalysisLevel>0</AnalysisLevel>` to the `<PropertyGroup></PropertyGroup>` of my project file worked.
I ran my test app and it worked as well. Getting a 200 back.

**Comment by wfurt** [comment]
thanks for confirmation @Devnsyde. All the fixes should be in next preview build.
