### ISSUE TITLE
System.Runtime.Extensions.Tests fails on iOS and tvOS

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#36896]
System.Runtime.Extensions.Tests
System.Tests.AppDomainTests.TestingCreateInstanceFromObjectHandle - in PR
System.Tests.EnvironmentTests.GetFolderPath_Unix_PersonalIsHomeAndUserProfile - MacCatalyst only
System.Tests.EnvironmentUserName.UserName_Valid

```
System.Runtime.Extensions.Tests.dll   Failed: 21

Test collection for System.Tests.AppDomainTests
System.Tests.AppDomainTests.TestingCreateInstanceFromObjectHandle(physicalFileName: \"AssemblyResolveTestApp.dll\", assemblyFile: \"assemblyresolvetestapp.dll\", type: \"assemblyresolvetestapp.publicclasssample\", returnedFullNameType: \"AssemblyResolveTestApp.PublicClassSample\", exceptionType: typeof(System.IO.FileNotFoundException))
    Assert.Throws() Failure\nExpected: typeof(System.IO.FileNotFoundException)\nActual:   typeof(System.TypeLoadException): Could not load type 'assemblyresolvetestapp.publicclasssample' from assembly 'AssemblyResolveTestApp, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.\n---- System.TypeLoadException : Could not load type 'assemblyresolvetestapp.publicclasssample' from assembly 'AssemblyResolveTestApp, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
       at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Activator.CreateInstanceFrom(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstanceFrom(String assemblyFile, String typeName)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)
   at System.Tests.AppDomainTests.<>c__DisplayClass57_0.<TestingCreateInstanceFromObjectHandle>b__0()
----- Inner Stack Trace -----
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Activator.CreateInstanceFrom(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstanceFrom(String assemblyFile, String typeName)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)
   at System.Tests.AppDomainTests.<>c__DisplayClass57_0.<TestingCreateInstanceFromObjectHandle>b__0()
System.Tests.AppDomainTests.TestingCreateInstanceFromObjectHandle(physicalFileName: \"AssemblyResolveTestApp.dll\", assemblyFile: \"assemblyresolvetestapp.dll\", type: \"assemblyresolvetestapp.privateclasssample\", returnedFullNameType: \"AssemblyResolveTestApp.PrivateClassSample\", exceptionType: typeof(System.IO.FileNotFoundException))
    Assert.Throws() Failure\nExpected: typeof(System.IO.FileNotFoundException)\nActual:   typeof(System.TypeLoadException): Could not load type 'assemblyresolvetestapp.privateclasssample' from assembly 'AssemblyResolveTestApp, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.\n---- System.TypeLoadException : Could not load type 'assemblyresolvetestapp.privateclasssample' from assembly 'AssemblyResolveTestApp, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
       at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Activator.CreateInstanceFrom(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstanceFrom(String assemblyFile, String typeName)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)
   at System.Tests.AppDomainTests.<>c__DisplayClass57_0.<TestingCreateInstanceFromObjectHandle>b__0()
----- Inner Stack Trace -----
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Activator.CreateInstanceFrom(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstanceFrom(String assemblyFile, String typeName)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)
   at System.Tests.AppDomainTests.<>c__DisplayClass57_0.<TestingCreateInstanceFromObjectHandle>b__0()
System.Tests.AppDomainTests.TestingCreateInstanceFromObjectHandle(physicalFileName: \"AssemblyResolveTestApp.dll\", assemblyFile: \"assemblyresolvetestapp.dll\", type: \"assemblyresolvetestapp.publicclassnodefaultconstru\"..., returnedFullNameType: \"AssemblyResolveTestApp.PublicClassNoDefaultConstru\"..., exceptionType: typeof(System.IO.FileNotFoundException))
    Assert.Throws() Failure\nExpected: typeof(System.IO.FileNotFoundException)\nActual:   typeof(System.TypeLoadException): Could not load type 'assemblyresolvetestapp.publicclassnodefaultconstructorsample' from assembly 'AssemblyResolveTestApp, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.\n---- System.TypeLoadException : Could not load type 'assemblyresolvetestapp.publicclassnodefaultconstructorsample' from assembly 'AssemblyResolveTestApp, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
       at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Activator.CreateInstanceFrom(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstanceFrom(String assemblyFile, String typeName)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)
   at System.Tests.AppDomainTests.<>c__DisplayClass57_0.<TestingCreateInstanceFromObjectHandle>b__0()
----- Inner Stack Trace -----
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Activator.CreateInstanceFrom(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstanceFrom(String assemblyFile, String typeName)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)
   at System.Tests.AppDomainTests.<>c__DisplayClass57_0.<TestingCreateInstanceFromObjectHandle>b__0()

Test collection for System.Tests.EnvironmentTests
System.Tests.EnvironmentTests.GetFolderPath_Unix_PersonalIsHomeAndUserProfile
    Assert.Equal() Failure\n                        ↓ (pos 14)\nExpected: /Users/mdhwang\nActual:   /Users/mdhwang/Documents\n                        ↑ (pos 14)
       at System.Tests.EnvironmentTests.GetFolderPath_Unix_PersonalIsHomeAndUserProfile()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)


Test collection for System.Tests.EnvironmentUserName
System.Tests.EnvironmentUserName.UserName_Valid
    Assert.False() Failure\nExpected: False\nActual:   True
       at System.Tests.EnvironmentUserName.UserName_Valid()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by filipnavara** [comment]
System.Tests.EnvironmentTests.OSVersion_ParseVersion should be excluded (just as on macOS), it uses private reflection on API that doesn't exist

System.Tests.Environment_Exit.ExitCode_VoidMainAppReturnsSetValue should be excluded on iOS, tvOS (and possibly Mac Catalyst) because external processes cannot be launched

GetFolderPath_Unix_PersonalIsHomeAndUserProfile is not valid for iOS, tvOS

System.Tests.AppDomainTests are likely fixed by updated AppleAppBuilder now

**Comment by steveisok** [comment]
@mdh1418 The AppDomainTests can be re-enabled as they should work.

**Comment by mdh1418** [comment]
`System.Tests.AppDomainTests.TestingCreateInstanceFromObjectHandle` Still fails on MacCatalyst, but `System.Tests.AppDomainTests.TestingCreateInstanceFromObjectHandleFullSignature` passes on all iOS, tvOS, MacCatalyst now. The other tests still fail and stand as is.

**Comment by mdh1418** [comment]
Both `System.Tests.EnvironmentUserName.UserName_Valid` and `System.Tests.EnvironmentTests.GetFolderPath_Unix_PersonalIsHomeAndUserProfile` are failing on iOS and tvOS due to the values `Environment.UserName` being `string.Empty` and `Environment.GetEnvironmentVariable("HOME")` being null.

On MacCatalyst, the values are not empty or null.
