### ISSUE TITLE
🔥🔥🔥 "Libraries Test Run checked coreclr Linux" timing out on all PRs

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#45061]
Examples: #44688, #44945, ...

**Comment by ViktorHofer** [comment]
@safern can you please take a look at that one?

**Comment by ViktorHofer** [comment]
Still happening in PRs, i.e. https://github.com/dotnet/runtime/pull/45108.

**Comment by ericstj** [comment]
cc @aik-jahoda 
Does anyone know if this is related to a code change, or do we think this is due to infrastructure (EG: reduced agents in machine pools?)

**Comment by wfurt** [comment]
I was searching throug Kusto and I don't see even console link. SO this may be infrastructure. All the cases I look at are containers.

**Comment by SteveCarrollMSFT** [comment]
@jkotas let me know about this and i'm catching up.
My amateur sleuthing suggests this is not likely a repo level issue.
has this been reported to First Responders?   please cc me on this one.

**Comment by safern** [comment]
> @safern can you please take a look at that one?

Just catching up on this. I can help to look at data and follow up with FR if there is no thread already.

**Comment by stephentoub** [comment]
> has this been reported to First Responders? please cc me on this one.

It was here:
https://github.com/dotnet/runtime/pull/44980#issuecomment-731852288

**Comment by safern** [comment]
Thanks @stephentoub. I'm taking over to drive closure on this one.

**Comment by safern** [comment]
I just looked at data for some jobs that were linked here, and it looks like that queue was either clogged or had a hicup. The workitems are running fine, taking less than 1 minute one they get a machine, but it looks like the average waiting time on the queue was 11 hours 😮

**Comment by safern** [comment]
The core-eng issues are: https://github.com/dotnet/core-eng/issues/11485 and https://github.com/dotnet/core-eng/issues/11468. @dotnet/dnceng says it is fixed.

I'm going to leave this open to see if we get more instances of this before EOD, if not I will close it.

**Comment by jkotas** [comment]
Still happening: #45137

**Comment by safern** [comment]
Ok, I was just about to close this as the data suggested it didn't happen but I found out that the jobs where it happened are not showing on kusto, so I looked into swagger and that example just posted, shows all workitems as "waiting". 

I pinged the FR thread and the issue on:  https://github.com/dotnet/core-eng/issues/11468#issuecomment-732715076

Thanks, for reporting the new instance!

**Comment by safern** [comment]
Update: the queue should be back at capacity. We're killing all jobs that started more than 2 hours ago to ease the queue.

Current issue to investigate why machines are suddenly going offline is here: https://github.com/dotnet/core-eng/issues/11503

**Comment by tarekgh** [comment]
Still happening in https://github.com/dotnet/runtime/pull/45079

**Comment by safern** [comment]
I haven't seen this anymore. I looked at the queue health and it is pretty healthy with average wait times of 15 mins since yesterday. Please re-open if you do see this happen again.
