### ISSUE TITLE
C# 9 covariant return types: Still can get System.TypeLoadException when using generics

### ISSUE THREAD

**Issue by ASolomatin** [dotnet/runtime#45344]
# Description
This looks like https://github.com/dotnet/core/issues/5319 but with generics.

The C # 9.0 overridden virtual function works fine when the return type is a covariant derived type, continues to work if the return type is a covariant derived type that contains the overridden function. But System.TypeLoadException is thrown at runtime if you add some generics. As before, everything builds without errors and warnings.

# Code to reproduce
```csharp
using System;

var c = new AChild();

Console.WriteLine("Hello World!");

public abstract class A<T>
{
    public abstract B<T> GetB();
}

public class AChild : A<string>
{
    public override BChild GetB() => null;
}

public class B<T>
{
}

public class BChild : B<string>
{
}
```

# Error:
```bash
$ dotnet run
Unhandled exception. System.TypeLoadException: Return type in method 'AChild.GetB()' on type 'AChild' from assembly 'N5, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' is not compatible with base type method 'A`1[System.__Canon].GetB()'.
$ dotnet --version
5.0.100
```
### Versions
5.0.100-rc.2.20479.15
5.0.100

_Originally posted by @ASolomatin in https://github.com/dotnet/core/issues/5319#issuecomment-722769903_

**Comment by MichalStrehovsky** [comment]
Sounds like #45037 

Cc @janvorli

**Comment by janvorli** [comment]
I've verified this issue is fixed by #45275, it is a dup of #45037

**Comment by adamjones1** [comment]
Hi, in the meantime before this fix is released, I am trying to continue developing my app on machines with 5.0.101 installed (I didn't experience the error on 5.0.100 for some reason, it only appeared when 5.0.101 was installed). Is there any way to force usage of 5.0.100 for running it with a global.json? When I attempt this, `dotnet --version` gives me 5.0.100 but when the app actually launches unit tests with `dotnet test` it still gives me the error as if it were ignoring the global.json.

**Comment by janvorli** [comment]
Would setting the runtime version property in the csproj file to 5.0.100 work as a workaround? 
```
<RuntimeFrameworkVersion>5.0.100</RuntimeFrameworkVersion>
```

**Comment by adamjones1** [comment]
Trying this I get _"Unable to find package Microsoft.NETCore.App.Host.win-x64 with version (= 5.0.100)"_ (seems only 5.0.1 exists at https://www.nuget.org/packages/Microsoft.NETCore.App.Host.win-x64/?). Using 5.0.1 instead the issue is still present I assume as this still instructs it to use the latest patch version.

**Comment by janvorli** [comment]
I am sorry for the confusion, I meant 5.0.0.

**Comment by adamjones1** [comment]
Ah ok, using 5.0.0 unfortunately the TypeLoadException is still present. My full csproj is:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RuntimeFrameworkVersion>5.0.0</RuntimeFrameworkVersion>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\src\MyProject\MyProject.csproj" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
```

**Comment by ASolomatin** [comment]
Still can reproduce with small code modifications:
```csharp
using System;

var c = new AChild<string>();

Console.WriteLine("Hello World!");

public abstract class A<T>
{
    public abstract B<T> GetB();
}

public class AChild<T> : A<T>
{
    public override BChild<T> GetB() => null;
}

public class B<T>
{
}

public class BChild<T> : B<T>
{
}
```

**Comment by janvorli** [comment]
@ASolomatin what version of runtime have you reproed it with? The latest fix is not in any released .NET 5 versions, it will be part of 5.0.2.

**Comment by ASolomatin** [comment]
Sorry. )  I thought, it's already released because the original issue stops to reproduce on 5.0.1

**Comment by janvorli** [comment]
@ASolomatin I'll verify it with the latest version to make sure this is not yet another problem.

**Comment by janvorli** [comment]
I can confirm that your test above passes with runtime from the master branch, which means that it should pass with the 5.0.2 once it is out.

**Comment by Unknown6656** [comment]
@janvorli I have the same bug with 5.0.2
Although I have to admit that my classes are more complex than @ASolomatin's. I'll try to post a MWE as soon as possible.

**Comment by ASolomatin** [comment]
Just one next code modification to reproduce on 5.0.2 somesing look likes the same:

```csharp
using System;

var c = new AChild<string>();

Console.WriteLine("Hello World!");

public abstract class A<T1, T2>
{
    public abstract B<T1, T2> GetB();
}

public class AChild<T> : A<T, string>
{
    public override BChild<T> GetB() => null;
}

public class B<T1, T2>
{
}

public class BChild<T> : B<T, string>
{
}
```

```bash
alex@nout-1:~/Projects/DummyTests/N5$ dotnet --version
5.0.102
alex@nout-1:~/Projects/DummyTests/N5$ dotnet run
Unhandled exception. System.TypeLoadException: Return type in method 'AChild`1[T].GetB()' on type 'AChild`1[T]' from assembly 'N5, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' is not compatible with base type method 'A`2[T,System.__Canon].GetB()'.
```

**Comment by janvorli** [comment]
@ASolomatin thank you for the repro. I have tested it with my pending fix for the #47007 and the issue is gone with that fix.
