### ISSUE TITLE
HttpClient derived from IHttpClientFactory is throwing System.Threading.Tasks.TaskCanceledException: A task was canceled

### ISSUE THREAD

**Issue by alcatraz007** [dotnet/runtime#46741]
We are trying to do load test setting LevelOfParallelism as 16 using NUnit framework.
We are getting System.Threading.Tasks.TaskCanceledException after 15 mins of test.

We are using : .net core 3.0

We are using below code to initialize the HttpClient under startup class.

services.AddHttpClient("namedclient");

We are using bellow method to post the data:

```c#
private async Task<string> PostData(IHttpClientFactory _clientFactory, string data, string url)
        {
            string returnMessage = string.Empty;
            var _httpClient = _clientFactory.CreateClient("namedclient");

            using (StringContent content = new StringContent(data, Encoding.UTF8, "application/x-www-form-urlencoded"))
            {
                var result = await _httpClient.PostAsync(url, content);
                result.EnsureSuccessStatusCode();
                returnMessage = await result.Content.ReadAsStringAsync();
            }
            return returnMessage;
        }
```

The code does not give any error upto 4 LevelOfParallelism. After increasing the number, method has started throwing  TaskCanceledException.
Even if we use general HttpClient (not derived from IHttpClientFactory), the memory usage of the server becomes very high comparative to IHttpClientFactory but surprisingly TaskCanceledException goes away.

We are happy to provide more information if needed.
Any help would be appreciated!
Thanks in advance!

**Comment by ManickaP** [comment]
@alcatraz007 How soon after the `PostAsync` does the exception happen? Could you be hitting timeouts (they propagate as `TaskCancelledException` out of `HttpClient`)?

> Even if we use general HttpClient (not derived from IHttpClientFactory), the memory usage of the server becomes very high comparative to IHttpClientFactory but surprisingly TaskCanceledException goes away.

Could you post you repro code with `HttpClient` that causes the memory consumption? Aren't you by any chance disposing/discarding the client after each request (that's a big no-no)?

**Comment by alcatraz007** [comment]
PostAsync throws exception after 1 min 40 sec. The same payload if we send through postman, we get the result in 15 seconds.

Earlier we were using as you have pointed out. That's why we have refactored to IHttpClientFactory. Now memory consumption has gone down drastically but ended up with task cancelled exception.

Please find the older code block:
`               using (HttpClient client = new HttpClient())
                {
                    StringContent content = new StringContent(message, Encoding.UTF8, "application/x-www-form-urlencoded");
                    var result = client.PostAsync(sendUrl, content).Result;
                    string response = result.Content.ReadAsStringAsync().Result;
                    returnMessage = response;                    
                }`

**Comment by ManickaP** [comment]
> PostAsync throws exception after 1 min 40 sec. 

You're hitting a **timeout**: [The default value is 100,000 milliseconds (100 seconds).](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout?view=net-5.0#remarks)

Are the requests going out to you server? Is your server handling the requests and replying in timely manner?
You could capture the exchange with wireshark to see what's going on. Or you could try to debug into the `HttpClient` and see where it gets stuck.

Add your sample:
```
using (HttpClient client = new HttpClient())
{
...
    var result = client.PostAsync(sendUrl, content).Result;
...
}
```
First of all, you **shouldn't dispose `HttpClient` with each request**, keep the instance around in some static field and reuse it. Second of all, why are you calling `.Result` on the task instead of awaiting? And lastly, you can probably use [`FormUrlEncodedContent`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.formurlencodedcontent?view=net-5.0) instead of `StringConetnt`.

**Comment by Brijwizards** [comment]
@ManickaP  - Call is happening within the server. Our .Net core API calls the WCF REST service hosted on the same server. WCF REST service  is returning **this**(transient exception says 'A task was canceled'). However this service interacts with external services . When we run the test with 4 NUnit.Framework LevelOfParallelism we are not hitting this issue. We are observing this when we increase the limit to 8, 12 or 16 and so on.  

We updated the code and using **returnMessage = await result.Content.ReadAsStringAsync();   ** and reading the string in a separate method call like this.
response.Wait();
var returnMessage = response.Result;

**IIS info:
.Net core service and WCF Rest service both are on the same Azure VM under the different App pool.**

**System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request.. ---> System.Net.Sockets.SocketException: The I/O operation has been aborted because of either a thread exit or an application request.

   --- End of inner exception stack trace ---

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)

   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)

   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)

   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)

   --- End of inner exception stack trace ---

   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)

   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)**

**Test Result:**
Automation HTTP Client instance/LevelOfParallelism  | 12
Total Mins | 25
**Connection/port Opened | 208**
**Task Cancel Failed | 27** 
Total Test Cases Kicked off | 1000

Automation HTTP Client instance/LevelOfParallelism | 1
Total Mins | 50
**Connection/port Opened | 134**
**Task Cancel Failed | 0**
Total Test Cases Kicked off | 1000

When we run the same set of test cases with old code which has standard http client implementation we don't see this issue however we see memory leak happening there. And that the reason we implemented the IHttpClientFactory  and now we are seeing Task Cancel  issue however memory leak issue seems to be resolved.

**Comment by ManickaP** [comment]
> PostAsync throws exception after 1 min 40 sec.

Based on the 100 seconds to the exception, **you're definitely hitting timeouts**.

> WCF REST service is returning this(transient exception says 'A task was canceled').

I still don't understand what your server does or whether it even behaves correctly. Are you saying it's throwing exception as well?

Try to isolate the problem first. Is it happening if you run the load outside of unit tests? What if you exclude the external service and just return 200 from your REST endpoint?

In the meantime, I was just able to run 10 000 parallel `PostAsync` between `HttpClient` and kestrel locally in less than 10 seconds without any issues.

<details>

Client:
```C#
class Program
{
    private static readonly HttpClient _client = new HttpClient();

    static async Task Main()
    {
        Stopwatch sw = Stopwatch.StartNew();
        var tasks = new Task<HttpResponseMessage>[10_000];
        for (int i = 0; i < tasks.Length; ++i)
        {
            tasks[i] = _client.PostAsync("http://localhost:5001/postFormUrlEncodedContent",
                new StringContent("field1=value1&field2=value2", Encoding.UTF8,
                    "application/x-www-form-urlencoded"));
        }

        await Task.WhenAll(tasks);
        for (int i = 0; i < tasks.Length; ++i)
        {
            using var response = await tasks[i];
            var responseContent = await response.Content.ReadAsStringAsync();
            Console.WriteLine(responseContent);
        }

        Console.WriteLine(sw.Elapsed);
    }
}
```

Kestrel endpoint definition:
```C#
app.UseEndpoints(endpoints =>
{
    endpoints.MapPost("/postFormUrlEncodedContent", async context =>
    {
        using var streamReader = new StreamReader(context.Request.Body, Encoding.UTF8);
        var requestContent = await streamReader.ReadToEndAsync();
        await context.Response.WriteAsync(requestContent + requestContent, Encoding.UTF8);
    });
}
```
</details>

**Comment by Brijwizards** [comment]
@ManickaP - Rest service developed in .Net core is a front end service talks to the WCF Rest backend service at least twice(2 PostAsync , in some cases it is 3) to fulfill one transaction initiated from front end service. Behind the scene Back end service interacts with external service. Our front end service works fine(returns 200 OK) but is is the backend service whose sends this response
System.Threading.Tasks.TaskCanceledException: The operation was canceled. ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request.. ---> System.Net.Sockets.SocketException: The I/O operation has been aborted because of either a thread exit or an application request.

When i run same set of test cases e..g 100 parallel PostAsync with **HttpClient** based PostAsync  call, back end service response is perfectly fine, Total Elapsed Time:00:01:13.70560 to serve 100 parallel PostAsync

When i run same set of test cases e..g 100 parallel PostAsync with    **IHttpClientFactory** based PostAsync  call, back end service responds with TaskCanceledException. When i lower down parallel PostAsync e.g. to 1 or 10,  backend service works fine.

Here is what we have tried so far.
1. Polly option to retry
2. Lowering down MaxConnectionsPerServer 
3. Setting SocketsHttpHandler to false
.AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);
4. Added Task.Wait() before reading the task result

**Startup.cs:**
           services.AddHttpClient("namedclient")
            .ConfigurePrimaryHttpMessageHandler(() =>
             {
                 return new HttpClientHandler { MaxConnectionsPerServer = 1100 };
             });

// Commented code.
            //     var retryPolicy = HttpPolicyExtensions
            //    .HandleTransientHttpError()
            //    .RetryAsync(3);
            //     var noOp = Policy.NoOpAsync().AsAsyncPolicy<HttpResponseMessage>();
            //     services.AddHttpClient("namedclient", c=> { })
            //         .SetHandlerLifetime(Timeout.InfiniteTimeSpan)
            //         .AddPolicyHandler(request => request.Method == HttpMethod.Post ? retryPolicy : noOp);

We migrated to IHttpClientFactory implementation from HttpClient to avoid the socket exception/memory leak which started to happen on the servers during holiday season.  We followed this for IHttpClientFactory 

https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests

**Comment by karelz** [comment]
Not enough info to make this actionable - no isolated repro, looks like end-to-end scenario problem with multiple servers chained. Closing.

From the above, I would recommend to track what is happening with the requests and which one times out and why - is it due to external server responsiveness perhaps?
Basic perf investigation should be able to move things forward. Or analyze network traffic to the external server to confirm where the timeout comes from - from the external server, or from your code.

Note that `HttpClient` should not be allocated per request (unless you are using `HttpClientFactory`). If you migrated to the Factory, things should be simpler for you in ASP.NET code than maintaining `HttpClient` singletons elsewhere.
Also note that both `.Wait` and `.Result` will block threads, potentially leading to thread exhaustion. It may very well be behind the timeouts. It is anti-pattern you should avoid on apps that need to scale.

**Comment by Brijwizards** [comment]
@karelz @ManickaP  - Thanks. We did further investigation and found that backend service is the one which is cancelling the parallel threads if operation lasts for more than 100 seconds. We increased **HttpRuntime** execution time  under system.web & observed slightly  better result but again it is dependent on 100 seconds operation time out limit. We will not see any better result until we increase the operation time out limit of our backend service if there is any possibility to achieve that. So at this point we are sure that this issue is not related to HttpClientFactory implementation.

Thanks again for support on this.
