### ISSUE TITLE
ILogger<T> was implemented in such a way that it isn't being cached (for the same type) unlike non generic version

### ISSUE THREAD

**Issue by LirazShay** [dotnet/runtime#48473]
When using `ILogger<T>` in class dependency, and creating multiple instances of the same type, a new  `ILogger<T>` instance is created for each instance instead of logger being cached and reused like in non generic ILogger

### To Reproduce
This unit test can explain the issue:    
```c#
//loggerFactory is of type LoggerFactory
var loggerFactory = container.Resolve<ILoggerFactory>();

//Non generic ILogger is being cached
var logger1 = loggerFactory.CreateLogger(typeof(MyClass).FullName);
var logger2 = loggerFactory.CreateLogger(typeof(MyClass).FullName);

Assert.AreEqual(logger1, logger2);

//Non generic ILogger is being cached when called from extension method
logger1 = loggerFactory.CreateLogger(typeof(MyClass));
logger2 = loggerFactory.CreateLogger(typeof(MyClass));

Assert.AreEqual(logger1, logger2);

//BUT - here is the problem
var genericLog1 = loggerFactory.CreateLogger<MyClass>();
var genericLog2 = loggerFactory.CreateLogger<MyClass>();
//This assert is failing...
Assert.AreEqual(genericLog1, genericLog2);
```

### Expected behavior
When calling loggerFactory.CreateLogger<T>() multiple times with the same type - it should use the same ILogger<T> instance
Exactly like how it is working in CreateLogger(type) or CreateLogger(string)

### Additional context
From the source code of LoggerFactoryExtensions, it seems that the problem is that when calling CreateLogger<T>(this ILoggerFactory factory) - it always created new instance -
```c#
/// <summary>
/// ILoggerFactory extension methods for common scenarios.
/// </summary>
public static class LoggerFactoryExtensions
{
    /// <summary>
    /// Creates a new <see cref="ILogger"/> instance using the full name of the given type.
    /// </summary>
    /// <param name="factory">The factory.</param>
    /// <typeparam name="T">The type.</typeparam>
    /// <returns>The <see cref="ILogger"/> that was created.</returns>
    public static ILogger<T> CreateLogger<T>(this ILoggerFactory factory)
    {
        if (factory == null)
        {
            throw new ArgumentNullException(nameof(factory));
        }
        return new Logger<T>(factory);
    }
```

Unlike in the other method CreateLogger(type) that it redirect the responsibility to the factory 
and the factory is caching all created logger
```c#
/// <summary>
/// Creates a new <see cref="ILogger"/> instance using the full name of the given <paramref name="type"/>.
/// </summary>
/// <param name="factory">The factory.</param>
/// <param name="type">The type.</param>
/// <return>The <see cref="ILogger"/> that was created.</return>
public static ILogger CreateLogger(this ILoggerFactory factory, Type type)
{
    if (factory == null)
    {
        throw new ArgumentNullException(nameof(factory));
    }

    if (type == null)
    {
        throw new ArgumentNullException(nameof(type));
    }

    return factory.CreateLogger(TypeNameHelper.GetTypeDisplayName(type, includeGenericParameters: false, nestedTypeDelimiter: '.'));
}
```

Code from LoggerFactory:
```c#
 public ILogger CreateLogger(string categoryName)
{
    if (CheckDisposed())
    {
        throw new ObjectDisposedException(nameof(LoggerFactory));
    }

    lock (_sync)
    {
        if (!_loggers.TryGetValue(categoryName, out var logger))
        {
            logger = new Logger(this)
            {
                Loggers = CreateLoggers(categoryName)
            };
            _loggers[categoryName] = logger;
        }

        return logger;
    }
}
```

**Comment by TheMaximum** [comment]
Hi! I'm new to developing in the runtime and thought this might be an interesting issue to start.
Turns out it's harder than expected and I've hit a bit of a snag.

---

I've added the relevant unittests here: https://github.com/TheMaximum/runtime/commit/dc432462824cd0236426437f22bf84df877d0cec. As expected, the ``LoggerFactoryCreateOfT`` tests fail - as a new instance of ``Logger{T}`` is returned.

However, while the instance of ``Logger{T}`` returned by the second ``CreateLogger{T}()`` call is different, the methods ``Logger{T}`` provide only call an instance of ``ILogger``, which in turn has been set using ``ILoggerFactory.CreateLogger(string)`` and thus is the same every time (if the ``ILoggerFactory`` implementation does that like ``LoggerFactory``).

I wonder what the idea behind ``ILogger{T}`` and ``Logger{T}`` are, as the only time (at least as far as I can see) the typed argument is used, is when calling ``ILoggerFactory.CreateLogger(string)`` with the name of the typed argument.

You could make the ``LoggerFactoryExtensions.CreateLogger{T}`` method return a normal ``ILogger`` instance. Or if the generic typed ``ILogger``/``Logger`` is required, the ``ILoggerFactory``/``LoggerFactory`` will need a new method that returns cached ``ILogger{T}`` instances - at least that's the possible solution I can see.

Would you be able to provide some extra insight into this, @maryamariyan ?

**Comment by KalleOlaviNiemitalo** [comment]
> I wonder what the idea behind `ILogger{T}` and `Logger{T}` is

An application can define class MyService with a constructor that has an `ILogger<MyService>` parameter. If Microsoft.Extensions.DependencyInjection then creates an instance of MyService, it also creates a `Logger<MyService>` for the parameter. So when the MyService instance writes entries to this logger, each entry gets "MyService" as the log category, even though MyService never explicitly called CreateLogger.

**Comment by KalleOlaviNiemitalo** [comment]
LoggingServiceCollectionExtensions.AddLogging registers `ILogger<>` as a singleton: <https://github.com/dotnet/runtime/blob/c636bbdc8a2d393d07c0e9407a4f8923ba1a21cb/src/libraries/Microsoft.Extensions.Logging/src/LoggingServiceCollectionExtensions.cs#L42>

So if the application lets the dependency container resolve `ILogger<MyService>`, then the resulting `Logger<MyService>` should be cached by the container. I'm not convinced it makes sense to add another layer of caching in the `CreateLogger<T>` method.

**Comment by TheMaximum** [comment]
Thanks for the insights, @KalleOlaviNiemitalo! As mentioned: the ``Logger{T}`` methods basically just call their corresponding methods on ``ILogger``, which is already cached by the factory. As such, the parts that actually execute stuff are already re-used in every ``Logger{T}`` instance.

Question might indeed be whether the typed variant would need to be cached, or if caching the underlaying instance is enough?

**Comment by KalleOlaviNiemitalo** [comment]
Well, there are two caches already. The non-generic `ILogger` is cached by LoggerFactory, and the generic `ILogger<TCategory>` is normally cached by a dependency injection container. The sample code in the description of this issue skips the latter cache though, by calling `CreateLogger<MyClass>()` on the ILoggerFactory rather than `GetService(typeof(ILogger<MyClass>))` on a DI container.

It seems the requested change would only benefit an application that does not use logging by dependency injection, and that furthermore creates loggers so often that the construction or garbage collection becomes a bottleneck.

As this change looks difficult to make without breaking compatibility of ILoggerFactory or costing performance, I think it would be better to leave Microsoft.Extensions.Logging as is and instead make the application cache the loggers. (Alternatively, the application could switch to non-generic ILogger, but that could cause ambiguity if the application currently has extension methods for different `ILogger<TCategory>` categories.)

**Comment by LirazShay** [comment]
@KalleOlaviNiemitalo 
More about my use case:
I am working on project that is not using the Microsoft DI
We're migrating to Microsoft Logging because we want have single abstraction for ILogger in our infra code / dot net 5 and old dot net repos (currently we were using LibLog and we will replace it with MS ILogger)
Our old repos do not use Microsoft DI but we want them to use Microsoft Logging  (ILogger {T} injected to each class)
In my scenario I had to call the factory and register the instance to the Autofac/Windsor containers 

Regarding what you suggested to leave it as is (cache the generic logger in the DI and cache the non generic in Logging factory):
Since those packages are different and independent (Microsoft Logging / Microsoft DI) so I don't think that we should rely on the DI implementation in order to solve Logging issues/concern even though it's possible it's not best practice

Logger caching is very basic concern. So I do think that the solution for Logging {T} should reside inside that package otherwise there will be some kind of coupling between the packages (Logging and DI). 
I agree that I can solve it in my code but it wasn't so simple to understand it and other developers users of the framework will not understand it unless it will be added to the public documentation.

I can change my code to register the logger as singleton and it will solve the problem in the container layer 
But I think that maybe it will be better to move the ILogger{T} to be used inside the factory and not as extension method
The way it's currently working feels like a hack or patch (some caching happens in the factory and some caching should happen in the container by registering as singleton)

As far as I know, most of the developers are using the generic version (because the non generic version will inject logger without correct logger name - the name of the class - and the logs will be written without the class name)
Since the future is this generic logger maybe it should not be an extension.

By the way I think that the whole idea of ILogger{T} is cumbersome
It was designed for the DI in order to create logger with the class name.
So why not just injecting ILogger for each class and when creating that instance pass the class name as argument to the factory (we're doing it in our old infra code with Windsor/Autofac/Log4Net/NLog and more)

**Comment by KalleOlaviNiemitalo** [comment]
The Microsoft.Extensions.Logging package depends on Microsoft.Extensions.DependencyInjection already. Microsoft.Extensions.Logging.Abstractions doesn't.

If Microsoft.Extensions.Logging.Abstractions were changed to make LoggerFactoryExtensions.CreateLogger\<T>(this ILoggerFactory factory) return the same ILogger\<T> every time, that would have to be done outside the ILoggerFactory interface, which cannot be changed without breaking compatibility. An implementation could be like this:

* Define a new interface ITypedLoggerFactory, with a method `ILogger<T> CreateLogger<T>();`. This could extend ILoggerFactory or not. The interface would have to be in the Microsoft.Extensions.Logging.Abstractions package.

* Change LoggerFactory ([source](https://github.com/dotnet/runtime/blob/cf258a14b70ad9069470a108f13765e0e5988f51/src/libraries/Microsoft.Extensions.Logging/src/LoggerFactory.cs)) to implement ITypedLoggerFactory and cache the results. This would make instances of LoggerFactory a little larger but I imagine apps typically don't have many instances of that anyway.

* Change LoggerFactoryExtensions.CreateLogger\<T>(this ILoggerFactory factory) ([source](https://github.com/dotnet/runtime/blob/cf258a14b70ad9069470a108f13765e0e5988f51/src/libraries/Microsoft.Extensions.Logging.Abstractions/src/LoggerFactoryExtensions.cs#L20)) to check for ITypedLoggerFactory; if implemented, call its CreateLogger\<T>() method instead of creating a Logger<T> directly.

* Do not change LoggingServiceCollectionExtensions ([source](https://github.com/dotnet/runtime/blob/cf258a14b70ad9069470a108f13765e0e5988f51/src/libraries/Microsoft.Extensions.Logging/src/LoggingServiceCollectionExtensions.cs)). So if a dependency injection container resolves ILogger\<T>, then it bypasses ITypedLoggerFactory and relies only on caching in the DI container.

Those changes would cache ILogger\<T> implementations for applications that use Microsoft.Extensions.Logging.LoggerFactory.

If an application instead uses some other implementation of ILoggerFactory that does not support ITypedLoggerFactory, then LoggerFactoryExtensions.CreateLogger\<T> would still create a new Logger\<T> on each call. If that is not acceptable, then it would have to be fixed in a different way, perhaps by using ConditionalWeakTable\<ILoggerFactory, ITypedLoggerFactory> in LoggerFactoryExtensions. (Using the ILogger instances as keys in ConditionalWeakTable seems more difficult because the ILoggerFactory might return the same ILogger implementation instance for multiple categories even if each category has to be mapped to a different ILogger\<T> type.)

At that point though, I wonder whether the complex ILogger\<T> caching would even give your app better performance than creating a new Logger\<T> each time. Or do you have some non-performance reason why you need the loggers to be cached?

**Comment by davidfowl** [comment]
Is this a performance issue? If yes are there associated performance numbers? If this isn't about performance, what's it about?

**Comment by LirazShay** [comment]
Hi @davidfowl 
Yes it's about caching the Logger instances and reusing the same instance - it's something basic across all logging frameworks to cache the logger - that's why the LoggerFactory has dictionary to use existing instances
We found scenario that by design it's not cached
I don't have numbers
There was old discussion that suggested small change in this area - 
https://github.com/aspnet/Logging/issues/727
So the design suggested by @KalleOlaviNiemitalo will also help from other aspects

**Comment by davidfowl** [comment]
I don't want to introduce *any* new types and complicate the design without a *great* reason to. I'd like to see those great reasons outlined here. ILogger<T> was introduced as a dependency injection specific extension as the generic isn't used for much else. 

I'd like to see the usage pattern you have now and to understand the problems you are running into. 

PS: I love making performance improvements but I want to make sure they are worth it.

**Comment by LirazShay** [comment]
@KalleOlaviNiemitalo Regarding your suggested design to solve it - I likes it.

I just have few comments:
1)
> Change LoggerFactory (source) to implement ITypedLoggerFactory and cache the results. This would make instances of LoggerFactory a little larger but I imagine apps typically don't have many instances of that anyway.

LoggerFactory is singleton - it will always be used like that
https://github.com/dotnet/runtime/blob/cf258a14b70ad9069470a108f13765e0e5988f51/src/libraries/Microsoft.Extensions.Logging/src/LoggingServiceCollectionExtensions.cs#L41

2) Regarding ConditionalWeakTable it's overkill 

3) So extending ILoggerFactory and adding the method for CreateLogger{T} is not an option at all? (breaking change)

**Comment by KalleOlaviNiemitalo** [comment]
> I agree that I can solve it in my code but it wasn't so simple to understand it and other developers users of the framework will not understand it unless it will be added to the public documentation.

Improving the documentation would be uncontroversial, I hope. Add a note to the [LoggerFactoryExtensions.CreateLogger](https://docs.microsoft.com/dotnet/api/microsoft.extensions.logging.loggerfactoryextensions.createlogger?view=dotnet-plat-ext-5.0) page saying that these methods are not very efficient, and that performance-sensitive code should do one of:

* cache the result; or
* resolve ILogger\<TCategoryName> from a dependency injection container that caches the result as a singleton; or
* use [ILoggerFactory.CreateLogger(string)](https://docs.microsoft.com/dotnet/api/microsoft.extensions.logging.iloggerfactory.createlogger?view=dotnet-plat-ext-5.0) with a string that is not built from a Type each time.

**Comment by davidfowl** [comment]
@shirhatti  @noahfalk if we do the singleton logger factory feature, we'll need to fix this.

**Comment by LirazShay** [comment]
@davidfowl 
Thanks for the update!
By the way, will it be possible to allow injection of non generic ILogger initialized with the class name as category name?
Since the generic Logger (ILogger<T>) does not add any new functionality, I feel it makes the code little verbose - in our new repos every class has field like this: ILogger<XYXService> _logger.
In my opinion, I would like to use ILogger _logger;
But currently it's not supported by the IOC automatically.
We wrote custom code to guide the windsor/autofac containers how to resolve ILogger (non generic) for each class with the class name.
I know it's bit hard to do in MS DI because it's generic abstraction and the solution should be designed carefully but I find it very useful to allow users write classes that depend on ILogger (not ILogger<T>)
I tried to use ILogger<T> only in the c'tor and save it in ILogger as field type but our architects didn't like the idea of using different type for field type (ILogger<T> in c'tor parameter type and ILogger as field type to save the logger)
So I find myself writing too much ILogger<T>s, it was cumbersome the verbose for me.
What is your opinion?

**Comment by davidfowl** [comment]
What would the category be?

**Comment by KalleOlaviNiemitalo** [comment]
If I understand correctly, the request is that

```C#
class AccountController
{
    public AccountController(ILogger logger) {}
}
```

would cause the dependency container to inject an `ILogger` whose category name is generated from `typeof(AccountController)`. That feels too magical to me, and unlikely to be supported by all dependency containers that implement the Microsoft.Extensions.DependencyInjection abstractions. Perhaps a similar feature could instead be achieved with a source generator that adds another constructor:

```C#
partial class AccountController
{
    public AccountController(ILoggerFactory factory)
        : this(factory.Create("AccountController"))
    {
    }
}
```

`ILogger<TCategoryName>` would not be involved, and `LoggerFactory` would cache the loggers.

@LirazShay, are your [EventId](https://docs.microsoft.com/dotnet/api/microsoft.extensions.logging.eventid?view=dotnet-plat-ext-5.0) values unique per category or per assembly? I find that using e.g. `ILogger<AccountController>` rather than plain `ILogger` in fields and extension methods makes it clear where I can reuse [EventId.Id](https://docs.microsoft.com/dotnet/api/microsoft.extensions.logging.eventid.id?view=dotnet-plat-ext-5.0) numbers.

**Comment by davidfowl** [comment]
I agree that is too magical for me 😄. We'd need to extend DI in ways that may not work with other containers. We've basically frozen DI for new features at this point so to make something like this work, you'd need to use a DI container that had an advanced feature like this.

**Comment by LirazShay** [comment]
@davidfowl , @KalleOlaviNiemitalo 
Thanks a lot for considering my suggestion.

I can understand that it seems little magical for the first time (how to ILogger will be resolved with class name)
 but for many DI containers it is simple to implement 
I didn't invent this convention, you can see this [link ](http://codingsoul.org/2016/07/18/logging-with-log4net-and-windsor-castle/) that explained how to implement it with Log4Net

In Windsor we just used simple factory method to resolve ILogger and one the parameters in the requested class type 
```
 container.Register(Component.For<ILogger>()
                    .UsingFactoryMethod((kernel, model, context) =>
                    {
                        var loggerFactory = kernel.Resolve<ILoggerFactory>();
                        return loggerFactory.CreateLogger(context.Handler.ComponentModel.Implementation);
                    }).LifestyleTransient());
```
I also understand the there are other priorities for now but thanks anyway!

@KalleOlaviNiemitalo 
Regarding your alternative solution - 
```
partial class AccountController
{
    public AccountController(ILoggerFactory factory)
        : this(factory.Create("AccountController"))
    {
    }
}
```
I don't feel it will make things easier, even with nameof() (it's problematic to hard code the class name)
I will prefer to use the generic logger than to add this line in every class that we have in our repo

**Comment by LirazShay** [comment]
@KalleOlaviNiemitalo 
Regarding your question about eventId can you please explain more if it's still relevant for you?###

**Comment by KalleOlaviNiemitalo** [comment]
@LirazShay, I asked about EventId because it was not clear to me how to best define event IDs in my own logging, and I am curious whether your experiences differ from mine.

As I understand it, the purpose of EventId is to make log entries easier to filter on the fly or analyze afterwards. Microsoft.Extensions.Logging.TraceSource [uses only EventId.Id](https://github.com/dotnet/runtime/blob/478b2f8c0e480665f6c52c95cd57830784dc9560/src/libraries/Microsoft.Extensions.Logging.TraceSource/src/TraceSourceLogger.cs#L43) and ignores EventId.Name; so if I am developing a library that logs events, I should make EventId.Id unique. However, because each event also has a category string that can be filtered on, I think it is OK to have different meanings for the same EventId.Id in different categories.

This then lead me to use `ILogger<TCategoryName>` almost everywhere instead of plain `ILogger`. For each category, I define a static class that provides extension methods for that `ILogger<TCategoryName>`. Each such class starts its EventId.Id numbers from 1, and that's OK because the category strings will differ.

So, I'm interested in whether you keep the EventId.Id numbers unique even between different log categories in the same assembly, if you use EventId at all.

**Comment by LirazShay** [comment]
@KalleOlaviNiemitalo thanks for the explanation!
I'm not using the event id at all.
By the way, you said:

> This then lead me to use ILogger<TCategoryName> almost everywhere instead of plain ILogger
Now you might feel what the users are doing all the time...
As I mentioned before - in our code we must use the generic ILogger all the time because the IOC only supports generic logger, otherwise all classes will get logger with the same category
Do you also feel it's too verbose ? (the generic logger was invented in .NET Core logging, I don't remember this convensin in any logging framework ever)

**Comment by KalleOlaviNiemitalo** [comment]
If Microsoft.Extensions.DependencyInjection had supported [named services](https://autofac.readthedocs.io/en/latest/advanced/keyed-services.html) like Autofac, then perhaps Microsoft.Extensions.Logging could have built on that and supported specifying the category with an attribute, something like `MyClass([LogCategory("MyNamespace.MyClass")]ILogger logger)`. But I think it's now too late for that.

**Comment by KalleOlaviNiemitalo** [comment]
> I will prefer to use the generic logger than to add this line in every class that we have in our repo

The idea was that the additional constructor would be inserted by a source generator when you build your project, so the lines would not be committed to your repo. You would still have to declare all of those classes as `partial`, though. (You might also have to add some attribute to the classes, depending on how the source generator were implemented.)

**Comment by qsdfplkj** [comment]
I assumed the same but found myself thinking maybe _the expectation is wrong_.  Why should an extension method return the same instance? It is a _factory_ and the method is called _Create_ . You could also expect that the factory returns a new object when you call create so why does the factory even cache these objects?

I think the underlying reason for it is that when introducing `ILogger<T>` (derived from `ILogger`) that in itself shouldn't be a reason to have to change the `ILoggerFactory` that is fully based on `ILogger`.

Besides you don't really need `ILogger<T>` you could call `factory.CreateLogger(typeof(T))`.

It is only useful for the `ServiceProvider` that needs it to inject the proper instances of `ILogger<T>` which does track all the instances of `ILogger<T>` as it is a singleton so usually you will not have multiple instances. You could inject `ServiceProvider` and call `GetService<Ilogger<T>>();`  and consider your `ServiceProvider` to be the logger factory that solves you issue.

**Comment by nadyai** [comment]
The main problem,  I face up is that factory.CreateLogger<T>() is kind of a heavy operation and is intended to be used once, for singleton. I would prefer for applications with no proper DI to have LoggerHandler<T> which will handle caching and re-using of generic loggers.

**Comment by davidfowl** [comment]
https://github.com/dotnet/runtime/issues/48473#issuecomment-787486410

@nadyai I would love to fix this but can you answer some of the questions I asked above?

**Comment by gcsizmadia** [comment]
@LirazShay, I have implemented a similar function for `Autofac` that simply creates the specific generic `ILogger<T>` type then resolves it from the container. Check [here](https://github.com/gcsizmadia/EgonsoftHU.Extensions.Logging.Autofac/blob/main/src/EgonsoftHU.Extensions.Logging.AutofacV6/DependencyModule.cs).

It is also available as a nuget package.

@davidfowl, if there was a possibility to access the `System.Reflection.ParameterInfo` instance of the ctor parameter that is being resolved (e.g. the `IServiceProvider` could have some property of the resolution context that contains that `ParameterInfo`) then we can use the already existing methods as below.

```csharp
WebApplicationBuilder builder = WebApplication.CreateBuilder(args);

builder.Services.AddSingleton<ILogger>(
    serviceProvider =>
    (ILogger)serviceProvider.GetRequiredService(
        typeof(ILogger<>).MakeGenericType(serviceProvider.ResolutionContext.Parameter.Member.DeclaringType)
    )
);
```

**Comment by qsdfplkj** [comment]
A simple solution would be to move the two CreateLogger extension methods to the ILoggerFactory so that ILogger and ILogger<T> are both created from the same factory and both can be cached.

**Comment by levicki** [comment]
@davidfowl @KalleOlaviNiemitalo 
> If `Microsoft.Extensions.Logging.Abstractions` were changed to make `LoggerFactoryExtensions.CreateLogger<T>(this ILoggerFactory factory)` return the same `ILogger<T>` every time, that would have to be done outside the `ILoggerFactory` interface, which cannot be changed without breaking compatibility.

I am trying to understand what is stopping you from changing the `LoggerFactoryExtensions.CreateLogger<T>(this ILoggerFactory factory)` implementation to do:
```
public static class LoggerFactoryExtensions
{
+	private static readonly ConcurrentDictionary<string, object> m_Loggers = new ConcurrentDictionary<string, object>(StringComparer.Ordinal);
+	private static readonly object m_Sync = new object();

	public static ILogger<T> CreateLogger<T>(this ILoggerFactory factory)
	{
		if (factory == null) {
			throw new ArgumentNullException(nameof(factory));
		}
		
-		return new Logger<T>(factory);
+		object Logger = null;
+
+		if (!m_Loggers.TryGetValue(nameof(T), out Logger)) {
+			lock (m_Sync) {
+				if (!m_Loggers.TryGetValue(nameof(T), out Logger)) {
+					Logger = new Logger<T>(factory);
+					m_Loggers[nameof(T)] = Logger;
+				}
+			}
+		}
+
+		return (ILogger<T>)Logger;
	}
}
```
Is this because someone might expect that every `ILogger<T>` returned is a different instance? Is that assumption even part of some interface contract? To me this looks like implementation detail, not something ILoggerFactory interface should care about especially given that this is an extension method.

From the documentation I see that both `CreateLogger(ILoggerFactory, Type)` and `CreateLogger<T>(ILoggerFactory)` are supposedly creating a new instance:

![image](https://github.com/dotnet/runtime/assets/16415478/30701775-c1a6-4c74-ad68-fa0af7eaf8e6)

Yet one of them doesn't as clearly demonstrated in this issue.

The only possible concern I see here is with creating a separate cache for `ILogger<T>` instances.

**Comment by levicki** [comment]
@KalleOlaviNiemitalo That still doesn't explain why it can't be done?

**Comment by levicki** [comment]
> `static readonly ConcurrentDictionary<string, object> m_Loggers` would have to be `static readonly ConditionalWeakTable<ILoggerFactory, ConcurrentDictionary<string, object>>` instead, in case the application has multiple logger factories.

Here is a naive implementation with your change, please let me know if I am doing something wrong:
```
public static class MyLoggerFactoryExtensions
{
	private static readonly ConditionalWeakTable<ILoggerFactory, ConcurrentDictionary<string, object>> m_Loggers = new ConditionalWeakTable<ILoggerFactory, ConcurrentDictionary<string, object>>();
	private static readonly object m_SyncFactory = new object();
	private static readonly object m_SyncCache = new object();

	public static ILogger<T> CreateLogger<T>(this ILoggerFactory factory) where T : class
	{
		ConcurrentDictionary<string, object> Cache = null;

		if (!m_Loggers.TryGetValue(factory, out Cache)) {
			lock (m_SyncFactory) {
				if (!m_Loggers.TryGetValue(factory, out Cache)) {
					Cache = new ConcurrentDictionary<string, object>(StringComparer.Ordinal);
					m_Loggers.Add(factory, Cache);
				}
			}
		}

		object Logger = null;

		if (!Cache.TryGetValue(nameof(T), out Logger)) {
			lock (m_SyncCache) {
				if (!Cache.TryGetValue(nameof(T), out Logger)) {
					Logger = new Logger<T>(factory);
					Cache[nameof(T)] = Logger;
				}
			}
		}

		return (ILogger<T>)Logger;
	}
}
```

**Comment by davidfowl** [comment]
It's wrong, the cache key is the logger factory instance + the key. I'd prefer to add a default interface member on .NET 9 + where the logger can implement this caching in a non-static way.

**Comment by levicki** [comment]
@davidfowl Check updated example above.

**Comment by qsdfplkj** [comment]
If you e.g. CreateLogger<T>() and then call CreateLogger(typeof(T).Name)  you still get different instance while logging to the same category. You should use the same cache as is in the loggerfactory caching ILogger instances. Where Logger<T> is  just a wrapper for ILogger.

**Comment by levicki** [comment]
> If you call e.g. `CreateLogger<T>()` and then call `CreateLogger(typeof(T).Name)` you still get different instance while logging to the same category. You should use the same cache as is in the loggerfactory caching `ILogger` instances. Where `Logger<T>` is just a wrapper for an `ILogger`.

As I said, it is a naive implementation brute-forced in 5 minutes showing that it can be done and (assuming it is correct) it results in 35% speed gain and 2.5x less memory usage. I totally agree that it should work the same as the LoggerFactory caching, but I still can't understand what's stopping Microsoft developers from implementing it properly for so long?

**Comment by qsdfplkj** [comment]
You can't fix getting the same instance via both `CreateLoggers` with an extension method as you can't use the `LoggerFactory` cache that is used by `CreateLogger(string categoryName)`. But Microsoft can. It should be simple to solve as they could add a `CreateLogger<T>()` to the `ILoggerFactory` interface. Whatever their  reason is I can only guess probably some strict design guidelines. Maybe they don't want generic code inside nongeneric classes.

**Comment by levicki** [comment]
@qsdfplkj You are right, I can't do it like that (for starters even if I had the code for `TypeNameHelper` I can't just cast to `ILogger<T>`. Microsoft devs can surely do something, but as usual they chase some perfection and schedule the fix for some N+1 framework version which is always one version away.

Meanwhile back in the real world we the customers are forced to use the old versions of framework and stuck with rolling our own imperfect workarounds because we can't just upgrade our framework willy-nilly &mdash; try doing that in banking or medical industry and see how much you will have to pay for various re-certifications of your application if you change more than your own code.

I don't expect Microsoft devs who are used to moving fast and breaking things without cost and consequence (other than for their customers) to understand that.

**Comment by davidfowl** [comment]
>  It should be simple to solve as they could add a CreateLogger<T>() to the ILoggerFactory interface.

Right, this is what I said above.

**Comment by qsdfplkj** [comment]
I think my comment is flawed. `ILogger` and `ILogger<T>` of the same category can't ever be the same instance as `ILogger<T>` needs `ILogger`. Therefore we can only cache it in the extension:

like https://github.com/dotnet/runtime/issues/48473#issuecomment-1896456863
```
public static class MyLoggerFactoryExtensions
{
    private static readonly ConditionalWeakTable<ILoggerFactory, ConcurrentDictionary<Type, ILogger>> _loggers = [];

    public static ILogger<T> CreateLogger<T>(this ILoggerFactory factory)
    {
        // GetOrCreateValue is atomic
        var cache = _loggers.GetOrCreateValue(factory); 
        // GetOrAdd the used valueFactory is not thread safe and can create multiple instance until one is added
        // but only the first added instance is ever returned so you get no duplicates.
        // so either take the risk and be faster
        return (ILogger<T>)cache.GetOrAdd(typeof(T), _ => new Logger<T>(factory));
        // or take the penalty and make it thread safe
        return (ILogger<T>)cache.GetOrAdd(typeof(T), _ => new Lazy<ILogger<T>>(() => new Logger<T>(factory)).Value);

    }
}
```

**Comment by levicki** [comment]
> Right, this is what I said above.

So basically it boils down to this:

 - We have a generic method CreateLogger<T>() which is suboptimal (35% performance and 2.5x memory penalty) compared to non-generic method
 - Therefore we should avoid using generic `Logger<T>` which is most often used for dependency injection
 - In libraries we have to pass `ILoggerFactory` into all classes and keep reference to it in each class so we can create loggers inside of each of those classes with proper `categoryName` (unless there's a better solution?)
 - In those libraries instead of writing `_logger = factory.CreateLogger<ClassA>()` we now have to write `_logger = factory.CreateLogger(nameof(ClassA))` or `_logger = factory.CreateLogger(typeof(ClassA))`, both of which look like a code smell compared to using a generic.

I really wish framework stuff wasn't this unorthogonal.

**Comment by davidfowl** [comment]
> Therefore we should avoid using generic Logger<T> which is most often used for dependency injection

This is actually not expensive because the DI system is caching `Logger<T>` instances as singletons when injected.

**Comment by levicki** [comment]
> This is actually not expensive because the DI system is caching `Logger<T>` instances as singletons when injected.

 - Is this true for all DI container implementations (Unity, Autofac, etc) or only for Microsoft's implementation in .NET 5+?
 - What about all the libraries which can't use DI and already use `ILoggerFactory` and `ILogger<TCategoryName>` pattern as per [Microsoft's own guidance](https://learn.microsoft.com/en-us/dotnet/core/extensions/logging-library-authors)?

On a side note, unlike NLog, Serilog for example fails all three asserts in the issue sample code &mdash; it always returns new instance even when they are created with `CreateLogger(string CategoryName)` and `CreateLogger(Type type)` so your performance can be even worse depending on which logging implementation you are using.

So instead of whoever designed `ILoggerFactory` making the instance caching an explicit part of the contract by naming the method `CreateOrGetLogger()` we now have this mess.

**Comment by CoenraadS** [comment]
I read this thread and see the recommendation is to use the DI, but then what is the recommended practice for creating an ILogger when using e.g. a factory pattern, and the target class requires a logger?

e.g. 

```
class FooFactory(IServiceProvider sp)
{

    public Foo Create(string name)
    {
        return new Foo(name, sp.GetRequiredService<ILogger<Foo>>());
    }
}
```

Then since this isn't really nice for e.g. type safe unit testing, because it is using the lookup anti-pattern, one might be expected to create their own 'DILoggerFactory` or something which wraps the service provider?

**Comment by levicki** [comment]
@CoenraadS You can use something like this:
```
public static class ClassFactory
{
	public static ILoggerFactory LoggerFactory { get; set; }

	public static T CreateWithLogger<T>(params object[] args)
	{
		Type t = typeof(T);

		ConstructorInfo ctor = t.GetConstructors().Where(x => x.IsPublic &&
								      x.CallingConvention.HasFlag(CallingConventions.HasThis) &&
								      x.GetParameters().Length >= 1 &&
								      x.GetParameters()[0].ParameterType == typeof(ILogger<T>)).First();

		if (ctor != null) {
			ParameterInfo[] pi = ctor.GetParameters();
			object[] ctorargs = new object[pi.Length];
			ILogger<T> Logger = LoggerFactory.CreateOrGetLogger<T>();
			ctorargs[0] = Logger;
			for (int i = 1; i < pi.Length; i++) {
				if (i < args.Length + 1) {
					ctorargs[i] = args[i - 1];
				} else {
					if (pi[i].IsOptional && pi[i].HasDefaultValue) {
						ctorargs[i] = Type.Missing;
					}
				}
			}
			return (T)ctor.Invoke(ctorargs);
		} else {
			return default(T);
		}
	}
}

public static class LoggerFactoryExtensions
{
	private static readonly ConditionalWeakTable<ILoggerFactory, ConcurrentDictionary<string, object>> m_Factories = new ConditionalWeakTable<ILoggerFactory, ConcurrentDictionary<string, object>>();
	private static readonly object m_FactoriesLock = new object();
	private static readonly object m_LoggersLock = new object();

	public static ILogger<T> CreateOrGetLogger<T>(this ILoggerFactory factory)
	{
		ConcurrentDictionary<string, object> Loggers = null;

		if (!m_Factories.TryGetValue(factory, out Loggers)) {
			lock (m_FactoriesLock) {
				if (!m_Factories.TryGetValue(factory, out Loggers)) {
					Loggers = new ConcurrentDictionary<string, object>(StringComparer.Ordinal);
					m_Factories.Add(factory, Loggers);
				}
			}
		}

		object Logger = null;
		string CategoryName = typeof(T).FullName;

		if (!Loggers.TryGetValue(CategoryName, out Logger)) {
			lock (m_LoggersLock) {
				if (!Loggers.TryGetValue(CategoryName, out Logger)) {
					Logger = new Logger<T>(factory);
					Loggers[CategoryName] = Logger;
				}
			}
		}

		return (ILogger<T>)Logger;
	}
}
```
It creates an instance of a class and does the `ILogger<T>` injection for you provided that the constructor of the class passed as `T` has `ILogger<T>` as its first argument and unlike regular DI it can also pass additional arguments during creation including optional ones.

Of course, it has limitations (does not use a DI container or a service, error checking can always be improved), but it works well enough for my use case of writing a bunch of class libraries which get `ILoggerFactory` as input and which aren't supposed to spill their innards into external code that uses a DI container.

**Comment by rosebyte** [comment]
The generic ILogger&lt;T> interface is meant to be used by DI containers to provide a logger associated with a particular class (so you can later filter logs by the class` name), but expressed as a constructor parameter type. This lets you write:

```csharp
public MyClass(ILogger<MyClass> logger) {...}
```

and the DI container knows how to supply the correct logger. DI also caches these loggers, so this pattern is efficient and by adding aditional cache we would just duplicate what the DI does. If you don’t use a DI container, you don’t need ILogger&lt;T> at all. You can obtain the appropriate logger for your class using:

```csharp
loggerFactory.CreateLogger(typeof(MyClass))
```

This also returns a cached logger, so that approach works just as well.

**Comment by levicki** [comment]
@rosebyte Did you actually run the code with asserts from the OP?

**Comment by LirazShay** [comment]
I think the severity of this issue might be underestimated.

In dotnet/aspnetcore#53200 the ASP.NET Core team had to update around 30 call sites to avoid the CreateLogger<T>() overhead by switching to a cached logger pattern (CreateLogger(typeof(...))).

If this issue had been fixed when it was originally reported, that PR likely wouldn’t have been necessary.

What happened instead is effectively a patch in many places rather than addressing the root cause. Multiple call sites were changed to work around the lack of caching in CreateLogger<T>().

It might be better to solve this at the framework level, since fixing it once would automatically benefit all consumers instead of requiring every project to implement the same workaround.

**Comment by rosebyte** [comment]
Let’s wrap it up:

1. Not all created objects are cached. Caching is a trade-off and only makes sense for expensive instances.
2. Logger&lt;T> is cheap; it is basically just a single reference to the underlying Logger, so it is not cached.
3. The primary motivation for tracking Logger instances in LoggerFactory is to propagate configuration changes. Having a single instance per category is a natural consequence.
4. There is nothing special we could do that anyone else could not, as anyone can have a factory like this:

```csharp
public sealed class CachedLoggerFactory(ILoggerFactory factory)
{
    private readonly ConcurrentDictionary<Type, object> _cache = new();
    public ILogger<T> Get<T>() => (ILogger<T>)_cache.GetOrAdd(typeof(T), _ => factory.CreateLogger<T>());
}
```

5. Caching the instances by default would affect all users who do not need it, for example because they use DI.

We discussed this issue in our triage process and agreed that this does not feel like a bug and can be closed after five years, as the discussion did not bring a strong reason to cache the Logger&lt;T> instances returned from the extension method.

Anyway, if anyone has a real-world use case that is blocked by this, please let us know so we can reconsider and potentially reopen the issue.
