### ISSUE TITLE
Incorrect parsing of large floating point number: one bit offset

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [dotnet/runtime#48648]
### Description
Parsing large floating-point numbers sometimes produces a number that differs from the correct value by one bit.
In particular, "6250000000000000000000000000000000e-12" produces this error.
The problem is illustrated in this sharplab.io [sample](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxAgrgOwD4AEBMADALABQBAjGboQAS4UB0AMgJaYCOA3GQG4QJasQQF5aAIgBs+AKyF5CxUuUqFcALQV84nqX6DcuACYB7dMAA2cWmNPmrjAAoCocABTCk9JgHELJ4AgLVgAvCBhWE0xGADl0MGBEAGUYAE8rKEYAQUxUgEpdfVpgVPgoG1oAIVYYAGEo3kR4BDJaNtpGHzgYStK4KDdDO0s4PNb2xiS4KwBjGDcADxsAPloFxgAVExSEdgBzN3EADUJtPLHSdo6svb2EOD3w9zcTCyMvQ0w4AHc8ldpXkZaABqei4L6/XR8AS0BAQb69MoVCHFPoAbQAurQAN6EBYAMUkXjxABYssSFgBRCgU2oAdgppwp+AAIhS6TIKSSSQBfKHkCgATkGxjMIwK1CFbmqdQaTUQmxMLLFVjccIRfSg510DGFJTKEoFwvViP6k2mcDmi3+6y2O32hxOZzy2Vu90e8DcLzeH3BPz+IlWgJBYIh2qAA)

Let `@double = double.Parse("6250000000000000000000000000000000e-12", NumberStyles.Any)`.
The first indication of the parsing problem is that the default string representation of `@double` is "6.250000000000001E+21" (note an extra `1` at the end).
The (little-endian) byte-representation (obtained with e.g. `BitConverter.GetBytes`) is 
`"F74AE1C7022D7544"`.
This representation is unfortunately incorrect.
The value `6.25e21` can be represented more accurately by a double-precision variable, and the byte-representation of this value is in fact
`"F64AE1C7022D7544"`.
The difference (for this particular number) is one bit (`F6` vs `F7`).
The mentioned above sharplab sample nicely illustrates this problem.

This issue was discovered when dotnet's parsing methods were run against a large set of floating point tests provided in this repository
https://github.com/nigeltao/parse-number-fxx-test-data

The test case discussed in this issue is found in `data/ibm-fpgen.txt`, line 64724
<details>
7C00 63A96816 44752D02C7E14AF6 6250000000000000000000000000000000e-12
</details>

There may be other (similar) issues, which I have not found yet.
#

### Configuration
So far tested on Windows 10 x64 20H2 19042.804
- dotnet @ Windows: 
  - 5.0.103
  - 6.0.100-preview.1.21103.13

- dotnet @ WSL2:
  - 5.0.103

Whatever backend sharplab.io uses also reproduces this error.

### Regression?

Did not test earlier versions of dotnet.

### Other information
This report would not be possible without https://github.com/nigeltao/parse-number-fxx-test-data project and its contributors.

I verified this particular parsing case against Rust implementation, see this [rust demo](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=fn%20main()%20%7B%0A%20%20%20%20let%20str%20%3D%20%226250000000000000000000000000000000e-12%22%3B%0A%20%20%20%20let%20str_f64%20%3D%20%2244752D02C7E14AF6%22%3B%0A%20%20%20%20let%20str_f32%20%3D%20%2263A96816%22%3B%0A%20%20%20%20let%20val_f64%20%3D%20str.parse%3A%3A%3Cf64%3E().unwrap()%3B%0A%20%20%20%20let%20val_f32%20%3D%20str.parse%3A%3A%3Cf32%3E().unwrap()%3B%0A%20%20%20%20%0A%20%20%20%20let%20str_f64_p%20%3D%20val_f64.to_be_bytes().iter().map(%7C%26x%7C%20format!(%22%7B%3A02X%7D%22%2C%20x)).collect%3A%3A%3CString%3E()%3B%0A%20%20%20%20let%20str_f32_p%20%3D%20val_f32.to_be_bytes().iter().map(%7C%26x%7C%20format!(%22%7B%3A02X%7D%22%2C%20x)).collect%3A%3A%3CString%3E()%3B%0A%20%20%20%20%0A%20%20%20%20println!(%22%7B%3A%3F%7D%22%2C%20str_f64)%3B%0A%20%20%20%20println!(%22%7B%3A%3F%7D%22%2C%20str_f64_p)%3B%0A%20%20%20%20%0A%20%20%20%20println!(%22%7B%3A%3F%7D%22%2C%20str_f32)%3B%0A%20%20%20%20println!(%22%7B%3A%3F%7D%22%2C%20str_f32_p)%3B%0A%20%20%20%20%0A%20%20%20%20println!(%22%7B%3A%3F%7D%22%2C%20val_f64.to_be_bytes())%3B%0A%20%20%20%20println!(%22%7B%3A%3F%7D%22%2C%20val_f32.to_be_bytes())%3B%0A%20%20%20%20%0A%7D).

Maybe related to #48119
Partially inspired by discussion around #48646.

**Comment by Ilia-Kosenkov** [comment]
This issue may arise here
https://github.com/dotnet/runtime/blob/4396f0948e66b0d78ec106209bdd61d0e3ecaf85/src/libraries/System.Private.CoreLib/src/System/Number.NumberToFloatingPointBits.cs#L217

And here
https://github.com/dotnet/runtime/blob/4396f0948e66b0d78ec106209bdd61d0e3ecaf85/src/libraries/System.Private.CoreLib/src/System/Number.NumberToFloatingPointBits.cs#L737-L755
There should be no rounding for this number (if I understand this correctly).
I am unable to trace what causes `ShouldRoundUp` to return `true` instead of `false`.

**Comment by tannergooding** [comment]
@pgovind, can you check if this is handled by your trailing zero fix?

**Comment by Ilia-Kosenkov** [comment]
Just to clarify - after running parsing tests for all of the test datasets ([in this folder](https://github.com/nigeltao/parse-number-fxx-test-data/tree/main/data), 5 268 191 strings), this is *the only value* that fails parsing test, so this is probably something quite rare.

**Comment by tannergooding** [comment]
Thanks! We had also run another large suite from ES6 covering 100m inputs and hadn't found any failures there either, so I expect you're right.

The Roslyn implementation doesn't have this bug so it was likely introduced by one of the refactorings or perf improvements on the libraries side.
Given the large number of trailing zeros with a negative exponent here, I'm hoping that it's fixed by the bug that @pgovind recently fixed.

**Comment by tannergooding** [comment]
We should make sure to add a regression test for this before closing the issue in either case.

**Comment by pgovind** [comment]
Hmm weird, this is not fixed by https://github.com/dotnet/runtime/pull/47666/files. Investigating locally.

**Comment by pgovind** [comment]
So, this is similar to https://github.com/dotnet/runtime/issues/46827. #47666 does not fix this because #47666 only works when we encounter a decimal point in the input. Since there is no decimal point in the input here, we never calculate the number of trailing zeros. 

The fix here is to carefully update the trailing zero calculation to take such cases into account.
