### ISSUE TITLE
[wasm][eat] Multiple tests failing for `System.Runtime.Tests`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#51912]
[System.Runtime.Tests](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-51697-merge-90ffb7de7255439c90/System.Runtime.Tests/console.b0a32014.log?sv=2019-07-07&se=2021-05-17T03%3A12%3A00Z&sr=c&sp=rl&sig=bXMAyTUXxvq97zAdN2V2kiBsJmBvk5%2BGJAHi0YFh1Ok%3D)

```
[03:37:22] fail: [FAIL] System.Runtime.Tests.NullableMetadataTests.ShimsHaveOnlyTypeForwards(assemblyName: "mscorlib")
[03:37:22] info: System.IO.FileNotFoundException :
[03:37:22] info:    at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
[03:37:22] info:    at System.Reflection.Assembly.Load(String assemblyString)
[03:37:22] info:    at System.Runtime.Tests.NullableMetadataTests.ShimsHaveOnlyTypeForwards(String assemblyName)
[03:37:22] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[03:37:22] fail: [FAIL] System.Runtime.Tests.NullableMetadataTests.ShimsHaveOnlyTypeForwards(assemblyName: "System.Threading.Overlapped")
[03:37:22] info: System.IO.FileNotFoundException :
[03:37:22] info:    at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
[03:37:22] info:    at System.Reflection.Assembly.Load(String assemblyString)
[03:37:22] info:    at System.Runtime.Tests.NullableMetadataTests.ShimsHaveOnlyTypeForwards(String assemblyName)
[03:37:22] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[03:37:22] fail: [FAIL] System.Runtime.Tests.NullableMetadataTests.NullablePublicOnlyAttributePresent(type: typeof(string))
[03:37:22] info: Assert.NotNull() Failure
[03:37:22] info:    at System.Runtime.Tests.NullableMetadataTests.NullablePublicOnlyAttributePresent(Type type)
[03:37:22] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[03:37:22] fail: [FAIL] System.Runtime.Tests.NullableMetadataTests.NullablePublicOnlyAttributePresent(type: typeof(System.Collections.Generic.Dictionary<,>))
[03:37:22] info: Assert.NotNull() Failure
[03:37:22] info:    at System.Runtime.Tests.NullableMetadataTests.NullablePublicOnlyAttributePresent(Type type)
[03:37:22] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[03:37:22] fail: [FAIL] System.Runtime.Tests.NullableMetadataTests.NullablePublicOnlyAttributePresent(type: typeof(System.Uri))
[03:37:22] info: Assert.NotNull() Failure
[03:37:22] info:    at System.Runtime.Tests.NullableMetadataTests.NullablePublicOnlyAttributePresent(Type type)
[03:37:22] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[03:37:22] fail: [FAIL] System.Runtime.Tests.NullableMetadataTests.NullablePublicOnlyAttributePresent(type: typeof(System.Collections.Concurrent.ConcurrentDictionary<,>))
[03:37:22] info: Assert.NotNull() Failure
[03:37:22] info:    at System.Runtime.Tests.NullableMetadataTests.NullablePublicOnlyAttributePresent(Type type)
[03:37:22] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[03:37:22] fail: [FAIL] System.Runtime.Tests.NullableMetadataTests.NullablePublicOnlyAttributePresent(type: typeof(System.Buffers.ArrayPool<>))
[03:37:22] info: Assert.NotNull() Failure
[03:37:22] info:    at System.Runtime.Tests.NullableMetadataTests.NullablePublicOnlyAttributePresent(Type type)
[03:37:22] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[03:37:22] fail: [FAIL] System.Runtime.Tests.NullableMetadataTests.NullableAttributesOnPublicApiOnly(type: typeof(string))
[03:37:22] info: Assert.True() Failure
[03:37:22] info: Expected: True
[03:37:22] info: Actual:   False
[03:37:22] info:    at System.Runtime.Tests.NullableMetadataTests.NullableAttributesOnPublicApiOnly(Type type)
[03:37:22] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[03:37:22] fail: [FAIL] System.Runtime.Tests.NullableMetadataTests.NullableAttributesOnPublicApiOnly(type: typeof(System.Collections.Generic.Dictionary<,>))
[03:37:22] info: Assert.True() Failure
[03:37:22] info: Expected: True
[03:37:22] info: Actual:   False
[03:37:22] info:    at System.Runtime.Tests.NullableMetadataTests.NullableAttributesOnPublicApiOnly(Type type)
[03:37:22] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[03:37:22] fail: [FAIL] System.Runtime.Tests.NullableMetadataTests.NullableAttributesOnPublicApiOnly(type: typeof(System.Uri))
[03:37:22] info: Assert.True() Failure
[03:37:22] info: Expected: True
[03:37:22] info: Actual:   False
[03:37:22] info:    at System.Runtime.Tests.NullableMetadataTests.NullableAttributesOnPublicApiOnly(Type type)
[03:37:22] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[03:37:22] fail: [FAIL] System.Runtime.Tests.NullableMetadataTests.NullableAttributesOnPublicApiOnly(type: typeof(System.Collections.Concurrent.ConcurrentDictionary<,>))
[03:37:22] info: Assert.True() Failure
[03:37:22] info: Expected: True
[03:37:22] info: Actual:   False
[03:37:22] info:    at System.Runtime.Tests.NullableMetadataTests.NullableAttributesOnPublicApiOnly(Type type)
[03:37:22] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[03:37:22] fail: [FAIL] System.Runtime.Tests.NullableMetadataTests.NullableAttributesOnPublicApiOnly(type: typeof(System.Buffers.ArrayPool<>))
[03:37:22] info: Assert.True() Failure
[03:37:22] info: Expected: True
[03:37:22] info: Actual:   False
[03:37:22] info:    at System.Runtime.Tests.NullableMetadataTests.NullableAttributesOnPublicApiOnly(Type type)
[03:37:22] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[03:37:22] fail: [FAIL] System.Runtime.Tests.NullableMetadataTests.ShimsDontHaveNullablePublicOnlyAttribute
[03:37:22] info: System.IO.FileNotFoundException :
[03:37:22] info:    at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
[03:37:22] info:    at System.Reflection.Assembly.Load(String assemblyString)
[03:37:22] info:    at System.Runtime.Tests.NullableMetadataTests.ShimsDontHaveNullablePublicOnlyAttribute()
[03:37:22] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

```
[03:38:47] fail: [FAIL] System.Tests.ActivatorTests.TestingCreateInstanceObjectHandle(assemblyName: "mscorlib", type: "System.Nullable`1[[System.Int32, mscorlib, Version"..., returnedFullNameType: "", exceptionType: null, returnNull: True)
[03:38:47] info: System.IO.FileNotFoundException :
[03:38:47] info:    at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
[03:38:47] info:    at System.Activator.CreateInstanceInternal(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
[03:38:47] info:    at System.Activator.CreateInstance(String assemblyName, String typeName)
[03:38:47] info:    at System.Tests.ActivatorTests.TestingCreateInstanceObjectHandle(String assemblyName, String type, String returnedFullNameType, Type exceptionType, Boolean returnNull)
[03:38:47] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[03:38:47] fail: [FAIL] System.Tests.ActivatorTests.TestingCreateInstanceObjectHandleFullSignature(assemblyName: "mscorlib", type: "System.Nullable`1[[System.Int32, mscorlib, Version"..., ignoreCase: True, bindingAttr: Instance | Public, binder: DefaultBinder { }, args: [], culture: , activationAttributes: null, returnedFullNameType: "", returnNull: True)
[03:38:47] info: System.IO.FileNotFoundException :
[03:38:47] info:    at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
[03:38:47] info:    at System.Activator.CreateInstanceInternal(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
[03:38:47] info:    at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
[03:38:47] info:    at System.Tests.ActivatorTests.TestingCreateInstanceObjectHandleFullSignature(String assemblyName, String type, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, String returnedFullNameType, Boolean returnNull)
[03:38:47] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[03:38:47] fail: [FAIL] System.Tests.ActivatorTests.TestingCreateInstanceObjectHandleFullSignature(assemblyName: "mscorlib", type: "SyStEm.NULLABLE`1[[System.Int32, mscorlib, Version"..., ignoreCase: True, bindingAttr: Instance | Public, binder: DefaultBinder { }, args: [], culture: , activationAttributes: null, returnedFullNameType: "", returnNull: True)
[03:38:47] info: System.IO.FileNotFoundException :
[03:38:47] info:    at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
[03:38:47] info:    at System.Activator.CreateInstanceInternal(String assemblyString, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
[03:38:47] info:    at System.Activator.CreateInstance(String assemblyName, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
[03:38:47] info:    at System.Tests.ActivatorTests.TestingCreateInstanceObjectHandleFullSignature(String assemblyName, String type, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, String returnedFullNameType, Boolean returnNull)
[03:38:47] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[03:38:47] fail: [FAIL] System.Tests.ActivatorTests.CreateInstanceT_StructWithPrivateDefaultConstructor_ThrowsMissingMethodException
[03:38:47] info: Assert.Throws() Failure
[03:38:47] info: Expected: typeof(System.MissingMethodException)
[03:38:47] info: Actual:   (No exception was thrown)
[03:38:47] info:    at System.Tests.ActivatorTests.CreateInstanceT_StructWithPrivateDefaultConstructor_ThrowsMissingMethodException()
[03:38:47] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

```
[03:38:54] fail: [FAIL] System.Reflection.Tests.ModuleTests.GetMethod_AmbiguousMatch
[03:38:54] info: Assert.Throws() Failure
[03:38:54] info: Expected: typeof(System.Reflection.AmbiguousMatchException)
[03:38:54] info: Actual:   (No exception was thrown)
[03:38:54] info:    at System.Reflection.Tests.ModuleTests.GetMethod_AmbiguousMatch()
[03:38:54] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[03:38:54] fail: [FAIL] System.Reflection.Tests.ModuleTests.GetMethod
[03:38:54] info: System.NullReferenceException : Object reference not set to an instance of an object.
[03:38:54] info:    at System.Reflection.Tests.ModuleTests.GetMethod()
[03:38:54] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[03:38:54] fail: [FAIL] System.Reflection.Tests.ModuleTests.GetMethods
[03:38:54] info: Expected: Span of length 2
[03:38:54] info: Actual: Span of length 0
[03:38:54] info:    at System.AssertExtensions.SequenceEqual[String](ReadOnlySpan`1 expected, ReadOnlySpan`1 actual)
[03:38:54] info:    at System.AssertExtensions.SequenceEqual[String](Span`1 expected, Span`1 actual)
[03:38:54] info:    at System.AssertExtensions.SequenceEqual[String](String[] expected, String[] actual)
[03:38:54] info:    at System.Reflection.Tests.ModuleTests.GetMethods()
[03:38:54] info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by MichalStrehovsky** [comment]
There are failing tests blocked on this issue, reopening. https://github.com/dotnet/runtime/pull/56859#discussion_r683050234

**Comment by lewing** [comment]
This is effectively tracking that trimming the test breaks the test now.

**Comment by MichalStrehovsky** [comment]
> This is effectively tracking that trimming the test breaks the test now.

Isn't that true for all the tests? I would expect all the tests being trimmed to 0 test cases since they're all reflection activated. The test case assemblies need to be be fully rooted. Looks like this is not happening. Test in https://github.com/dotnet/runtime/pull/56859#discussion_r683050234 would definitely be fixed with that if that was the case.

**Comment by lewing** [comment]
> > This is effectively tracking that trimming the test breaks the test now.
> 
> Isn't that true for all the tests? I would expect all the tests being trimmed to 0 test cases since they're all reflection activated. The test case assemblies need to be be fully rooted. Looks like this is not happening. Test in [#56859 (comment)](https://github.com/dotnet/runtime/pull/56859#discussion_r683050234) would definitely be fixed with that if that was the case.

I'm not sure what you are asking.  We have a build setting EnableAggressiveTrimming=true which roots the majority of the tests effectively.  We run ~60k tests on runtime main in that scenario for scenario.  The point I was was making is that this test appears to be failing because that trimming is causing issues not because  AOT is causing issues.

**Comment by MichalStrehovsky** [comment]
> I'm not sure what you are asking. We have a build setting EnableAggressiveTrimming=true which roots the majority of the tests effectively. We run ~60k tests on runtime main in that scenario for browser-wasm. The point I was was making is that this test appears to be failing because that trimming is causing issues not because AOT is causing issues.

The test called out in https://github.com/dotnet/runtime/pull/56859#discussion_r683050234 is reflecting on one of the test assemblies themselves. I would expect the target of the reflection to be rooted by whatever is rooting the test cases themselves - the test cases get reflection-activated by xunit so something must be rooting them. There's either a bug in how EnableAggressiveTrimming works (I assume we're testing the end-user scenario here that roots all user assemblies - which should include the things the test is reflecting on), how it's set up in this repo, or in IL Linker.

**Comment by lewing** [comment]
EnableAggressiveTrimming is highly imperfect but required in a practical sense for CI and mono AOT.  Please help resolving the failures, which have uncovered multiple linker bugs, instead of assuming it just works.

**Comment by ilonatommy** [comment]
All failures from the description but: `NullablePublicOnlyAttributePresent` and `NullableAttributesOnPublicApiOnly` are still failing with the same errors.
