### ISSUE TITLE
DirectoryInfo.MoveTo() throws exception in cases where the directory initially did not exist but was created in the meantime

### ISSUE THREAD

**Issue by ChristophHornung** [dotnet/runtime#52293]
Edited (for original see below):

### Description
`DirectoryInfo.MoveTo` incorrectly checks for a file-existence in case its `Exist` property is `false` instead of checking for directory-existence.

To reproduce the exception run this code: (Works on .net4.x but fails on .netCore3.1 and onwards)

```csharp
using System;
using System.IO;

namespace N
{
	public class C
	{
		public static void Main()
		{
			string root = @"D:\";
			string originalPath = Path.Join(root, "52293_original");
			string movedPath = Path.Join(root, "52293_moved");

			if (Directory.Exists(originalPath))
			{
				Console.WriteLine("Original existed. Deleting.");
				Directory.Delete(originalPath, recursive: true);
			}

			if (Directory.Exists(movedPath))
			{
				Console.WriteLine("Moved existed. Deleting.");
				Directory.Delete(movedPath, recursive: true);
			}

			var info = new DirectoryInfo(originalPath);
                       
			Console.WriteLine($"Creating original: {originalPath}");
                        // The .Exist is relevant because it forces the directory info to initialize
			Console.WriteLine("OriginalExists:" + info.Exists);
			Directory.CreateDirectory(originalPath);

                        // .Exist is false at this point -> attempt to move will fail
			Console.WriteLine("Attempting to move.");
			info.MoveTo(movedPath);

			Console.WriteLine($"Successfully moved: {movedPath}");
		}
	}
}
```

EDIT: (This was the original description - edited with the text above to reflect the discussion afterwards)
### Description

`DirectoryInfo.MoveTo` does not work on .net core 3.1 on Windows when the directory is created right before on the same `DirectoryInfo`.

I.e. this code fails on `MoveTo` when `<TargetFramework>netcoreapp3.1</TargetFramework>`:

(Both directories need to be non-existent)

```csharp
using System;
using System.Diagnostics;
using System.IO;

namespace TestDirCreateCore
{
	class Program
	{
		static void Main(string[] args)
		{
			DirectoryInfo tempDirectoryInfo = new DirectoryInfo("t:\\testdir");

			Debug.WriteLine(tempDirectoryInfo.Exists);
			tempDirectoryInfo.Create();
			Debug.WriteLine(tempDirectoryInfo.Exists);
			tempDirectoryInfo.MoveTo("t:\\testdir2");
		}
	}
}
```

with the exception:

`System.IO.DirectoryNotFoundException: 'Could not find a part of the path 't:\testdir'.'`

The same code works on .net4.7.2 and on .net5.0.

Note that on .net5.0 the second `tempDirectoryInfo.Exists` returns `true` while on .net4.7.2. it returns `false`.

Workaround: If `.Refresh()` is called before the `MoveTo()` the `Exists` property will return `true` and the move will no longer fail.

### Configuration
dotnet --info:
.NET SDK (gemäß "global.json"):
 Version:   5.0.202
 Commit:    db7cc87d51

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.202\

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14
.NET SDKs installed:
  1.0.3 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.523 [C:\Program Files\dotnet\sdk]
  2.1.600 [C:\Program Files\dotnet\sdk]
  2.1.617 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.815 [C:\Program Files\dotnet\sdk]
  3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.408 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview8.19405.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3-servicing-26724-03 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview8-28405-07 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by vcsjones** [comment]
This is because the `DirectoryInfo` has already cached that the directory does not exist when the object was constructed. Calling `Refresh` after `Create` will fix the issue:

```csharp
DirectoryInfo tempDirectoryInfo = new DirectoryInfo("D:\\testdir");

Debug.WriteLine(tempDirectoryInfo.Exists);
tempDirectoryInfo.Create();
tempDirectoryInfo.Refresh();
Debug.WriteLine(tempDirectoryInfo.Exists);
tempDirectoryInfo.MoveTo("D:\\testdir2");
```

This no longer reproduces in .NET 5 for me, it appears to have been fixed with https://github.com/dotnet/runtime/pull/34229.

**Comment by ChristophHornung** [comment]
@vcsjones I think the underlying issue is still present even in .net5.

This code works on .net4.7.2 but fails on both core3.1 and net5

```csharp
DirectoryInfo tempDirectoryInfo = new DirectoryInfo("t:\\testdir");
Debug.WriteLine(tempDirectoryInfo.Exists);
Directory.CreateDirectory("T:\\testdir");
Debug.WriteLine(tempDirectoryInfo.Exists);
tempDirectoryInfo.MoveTo("t:\\testdir2");
```

I think what is wrong here is the check that executes when `Exists` is false in the `MoveTo` method.
In the check line [here](https://github.com/dotnet/runtime/blob/d058930b2bf416635710b8b4022839a1ee1b8e6e/src/libraries/System.IO.FileSystem/src/System/IO/DirectoryInfo.cs#L220)

It reads `!FileSystem.FileExists(FullPath)` when instead it should check `!FileSystem.DirectoryExists(FullPath)`.

**Comment by ChristophHornung** [comment]
Uups, accidentally closed that by merging a PR on my own fork.

**Comment by carlossanlop** [comment]
@ChristophHornung I am unable to reproduce this issue with .NET 6.0, .NET 5.0 or with .NET Core 3.1.

I wonder if there's something different about your machine that is preventing you from creating the folder.

I ran the below code, in which I made sure to create the `DirectoryInfo` instance after ensuring the folders did not exist, then I created the folder using `Directory.CreateDirectory`, and then I moved it with `DirectoryInfo.MoveTo`:

```cs
using System;
using System.IO;

namespace N
{
    public class C
    {
        public static void Main()
        {
            string root = @"D:\";
            string originalPath = Path.Join(root, "52293_original");
            string movedPath = Path.Join(root, "52293_moved");

            if (Directory.Exists(originalPath))
            {
                Console.WriteLine("Original existed. Deleting.");
                Directory.Delete(originalPath, recursive: true);
            }

            if (Directory.Exists(movedPath))
            {
                Console.WriteLine("Moved existed. Deleting.");
                Directory.Delete(movedPath, recursive: true);
            }

            var info = new DirectoryInfo(originalPath);

            Console.WriteLine($"Creating original: {originalPath}");
            Directory.CreateDirectory(originalPath);

            Console.WriteLine("Attempting to move.");
            info.MoveTo(movedPath);

            Console.WriteLine($"Successfully moved: {movedPath}");
        }
    }
}
```

**Comment by ChristophHornung** [comment]
@carlossanlop That is because the `MoveTo` in your example happens at a point in time where the underlying information is not yet initialized, and thus an implicit `Refresh` is called. Why didn't you use the example code I provided?

Try this instead to see how checking `Exist` before creating the directory reproduces the issue:

```csharp
using System;
using System.IO;

namespace N
{
	public class C
	{
		public static void Main()
		{
			string root = @"D:\";
			string originalPath = Path.Join(root, "52293_original");
			string movedPath = Path.Join(root, "52293_moved");

			if (Directory.Exists(originalPath))
			{
				Console.WriteLine("Original existed. Deleting.");
				Directory.Delete(originalPath, recursive: true);
			}

			if (Directory.Exists(movedPath))
			{
				Console.WriteLine("Moved existed. Deleting.");
				Directory.Delete(movedPath, recursive: true);
			}

			var info = new DirectoryInfo(originalPath);

			Console.WriteLine($"Creating original: {originalPath}");
			Console.WriteLine("OriginalExists:" + info.Exists);
			Directory.CreateDirectory(originalPath);

			Console.WriteLine("Attempting to move.");
			info.MoveTo(movedPath);

			Console.WriteLine($"Successfully moved: {movedPath}");
		}
	}
}
```

**Comment by iSazonov** [comment]
With the last code I can confirm there is an exception on `info.MoveTo(movedPath);` with latest public .Net 6.0 6.0.100-preview.3.21202.5  (but code in OP works well - please update repro steps to make it simple and clear!).

**Comment by ChristophHornung** [comment]
@iSazonov What do you mean with "please update repro steps"? To edit the first comment on the issue?

**Comment by iSazonov** [comment]
> @iSazonov What do you mean with "please update repro steps"? To edit the first comment on the issue?

Yes, тow this is more misleading than showing the problem.

**Comment by carlossanlop** [comment]
> Why didn't you use the example code I provided?

@ChristophHornung  I _did_ use your example, I used the latest one you shared in [this comment](https://github.com/dotnet/runtime/issues/52293#issuecomment-832836520), in which you said it was failing in .NET 3.1 and 5.0. You said:

> I think the underlying issue is still present even in .net5.

And

> This code works on .net4.7.2 but fails on both core3.1 and net5

The only things I did was replace the `Debug.WriteLine`s with `Console.WriteLine`s, and added the delete folder logic at the beginning.

Your proposed change in the linked PR is a breaking change on several tests, on all operating systems that we do not want to introduce. This can be confirmed by [the CI results](https://github.com/dotnet/runtime/pull/52310/checks?check_run_id=2511804469), in which several FileSystem tests are failing.

Adding an `Exists`/`Refresh`, is what the user is expected to do right before moving the filesystem object, and even then, there's no guarantee that we are going to be able to move the file/folder to a new location, because there could be other processes modifying the filesystem.

You can see this issue has been reported in [other places](https://stackoverflow.com/questions/47186245/fileinfo-moveto-does-not-update-fileinfo-exists), with similar answers: Call `Refresh`.

Our documentation for `FileInfo.Exists` mentions this behavior [in the Remarks](https://docs.microsoft.com/en-us/dotnet/api/system.io.fileinfo.exists?view=net-5.0#remarks). I also noticed we do not have this same remark described in `DirectoryInfo.Exists`, and maybe it should be added. I created [an issue in dotnet-api-docs](https://github.com/dotnet/dotnet-api-docs/issues/6746) to track this request.

The updated title and description match the expected behavior, so I'm closing this.

**Comment by ChristophHornung** [comment]
@carlossanlop So the expected behavior for this API changed after .net4? (Since the code executes fine there but only fails on later version) This did crop up in a converting one of my projects to .net core 3.1 and I guess others will run into the same problem when ugprading.

It seems to me the additional `DirectoryExists` call would allow the move to go through in cases where the `DirectoryInfo` object does not have the latest information about the directory, I don't see any harm in that behavior. The tests break because after the change a `DirectoryNotFoundException` is thrown instead of the expected `IOException`. I would argue that is the more correction exception to throw here since if `Exist` is false the same kind of exception is thrown.

When this really is the expected behavior, shouldn't at least a remark also be added to the documentation of the `MoveTo` method to mention than an exception is thrown when the `DirectoryInfo` is out of sync though the directory exists in the file system? (Additionally the documentation currently does not even mention that the `DirectoryNotFoundException` is thrown when the source directory does not exists)
