### ISSUE TITLE
Massive allocations in unmanaged memory on Dictionary creation

### ISSUE THREAD

**Issue by Takoooooo** [dotnet/runtime#54688]
### Description
I wanted to use https://github.com/thecoderok/Unidecode.NET this project in my code, but I have realized it allocates a lot of memory. After some investigations, I have understood what the reason for all those allocations was this file
https://github.com/thecoderok/Unidecode.NET/blob/master/src/Unidecoder.Characters.cs
At peak, Dictionary initialization would consume ~65MB of memory(.net5,x64, Release), and ~99% of this memory is unmanaged, which is quite strange for me. For example "Hello World" console app(.net5,x64, Release) on my machine would consume ~8 MB of memory.
Steps to reproduce? Just initialize the dictionary with the data from https://github.com/thecoderok/Unidecode.NET/blob/master/src/Unidecoder.Characters.cs
### Configuration
.net5,x64,Win10
### Data
![image](https://user-images.githubusercontent.com/53405089/123290178-bd31fa80-d519-11eb-9386-dbaff37d3453.png)
(With dictionary initialization)
![image](https://user-images.githubusercontent.com/53405089/123290291-cf139d80-d519-11eb-81e2-0cbd37463e8b.png)
Just "hello world" app to compare.

### Analysis
From dotMemory, I can see what when the app just starts it starts to allocate memory to the heap(prb initializing dictionary) and also starts to massively allocate unmanaged memory. When the allocation to the heap ends some unmanaged memory is also being cleared and stabilizes on 30MB.

**Comment by huoyaoyuan** [comment]
It seems that diagnostics tools show string content as unmanaged memory.
However, the type has ~1.5K strings. Certainly a string shouldn't consume 30KB memory.

**Comment by GrabYourPitchforks** [comment]
I temporarily pathed this to the VM because those folks probably have the best awareness of what might be reporting this. Or at least can route it appropriately. :)

**Comment by jkotas** [comment]
The dictionary initialization method in the library is huge. The JITed code for it is about 1.5MB. 

The unmanaged memory allocation that you are seeing is coming from the JIT. The JIT needs the unmanaged memory to create intermediate representation of the method. It is expected that the intermediate representation for 1.5MB method is going to take 10s MB.

Large auto-generated collection initializers are known source of bad performance and crashes. See for example: https://github.com/dotnet/runtime/issues/8980.

You should open an issue against the library instead. The library should be fixed to use data-driven approach for initializing the Dictionary instead.

**Comment by jkotas** [comment]
Looks like there is an issue on this already: https://github.com/thecoderok/Unidecode.NET/issues/14

**Comment by Takoooooo** [comment]
> The dictionary initialization method in the library is huge. The JITed code for it is about 1.5MB.
> 
> The unmanaged memory allocation that you are seeing is coming from the JIT. The JIT needs the unmanaged memory to create intermediate representation of the method. It is expected that the intermediate representation for 1.5MB method is going to take 10s MB.
> 
> Large auto-generated collection initializers are known source of bad performance and crashes. See for example: #8980.
> 
> You should open an issue against the library instead. The library should be fixed to use data-driven approach for initialization of the Dictionary.

I`m sorry, but what do you mean by the "data-driven approach for initialization of the Dictionary"?

**Comment by huoyaoyuan** [comment]
Store the corresponding data in embedded binary file, **primitive** array initializer, or `ReadOnlySpan<byte>` that backed by a constant array. Then use a loop to convert the data into dictionary.

**Comment by Takoooooo** [comment]
> Store the corresponding data in embedded binary file, **primitive** array of constants, or `ReadOnlySpan<byte>` that backed by a constant array. Then use a loop to convert the data into dictionary.

I tried making one array of integers and a jagged array of strings, but it doesn't really solve the issue and to add them in for loop to the dictionary.Still~65MB

**Comment by huoyaoyuan** [comment]
>  a jagged array of strings

This is still codeful. String is not considered primitive in this case.
