### ISSUE TITLE
[WASM][AOT] Assertion at /__w/1/s/src/mono/mono/metadata/class.c:2006, condition `<disabled>' not met

### ISSUE THREAD

**Issue by chingham** [dotnet/runtime#59471]
### Description

We're testing .NET 6 RC 1 and run into an issue using AOT compilation
Compilation runs without any error, but when testing the published app, we have this error on startup:

```Assertion at /__w/1/s/src/mono/mono/metadata/class.c:2006, condition `<disabled>' not met```

### Configuration

dotnet --version: `6.0.100-rc.1.21463.6`
OS: `Windows 10 x64`
Browser: `Edge, Chrome`

### Other information

If we disable `RunAOTCompilation` in the csproj file, everything works just fine
This is on a business app that is quite large, and I unfortunately cannot provide a test project on this

Here is the complete error in web console:

```
dotnet.6.0.0-rc.1.21451.13.js:1 * Assertion at /__w/1/s/src/mono/mono/metadata/class.c:2006, condition `<disabled>' not met

11592426 @ dotnet.6.0.0-rc.1.21451.13.js:1
_emscripten_asm_const_int @ dotnet.6.0.0-rc.1.21451.13.js:1
$func37118 @ 102dff72:0x148e358
$func49249 @ 102dff72:0x14e466b
$func15290 @ 102dff72:0x8b0fe8
$func1551 @ 102dff72:0xe3966
$func670 @ 102dff72:0xa0b80
$func156 @ 102dff72:0x872a7
$func2594 @ 102dff72:0x14ab31
$func4359 @ 102dff72:0x2108c7
$func16026 @ 102dff72:0x8ddc96
$func5214 @ 102dff72:0x294454
$func16076 @ 102dff72:0x8e7699
$func6763 @ 102dff72:0x36ba86
$func839 @ 102dff72:0xac2fe
$func49108 @ 102dff72:0x14dbeb9
$func355 @ 102dff72:0x8f26d
$func24226 @ 102dff72:0xda4cf9
$func68533 @ 102dff72:0x1c89456
$func68403 @ 102dff72:0x1c78382
$func113815 @ 102dff72:0x355b840
$func112171 @ 102dff72:0x3436ac2
$func15937 @ 102dff72:0x8d2035
invoke_vi @ dotnet.6.0.0-rc.1.21451.13.js:1
$func15555 @ 102dff72:0x8bd053
$func16081 @ 102dff72:0x8e8282
$func6763 @ 102dff72:0x360a4a
$func839 @ 102dff72:0xac2fe
$func49090 @ 102dff72:0x14db8d8
$func363 @ 102dff72:0x8f8ba
$func112355 @ 102dff72:0x34cee7d
$func114005 @ 102dff72:0x357981d
$func103373 @ 102dff72:0x2f23876
$func556 @ 102dff72:0x9798f
$func15937 @ 102dff72:0x8d201d
invoke_vi @ dotnet.6.0.0-rc.1.21451.13.js:1
$func15555 @ 102dff72:0x8bd053
$func16081 @ 102dff72:0x8e8282
$func6763 @ 102dff72:0x360a4a
$func839 @ 102dff72:0xac2fe
$func49100 @ 102dff72:0x14dbbfd
$func601 @ 102dff72:0x9b195
$func33717 @ 102dff72:0x12906c7
$func33745 @ 102dff72:0x129321f
$func103256 @ 102dff72:0x2f11b85
$func2766 @ 102dff72:0x15aa09
$func15937 @ 102dff72:0x8d2052
invoke_vi @ dotnet.6.0.0-rc.1.21451.13.js:1
$func15555 @ 102dff72:0x8bd053
$func16081 @ 102dff72:0x8e8282
$func6763 @ 102dff72:0x360b8b
$func839 @ 102dff72:0xac2fe
$func49109 @ 102dff72:0x14dbef1
$func368 @ 102dff72:0x8f9d3
$func33743 @ 102dff72:0x1291fbf
$func103253 @ 102dff72:0x2f10d91
$func102243 @ 102dff72:0x2e90636
$func33755 @ 102dff72:0x12958ee
$func33804 @ 102dff72:0x129f81c
$func554 @ 102dff72:0x9792c
$func15937 @ 102dff72:0x8d201d
invoke_vi @ dotnet.6.0.0-rc.1.21451.13.js:1
$func15555 @ 102dff72:0x8bd053
$func16081 @ 102dff72:0x8e8282
$func6763 @ 102dff72:0x360b8b
$func839 @ 102dff72:0xac2fe
$func49109 @ 102dff72:0x14dbef1
$func368 @ 102dff72:0x8f9d3
$func6292 @ 102dff72:0x33b7de
$func33847 @ 102dff72:0x12a78b2
$func556 @ 102dff72:0x9798f
$func15937 @ 102dff72:0x8d201d
invoke_vi @ dotnet.6.0.0-rc.1.21451.13.js:1
$func15555 @ 102dff72:0x8bd053
$func16081 @ 102dff72:0x8e8282
$func6763 @ 102dff72:0x360b8b
$func839 @ 102dff72:0xac2fe
$func49090 @ 102dff72:0x14db8d8
$func363 @ 102dff72:0x8f8ba
$func102356 @ 102dff72:0x2e99661
$func33846 @ 102dff72:0x12a7603
$func103368 @ 102dff72:0x2f2337f
$func8720 @ 102dff72:0x4ada53
$func15937 @ 102dff72:0x8d2035
invoke_vi @ dotnet.6.0.0-rc.1.21451.13.js:1
$func15555 @ 102dff72:0x8bd053
$func16081 @ 102dff72:0x8e8282
$func6763 @ 102dff72:0x360a4a
$func839 @ 102dff72:0xac2fe
$func49108 @ 102dff72:0x14dbeb9
$func252 @ 102dff72:0x8a71b
$func33714 @ 102dff72:0x12902fc
$func13822 @ 102dff72:0x7ffa84
$func2764 @ 102dff72:0x15a946
$func15937 @ 102dff72:0x8d201d
invoke_vi @ dotnet.6.0.0-rc.1.21451.13.js:1
$func15555 @ 102dff72:0x8bd053
$func16081 @ 102dff72:0x8e8282
$func6763 @ 102dff72:0x360b8b
$func839 @ 102dff72:0xac2fe
$func49090 @ 102dff72:0x14db8d8
$func363 @ 102dff72:0x8f8ba
$func102351 @ 102dff72:0x2e9949f
$func103250 @ 102dff72:0x2f108e6
$func102250 @ 102dff72:0x2e90ef2
$func101468 @ 102dff72:0x2e3d321
$func15937 @ 102dff72:0x8d2074
invoke_vi @ dotnet.6.0.0-rc.1.21451.13.js:1
$func15555 @ 102dff72:0x8bd053
$func16081 @ 102dff72:0x8e8282
$func6763 @ 102dff72:0x360b8b
$func839 @ 102dff72:0xac2fe
$func49090 @ 102dff72:0x14db8d8
$func363 @ 102dff72:0x8f8ba
$func101587 @ 102dff72:0x2e4c815
$func33497 @ 102dff72:0x127c0b4
$func102262 @ 102dff72:0x2e915fa
$func556 @ 102dff72:0x9798f
$func15937 @ 102dff72:0x8d201d
invoke_vi @ dotnet.6.0.0-rc.1.21451.13.js:1
$func15555 @ 102dff72:0x8bd053
$func16081 @ 102dff72:0x8e8282
$func6763 @ 102dff72:0x360b8b
$func839 @ 102dff72:0xac2fe
$func49090 @ 102dff72:0x14db8d8
$func363 @ 102dff72:0x8f8ba
$func112345 @ 102dff72:0x34ceaef
$func36434 @ 102dff72:0x142d0cf
$func614 @ 102dff72:0x9ba6e
$func15937 @ 102dff72:0x8d201d
invoke_vi @ dotnet.6.0.0-rc.1.21451.13.js:1
$func15555 @ 102dff72:0x8bd053
$func16081 @ 102dff72:0x8e8282
$func6763 @ 102dff72:0x360b8b
$func49054 @ 102dff72:0x14daae6
$func48783 @ 102dff72:0x14d34f0
$func9528 @ 102dff72:0x513945
$func2156 @ 102dff72:0x11d758
$kd @ 102dff72:0x14d1283
Module._mono_wasm_invoke_method @ dotnet.6.0.0-rc.1.21451.13.js:1
_call_method_with_converted_args @ dotnet.6.0.0-rc.1.21451.13.js:1
call_method @ dotnet.6.0.0-rc.1.21451.13.js:1
(anonymous) @ dotnet.6.0.0-rc.1.21451.13.js:1
call_assembly_entry_point @ dotnet.6.0.0-rc.1.21451.13.js:1
callEntryPoint @ blazor.webassembly.js:1
Ct @ blazor.webassembly.js:1
async function (async)
Ct @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
```

Anyway, thank you for your incredible work on .NET !

**Comment by radical** [comment]
cc @vargaz

**Comment by lambdageek** [comment]
@vargaz this is in `mono_method_get_vtable_slot` in the generic instance case.

When would a `MonoMethod` not be in `method->klass->method` array?  Maybe if it's a dynamic method on a generic instance?  Is that possible?

(Not sure why it only asserts with AOT compilation - maybe it's some fallback path in the interpreter)

**Comment by vargaz** [comment]
We would need some kind of testcase to track this down.

**Comment by lewing** [comment]
@chingham do you have a sample project we can use to reproduce this error?

**Comment by vargaz** [comment]
Would it be possible to build the app with <WasmNativeStrip>false</WasmNativeStrip> to get a better
native stack trace ?

**Comment by chingham** [comment]
Oh ! Didn't know of this property, the stack trace is way more clear
Here it is:

```
_emscripten_asm_const_int	@	dotnet.6.0.0-rc.1.21451.13.js:5305
$wasm_trace_logger	@	dotnet.wasm:0x3c1a41f
$eglib_log_adapter	@	dotnet.wasm:0x3bb6edf
$monoeg_g_logstr	@	dotnet.wasm:0x3bfd360
$monoeg_g_logv_nofree	@	dotnet.wasm:0x3bfd30f
$monoeg_assertion_message	@	dotnet.wasm:0x3bfd3df
$mono_assertion_message	@	dotnet.wasm:0x3bfd426
$mono_assertion_message_disabled	@	dotnet.wasm:0x3bfd3f7
$mono_method_get_vtable_slot	@	dotnet.wasm:0x3b56bb9
$interp_transform_call	@	dotnet.wasm:0x3b3b8a3
$generate_code	@	dotnet.wasm:0x3b345f4
$generate	@	dotnet.wasm:0x3b3d979
$mono_interp_transform_method	@	dotnet.wasm:0x3b3d5d1
$do_transform_method	@	dotnet.wasm:0x3b2d6a1
$interp_exec_method	@	dotnet.wasm:0x3b2c052
$interp_entry	@	dotnet.wasm:0x3b2d532
$interp_entry_instance_1	@	dotnet.wasm:0x3b2f2d0
$corlib_aot_wrapper_gsharedvt_in_sig_void_this_obj	@	dotnet.wasm:0x3aa39be
$System_Linq_System_Collections_Generic_LargeArrayBuilder_1_T_REF_AddRange_System_Collections_Generic_IEnumerable_1_T_REF	@	dotnet.wasm:0x29c8e9c
$System_Linq_System_Collections_Generic_EnumerableHelpers_ToArray_T_REF_System_Collections_Generic_IEnumerable_1_T_REF	@	dotnet.wasm:0x29c9aa4
$System_Linq_System_Linq_Enumerable_ToArray_TSource_REF_System_Collections_Generic_IEnumerable_1_TSource_REF	@	dotnet.wasm:0x29cd42e
***Our App***	@	dotnet.wasm:0x1b8624d
***Our App***	@	dotnet.wasm:0x1c6e110
$jit_call_cb	@	dotnet.wasm:0x3b2edfb
invoke_vi	@	dotnet.6.0.0-rc.1.21451.13.js:10787
$mono_llvm_cpp_catch_exception	@	dotnet.wasm:0x3bf7a6b
$do_jit_call	@	dotnet.wasm:0x3b2df81
$interp_exec_method	@	dotnet.wasm:0x3b20fe4
$interp_entry	@	dotnet.wasm:0x3b2d532
$interp_entry_static_1	@	dotnet.wasm:0x3b2f8bc
$corlib_aot_wrapper_gsharedvt_in_sig_void_bii	@	dotnet.wasm:0x3ac7be3
***Our App***__OnAfterRenderAsyncd__7_	@	dotnet.wasm:0x1c59460
***Our App***_OnAfterRenderAsync_bool	@	dotnet.wasm:0x1b4703d
$Microsoft_AspNetCore_Components_Microsoft_AspNetCore_Components_ComponentBase_Microsoft_AspNetCore_Components_IHandleAfterRender_OnAfterRenderAsync	@	dotnet.wasm:0x57b67e
$corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_	@	dotnet.wasm:0x3a9d47c
$jit_call_cb	@	dotnet.wasm:0x3b2ede3
invoke_vi	@	dotnet.6.0.0-rc.1.21451.13.js:10787
$mono_llvm_cpp_catch_exception	@	dotnet.wasm:0x3bf7a6b
$do_jit_call	@	dotnet.wasm:0x3b2df81
$interp_exec_method	@	dotnet.wasm:0x3b20fe4
$interp_entry	@	dotnet.wasm:0x3b2d532
$interp_entry_instance_ret_0	@	dotnet.wasm:0x3b2f58d
$corlib_aot_wrapper_gsharedvt_in_sig_obj_this_	@	dotnet.wasm:0x3aa40fd
$Microsoft_AspNetCore_Components_Microsoft_AspNetCore_Components_Rendering_ComponentState_NotifyRenderCompletedAsync	@	dotnet.wasm:0x58ceef
$Microsoft_AspNetCore_Components_Microsoft_AspNetCore_Components_RenderTree_Renderer_NotifyRenderCompleted_Microsoft_AspNetCore_Components_Rendering_ComponentState_System_Collections_Generic_List_1_System_Threading_Tasks_Task_	@	dotnet.wasm:0x58c946
$Microsoft_AspNetCore_Components_Microsoft_AspNetCore_Components_RenderTree_Renderer_InvokeRenderCompletedCalls_Microsoft_AspNetCore_Components_RenderTree_ArrayRange_1_Microsoft_AspNetCore_Components_RenderTree_RenderTreeDiff_System_Threading_Tasks_Task	@	dotnet.wasm:0x58c679
$Microsoft_Extensions_Logging_Abstractions_aot_wrapper_gsharedvt_out_sig_obj_this_cl26_Mono_dValueTuple_602_3cint_2c_20int_3e_obj	@	dotnet.wasm:0x800829
$jit_call_cb	@	dotnet.wasm:0x3b2ee18
invoke_vi	@	dotnet.6.0.0-rc.1.21451.13.js:10787
$mono_llvm_cpp_catch_exception	@	dotnet.wasm:0x3bf7a6b
$do_jit_call	@	dotnet.wasm:0x3b2df81
$interp_exec_method	@	dotnet.wasm:0x3b2112d
$interp_entry	@	dotnet.wasm:0x3b2d532
$interp_entry_instance_0	@	dotnet.wasm:0x3b2f290
$corlib_aot_wrapper_gsharedvt_in_sig_void_this_	@	dotnet.wasm:0x3aa34e9
$Microsoft_AspNetCore_Components_Microsoft_AspNetCore_Components_RenderTree_Renderer_ProcessRenderQueue	@	dotnet.wasm:0x58c026
$Microsoft_AspNetCore_Components_Microsoft_AspNetCore_Components_RenderTree_Renderer_ProcessPendingRender	@	dotnet.wasm:0x58bfb9
$Microsoft_AspNetCore_Components_WebAssembly_Microsoft_AspNetCore_Components_WebAssembly_Rendering_WebAssemblyRenderer_ProcessPendingRender	@	dotnet.wasm:0x69666b
$Microsoft_AspNetCore_Components_Microsoft_AspNetCore_Components_RenderTree_Renderer_AddToRenderQueue_int_Microsoft_AspNetCore_Components_RenderFragment	@	dotnet.wasm:0x584be8
$Microsoft_AspNetCore_Components_Microsoft_AspNetCore_Components_RenderHandle_Render_Microsoft_AspNetCore_Components_RenderFragment	@	dotnet.wasm:0x584857
$corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_void_this_obj	@	dotnet.wasm:0x3a9dc23
$jit_call_cb	@	dotnet.wasm:0x3b2ede3
invoke_vi	@	dotnet.6.0.0-rc.1.21451.13.js:10787
$mono_llvm_cpp_catch_exception	@	dotnet.wasm:0x3bf7a6b
$do_jit_call	@	dotnet.wasm:0x3b2df81
$interp_exec_method	@	dotnet.wasm:0x3b2112d
$interp_entry	@	dotnet.wasm:0x3b2d532
$interp_entry_instance_0	@	dotnet.wasm:0x3b2f290
$corlib_aot_wrapper_gsharedvt_in_sig_void_this_	@	dotnet.wasm:0x3aa34e9
$Microsoft_AspNetCore_Components_Microsoft_AspNetCore_Components_ComponentBase_StateHasChanged	@	dotnet.wasm:0x57a7d1
$Microsoft_AspNetCore_Components_Microsoft_AspNetCore_Components_ComponentBase_CallOnParametersSetAsync	@	dotnet.wasm:0x57b0a8
$corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_	@	dotnet.wasm:0x3a9d47c
$jit_call_cb	@	dotnet.wasm:0x3b2ede3
invoke_vi	@	dotnet.6.0.0-rc.1.21451.13.js:10787
$mono_llvm_cpp_catch_exception	@	dotnet.wasm:0x3bf7a6b
$do_jit_call	@	dotnet.wasm:0x3b2df81
$interp_exec_method	@	dotnet.wasm:0x3b2112d
$interp_entry	@	dotnet.wasm:0x3b2d532
$interp_entry_static_1	@	dotnet.wasm:0x3b2f8bc
$corlib_aot_wrapper_gsharedvt_in_sig_void_bii	@	dotnet.wasm:0x3ac7be3
$Microsoft_AspNetCore_Components_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Microsoft_AspNetCore_Components_ComponentBase__RunInitAndSetParametersAsyncd__20_Microsoft_AspNetCore_Components_ComponentBase__RunInitAndSetParametersAsyncd__20_	@	dotnet.wasm:0x632725
$Microsoft_AspNetCore_Components_Microsoft_AspNetCore_Components_ComponentBase_RunInitAndSetParametersAsync	@	dotnet.wasm:0x57ade5
$Microsoft_AspNetCore_Components_Microsoft_AspNetCore_Components_ComponentBase_SetParametersAsync_Microsoft_AspNetCore_Components_ParameterView	@	dotnet.wasm:0x57ac6f
$Microsoft_AspNetCore_Components_aot_wrapper_gsharedvt_out_sig_obj_this_cl41_Mono_dValueTuple_605_3cint_2c_20int_2c_20int_2c_20int_2c_20int_3e_	@	dotnet.wasm:0x6326b4
$jit_call_cb	@	dotnet.wasm:0x3b2edfb
invoke_vi	@	dotnet.6.0.0-rc.1.21451.13.js:10787
$mono_llvm_cpp_catch_exception	@	dotnet.wasm:0x3bf7a6b
$do_jit_call	@	dotnet.wasm:0x3b2df81
$interp_exec_method	@	dotnet.wasm:0x3b20fe4
$interp_entry	@	dotnet.wasm:0x3b2d532
$interp_entry_instance_1	@	dotnet.wasm:0x3b2f2d0
$Microsoft_AspNetCore_Components_aot_wrapper_gsharedvt_in_sig_void_this_cl41_Mono_dValueTuple_605_3cint_2c_20int_2c_20int_2c_20int_2c_20int_3e_	@	dotnet.wasm:0x63b509
$Microsoft_AspNetCore_Components_Microsoft_AspNetCore_Components_Rendering_ComponentState_SupplyCombinedParameters_Microsoft_AspNetCore_Components_ParameterView	@	dotnet.wasm:0x5a347f
$Microsoft_AspNetCore_Components_Microsoft_AspNetCore_Components_Rendering_ComponentState_SetDirectParameters_Microsoft_AspNetCore_Components_ParameterView	@	dotnet.wasm:0x59806b
$Ingham_Rendering_aot_wrapper_gsharedvt_out_sig_void_this_cl41_Mono_dValueTuple_605_3cint_2c_20int_2c_20int_2c_20int_2c_20int_3e_	@	dotnet.wasm:0x1363d81
$jit_call_cb	@	dotnet.wasm:0x3b2ede3
invoke_vi	@	dotnet.6.0.0-rc.1.21451.13.js:10787
$mono_llvm_cpp_catch_exception	@	dotnet.wasm:0x3bf7a6b
$do_jit_call	@	dotnet.wasm:0x3b2df81
$interp_exec_method	@	dotnet.wasm:0x3b2112d
$interp_entry	@	dotnet.wasm:0x3b2d532
$interp_entry_static_1	@	dotnet.wasm:0x3b2f8bc
$corlib_aot_wrapper_gsharedvt_in_sig_void_bii	@	dotnet.wasm:0x3ac7be3
$Microsoft_AspNetCore_Components_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Microsoft_AspNetCore_Components_RenderTree_Renderer__RenderRootComponentAsyncd__39_Microsoft_AspNetCore_Components_RenderTree_Renderer__RenderRootComponentAsyncd__39_	@	dotnet.wasm:0x634023
$Microsoft_AspNetCore_Components_Microsoft_AspNetCore_Components_RenderTree_Renderer_RenderRootComponentAsync_int_Microsoft_AspNetCore_Components_ParameterView	@	dotnet.wasm:0x588b14
$Microsoft_AspNetCore_Components_WebAssembly_Microsoft_AspNetCore_Components_WebAssembly_Rendering_WebAssemblyRenderer_AddComponentAsync_System_Type_Microsoft_AspNetCore_Components_ParameterView_string	@	dotnet.wasm:0x696267
$Microsoft_AspNetCore_Components_WebAssembly_aot_wrapper_gsharedvt_out_sig_obj_this_objcl41_Mono_dValueTuple_605_3cint_2c_20int_2c_20int_2c_20int_2c_20int_3e_obj	@	dotnet.wasm:0x6f89ee
$jit_call_cb	@	dotnet.wasm:0x3b2ee3a
invoke_vi	@	dotnet.6.0.0-rc.1.21451.13.js:10787
$mono_llvm_cpp_catch_exception	@	dotnet.wasm:0x3bf7a6b
$do_jit_call	@	dotnet.wasm:0x3b2df81
$interp_exec_method	@	dotnet.wasm:0x3b2112d
$interp_entry	@	dotnet.wasm:0x3b2d532
$interp_entry_static_1	@	dotnet.wasm:0x3b2f8bc
$corlib_aot_wrapper_gsharedvt_in_sig_void_bii	@	dotnet.wasm:0x3ac7be3
$Microsoft_AspNetCore_Components_WebAssembly_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Microsoft_AspNetCore_Components_WebAssembly_Hosting_WebAssemblyHost__RunAsyncCored__15_Microsoft_AspNetCore_Components_WebAssembly_Hosting_WebAssemblyHost__RunAsyncCored__15_	@	dotnet.wasm:0x6fcc0f
$Microsoft_AspNetCore_Components_WebAssembly_Microsoft_AspNetCore_Components_WebAssembly_Hosting_WebAssemblyHost_RunAsyncCore_System_Threading_CancellationToken_Microsoft_AspNetCore_Components_WebAssembly_Hosting_WebAssemblyCultureProvider	@	dotnet.wasm:0x699f06
$Microsoft_AspNetCore_Components_WebAssembly_Microsoft_AspNetCore_Components_WebAssembly_Hosting_WebAssemblyHost_RunAsync	@	dotnet.wasm:0x699ddf
$corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_	@	dotnet.wasm:0x3a9d47c
$jit_call_cb	@	dotnet.wasm:0x3b2ede3
invoke_vi	@	dotnet.6.0.0-rc.1.21451.13.js:10787
$mono_llvm_cpp_catch_exception	@	dotnet.wasm:0x3bf7a6b
$do_jit_call	@	dotnet.wasm:0x3b2df81
$interp_exec_method	@	dotnet.wasm:0x3b2112d
$interp_entry	@	dotnet.wasm:0x3b2d532
$interp_entry_static_1	@	dotnet.wasm:0x3b2f8bc
$corlib_aot_wrapper_gsharedvt_in_sig_void_bii	@	dotnet.wasm:0x3ac7be3
***Our App***_Program__Maind__0_	@	dotnet.wasm:0x1c59171
***Our App***_Program_Main_string__	@	dotnet.wasm:0x1b45f74
$corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_obj	@	dotnet.wasm:0x3a9d3c8
$jit_call_cb	@	dotnet.wasm:0x3b2ede3
invoke_vi	@	dotnet.6.0.0-rc.1.21451.13.js:10787
$mono_llvm_cpp_catch_exception	@	dotnet.wasm:0x3bf7a6b
$do_jit_call	@	dotnet.wasm:0x3b2df81
$interp_exec_method	@	dotnet.wasm:0x3b2112d
$interp_runtime_invoke	@	dotnet.wasm:0x3b1fcec
$mono_jit_runtime_invoke	@	dotnet.wasm:0x3bd712b
$do_runtime_invoke	@	dotnet.wasm:0x3b8fcf9
$mono_runtime_try_invoke	@	dotnet.wasm:0x3b9034d
$mono_runtime_invoke	@	dotnet.wasm:0x3b9250c
$mono_wasm_invoke_method	@	dotnet.wasm:0x3c19c28
Module._mono_wasm_invoke_method	@	dotnet.6.0.0-rc.1.21451.13.js:9949
_call_method_with_converted_args	@	dotnet.6.0.0-rc.1.21451.13.js:8176
call_method	@	dotnet.6.0.0-rc.1.21451.13.js:8136
(anonymous)	@	dotnet.6.0.0-rc.1.21451.13.js:8372
call_assembly_entry_point	@	dotnet.6.0.0-rc.1.21451.13.js:8379
callEntryPoint	@	blazor.webassembly.js:1
Ct	@	blazor.webassembly.js:1
async function (async)		
Ct	@	blazor.webassembly.js:1
(anonymous)	@	blazor.webassembly.js:1
(anonymous)
```

This also gives us a hint to what method is causing this, we will try to modify some things in our code to see if we can make it to work

**Comment by chingham** [comment]
Interesting note: I really don't understand:
If, at the very beginning of the "App.OnAfterRender", I add these few lines of codes (that litterally do nothing useful, it was just a test):

```
var array1 = new int[] { 1, 2, 3, 4, 5, 6 };
var array2 = new int[] { 7, 8, 9, 10 };
js.Invoke<int>("test", new {
     foo = array1.Select(x => new {
        x = x,
        y = 1,
        z = array2.Select(y => new {
            w = y
        })
    }).ToArray()
});
```

The error disappear... And the app runs normally
If I remove this code, the error comes back

**Comment by yowl** [comment]
I can reproduce this with code from https://github.com/dotnet/runtimelab/blob/feature/NativeAOT-LLVM/src/tests/nativeaot/SmokeTests/HelloWasm/HelloWasm.cs.  In particular this method:
```
        private static void TestExceptionInGvmCall()
        {
            StartTest("TestExceptionInGvmCall");

            var shouldBeFalse = CatchGvmThrownException(new GenBase<string>(), (string)null);
            var shouldBeTrue = CatchGvmThrownException(new DerivedThrows<string>(), (string)null);

            EndTest(shouldBeTrue && !shouldBeFalse);
        }
```
WHere the other relevant parts are:
```
        class DerivedThrows<A> : GenBase<A>
        {
            public override string GMethod1<T>(T t1, T t2) { throw new Exception("ToStringThrows"); }
        }

        private static bool CatchGvmThrownException<T>(GenBase<T> g, T p)
        {
            try
            {
                var i = 1;
                if (i == 1)
                {
                    g.GMethod1(p, p);
                }
            }
            catch (Exception e)
            {
                return e.Message == "ToStringThrows"; // also testing here that we can return a value out of a catch
            }
            return false;
        }

        class GenBase<A>
        {
            public virtual string GMethod1<T>(T t1, T t2) { return "GenBase<" + typeof(A) + ">.GMethod1<" + typeof(T) + ">(" + t1 + "," + t2 + ")"; }
        }
```

**Comment by lambdageek** [comment]
Spent some time trying to reproduce the crash using the sample from https://github.com/dotnet/runtime/issues/59471#issuecomment-1075351910 on desktop using `--aot=llvmonly,interp` for compilation and `--llvmonly-interp` for running.  Tried commits before and after 783e260c78f.  So far haven't been able to get it to crash.

it might be wasm specific, or else I didn't pick quite the right AOT settings.  In any case, I'll try with a wasm runtime next week.

**Comment by vargaz** [comment]
Its also possible that this issue has been fixed since net6.

**Comment by lambdageek** [comment]
Tried to repro in a barebones browser sample between `main` and 44b1cd68414; also tried in a blazor sample with net7.0-preview2 and with net6 (6.0.2).
I'm doing `<RunAOTCompilation>true</RunAOTCompilation>`, `<WasmNativeStrip>false</WasmNativeStrip>` and `Release` configuration.

In all cases, the sample runs and gives the expected answer. no crash.

Not sure what else I might be missing.

**Comment by yowl** [comment]
[BlazorApp1.zip](https://github.com/dotnet/runtime/files/8366073/BlazorApp1.zip)
This is my project (running with 6.0.3)  In `Counter.razor.cs` at line 1971 you can see the lines I have problems with (commented out in the zip).  Does this help?

**Comment by lambdageek** [comment]
> [BlazorApp1.zip](https://github.com/dotnet/runtime/files/8366073/BlazorApp1.zip) This is my project (running with 6.0.3) In `Counter.razor.cs` at line 1971 you can see the lines I have problems with (commented out in the zip). Does this help?

That's helpful, thanks. I still don't get a crash.  (Uncommented the lines; and `dotnet publish -c Release -p:RunAOTCompilation=true` and then serve the publish/wwwroot directory)

**Comment by yowl** [comment]
Sorry, but I can't repro it either today.  Maybe I didn't have a clean build before or something....

**Comment by lewing** [comment]
Is this still an active issue?
