### ISSUE TITLE
m_UnresolvedClassLock is held in an unsafe way for Func Evals

### ISSUE THREAD

**Issue by auott** [dotnet/runtime#60565]
### Description

m_UnresolvedClassLock can be held when an application is in break state. If a func eval triggers an assembly load while that lock is held on another thread the func eval must be aborted. 

### Reproduction Steps

See the following VS feedback ticket: https://developercommunity.visualstudio.com/t/VS2022-preview-41---debugger-message-T/1548980.

### Expected behavior

A func eval should be able to load an assembly without encountering the effective deadlock with m_unresolvedClassLock.

### Actual behavior

Func evals can effectively deadlock and the application ends up in a bad state.

**Comment by thejman1989** [comment]
Is there any idea on a fix? As this has been stale for some time now

**Comment by schwarzr** [comment]
Looks like this is related to the hot reload feature. For me the error disappeared after disabling hot reload...

**Comment by NoahStahl** [comment]
Same, this behavior ceases for me when hot reload is disabled. Nice find @schwarzr ! Pretty consistent when enabled, even in simple .NET 6 console app. Using latest VS 2022.

**Comment by sec** [comment]
Also getting this - was this fixed in 6.0.1 by any chance? This bug makes Hot Reload (and also Edit and Continue) pretty useless (or annoying at least)...

**Comment by EgorBo** [comment]
I hit it quite often 😢

**Comment by deeprobin** [comment]
> I hit it quite often 😢

Unfortunately, I have also had this experience 😢.

**Comment by EgorBo** [comment]
If JetBrains Resharper is installed - it tries to show all locals automatically inside the editor during debug break, so this issue is reproduced with every second run, when I disabled that feature in Resharper - it gone away.

**Comment by thejman1989** [comment]
> 

For me it happens without ReSharper installed. I'm happy it resolved the issue for you, but I'm still experiencing it, which made me switch back to .Net 5

**Comment by alexhelms** [comment]
Any update on this? I've been running into this constantly. If I turn off hot reload I no longer have the issue but hot reload/edit and continue are pretty essential.

**Comment by JKamsker** [comment]
> Any update on this? I've been running into this constantly. If I turn off hot reload I no longer have the issue but hot reload/edit and continue are pretty essential.

Same here. Resharper isnt installed aswell.

**Comment by marxxxx** [comment]
Same here. This is quite annoying. I turned off hot reload and Edit&Continue as this feature wasn't working properly (at least with Blazor Server) anyway.

**Comment by danmoseley** [comment]
@noahfalk to see updates above.

**Comment by noahfalk** [comment]
@tommcdon @davmason

**Comment by nicklasjepsen** [comment]
Console app, debug mode with break point. Get the error on the first line of execution after stepping over (F10). Disabling "Edit and continue hot reload" makes the error go away.

**Comment by tommcdon** [comment]
Thanks for sharing that this issue reproduces with console apps and a workaround @nicklasjepsen.  This should help us construct a repro to help us understand and develop potential fixes for it.

**Comment by noahfalk** [comment]
Some research into the m_UnresolvedClassLock suggests that this specific cause of the issue was probably resolved when [this code](https://github.com/dotnet/runtime/commit/5da8f31789e21fa90b30e539f47f087f6de46230#diff-2e6d1f272282cd51c68e93dd38f76bd94bb903656b80e822027fb072fad24094L1074) was changed early in .NET 7. This doesn't guarantee that all causes of the issue are resolved, or that everyone observing that func-eval abort message was hitting this specific cause, but it should at least mean the situation is improved in .NET 7. Has anyone reproducing the issue on .NET 6 been able to try a .NET 7 preview build to see if the issue is resolved for you? If you can still reproduce it on a .NET 7 preview I'd love to get some dumps from you to try and diagnose any additional variations of this problem.

I tried reproducing the problem as described by @nicklasjepsen but I wasn't able to observe any issue. Here is what I did specifically in case anyone has an alternate suggestion of what I should try?
1. Launch Visual Studio 2022 (v17.2.5)
2. Create a new Console app project targetting NET 6.0 using the default top level statements. This creates the standard two line Program.cs:
```C#
// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
```
3. I set a breakpoint on line 2
4. I hit F5 with the hot reload settings still in their default on configuration and the project in the default Debug configuration
5. After hitting the breakpoint at line 2 I used F10 to step over
The step completed as expected, no errors shown.

I also tried variations where I made edits before hitting F10, did multiple steps, used set next statement, and I changed the project from console app to asp.net core app. None of those variations produced any errors for me.

> This same issue locking issue also looks like it applies to "m_PinnedHeapHandleTableCrst" in "BaseDomain::AllocateObjRefPtrsInLargeTable".

@auott - in order for someone on the runtime to investigate we either need callstacks where you observed the threads blocked or dumps from debuggee. Do you have them?

**Comment by noahfalk** [comment]
@auott - actually looking at m_PinnedHeapHandleTableCrst this is probably simple enough that I can guess what the repro is even if you don't have stacks. They'd still be handy if you have them though.

**Comment by auott** [comment]
@noahfalk - I don't have any stacks at this point. I also haven't seen any repros that have come from .NET 7 (at least for this specific one) so it's definitely possible some of this has been cleaned up.

**Comment by noahfalk** [comment]
I just put up a PR that should resolve the PinnedHeapHandleTableCrst part of the issue. With no known repro I can't guarantee it fixes the problem, but I think I have a decent guess what happened and I am able to use the debugger to confirm that the new debugger suspension point is outside the PinnedHeapHandleTableCrst lock.

I am planning to mark the bug resolved once that fix gets checked in and if there are new func-eval deadlocks we can file those as new issues and evaluate them case by case. The runtime has never provided a guarantee that it is safe to run arbitrary func-evals when stopped at arbitrary places, but pragmatically we'll try to resolve any common obstacles if we can.
