### ISSUE TITLE
UserSecrets should be optional by default

### ISSUE THREAD

**Issue by jeroenlandheer** [dotnet/runtime#61418]
Since .Net 6.0, the `IConfigurationBuilder.AddUserSecrets` optional parameter defaults to `false` wich causes a runtime error

```
System.IO.FileNotFoundException: The configuration file 'secrets.json' was not found and is not optional.
```

For regular JSON configuration files this behaviour is correct, but for user secrets it is not. These are normally only used on developer's workstations, not in production code. 

Reproduction of this issue is easy, here's an example:

```csharp
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Configuration.UserSecrets;
using System.Reflection;

[assembly: UserSecretsId("{A24A5950-7D7F-42E5-B7C7-CFF64ADF7D29}")]

ConfigurationBuilder builder = new ConfigurationBuilder();
builder.AddUserSecrets(Assembly.GetExecutingAssembly());
var config = builder.Build();
```

**Comment by davidfowl** [comment]
Are you saying it was optional before and we broke it?

**Comment by zlatanov** [comment]
> Are you saying it was optional before and we broke it?

It wasn't optional before, but we broke it anyway.  See [this PR](https://github.com/dotnet/runtime/pull/44838/files). The problem is that the code before .NET 6, didn't really checked if user secrets were being added as optional or not.

`AddUserSecrets<T>()` indeed was not optional since it was introduced, but the method which eventually really adds the user secrets provider ignored this and always considered it optional.

The aforementioned PR changed this behavior. I agree with the OP however, User Secrets should never be required.

**Comment by davidfowl** [comment]
Ah it was ignored before 😄, therefore always optional. Got it.

**Comment by safern** [comment]
I think we should service this on 6.0.0 as this was the original behavior (due to not flowing a value, it was a bug, but still it was the original behavior). So either we add a breaking change doc or change the default value to be `true` on the override that doesn't take the boolean parameter. I think we should fix it in servicing but it would be breaking from 6.0.0 to 6.0.1, so that is what makes me doubt what is best here.

**Comment by Kralizek** [comment]
I'm having the same issue. The same application started nicely in .NET 5.0 but breaks in .NET 6.0.

**Comment by johnkwaters** [comment]
I have a flavor of this, I conditionally include user secrets in DEBUG mode - but in RELEASE I still get this error!

#if DEBUG
                        cfgBuilder.AddUserSecrets<Startup>();
#endif

**Comment by jeroenlandheer** [comment]
@johnkwaters 

If that's the case, I think the `DEBUG` constant is defined in your release configuration. You can check your project and see if you have any `<DefineConstants />` in your csproj file that might cause this. e.g.:

```xml
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants)TRACE;DEBUG</DefineConstants>
  </PropertyGroup>
```

A workaround is to use this in your code:
```csharp
cfgBuilder.AddUserSecrets(optional: true);
```
This line will still be included in release builds, but will not cause this issue.

**Comment by johnkwaters** [comment]
Thanks @jeroenlandheer - I ended up using that workaround. DEBUG is not defined in my csproj for Release (it isn't in Debug configuration either, which seems magic. Something not in my project is settings the compile time constant DEBUG. It's not in the build task in DevOps either.

**Comment by johnkwaters** [comment]
Here is my build pipeline:
[pipeline.txt](https://github.com/dotnet/runtime/files/7650919/pipeline.txt)

Here is my csproj
[TrailheadChronos.IdentityServer.txt](https://github.com/dotnet/runtime/files/7650922/TrailheadChronos.IdentityServer.txt)

**Comment by johnkwaters** [comment]
And here is how UserSecrets are loaded:
[Program.txt](https://github.com/dotnet/runtime/files/7650929/Program.txt)

**Comment by jeroenlandheer** [comment]
@johnkwaters 
Taking a quick glance, I think you should check the value of `$(BuildConfiguration)` variable in your build pipeline. If that's 'Debug' it will build a debug configuration. AFAICS there's not much else in your project file or code that could cause this. 

But this is getting a bit off-topic, since this issue is about UserSecrets, not about build pipelines conditional compilation constants. If you need more assistance, feel free to contact me directly.

**Comment by johnkwaters** [comment]
I realize it's off topic, but I want keep digging here because there's something going on that makes no sense.
My pipeline does define the configuration as release:

pool:
 vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

And the log from the build shows it compiled for Release:

C:\Windows\system32\chcp.com 65001
Active code page: 65001
Info: .NET Core SDK/runtime 2.2 and 3.0 are now End of Life(EOL) and have been removed from all hosted agents. If you're using these SDK/runtimes on hosted agents, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the required version.
C:\hostedtoolcache\windows\dotnet\dotnet.exe build D:\a\1\s\src\TrailheadChronos.IdentityServer\TrailheadChronos.IdentityServer.csproj "-dl:CentralLogger,\"D:\a\_tasks\DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b\2.187.0\dotnet-build-helpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll\"*ForwardingLogger,\"D:\a\_tasks\DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b\2.187.0\dotnet-build-helpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll\"" --configuration Release

Yet... it's complaining about no user secrets. I can't explain it.

**Comment by maryamariyan** [comment]
pinging @galakt the PR author, we are looking at reverting changes in https://github.com/dotnet/runtime/pull/44838, checking to see if this is not going to break you?

**Comment by zlatanov** [comment]
@maryamariyan I'd suggest that you don't revert them 1 to 1, but keep the changes where the callsite will throw if user secrets are not optional and missing, but change the entry point methods AddUserSecrets<T>() to use `optional: true` here:

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Microsoft.Extensions.Configuration.UserSecrets/src/UserSecretsConfigurationExtensions.cs#L30-L32

and here

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Microsoft.Extensions.Configuration.UserSecrets/src/UserSecretsConfigurationExtensions.cs#L84-L85

**Comment by galakt** [comment]
@maryamariyan reverting PR means "back to ignored parameter bug" :) I'd suggest just make a clear BC and set `optional: true`.

**Comment by safern** [comment]
Yes I agree we shouldn't revert the change but instead fix the behavior to behave as it used to do by default, but by keeping the fix, it means that costumers will be able to call these APIs with `optional: false` to make files optional, which didn't work before the fix.

**Comment by safern** [comment]
reopening as this needs to be ported to release/6.0

**Comment by dufkaf** [comment]
Hi, I just hit this issue when switching from 3.1 to 6. I get the `System.IO.FileNotFoundException: 'The configuration file 'secrets.json' was not found and is not optional.  ...` exception. 

I tried available  overloads with optional parameters
```
public static IConfigurationBuilder AddUserSecrets<T>(this IConfigurationBuilder configuration, bool optional)
public static IConfigurationBuilder AddUserSecrets<T>(this IConfigurationBuilder configuration, bool optional, bool reloadOnChange)
```
but still get the same exception when passing false (or false, false)
```
                .AddUserSecrets<Startup>(false)
```
anyone seeing this too?

**Comment by Kralizek** [comment]
Shouldn't you pass `true` to make the `secrets.json` file optional?

**Comment by dufkaf** [comment]
Oh, sorry, indeed that works, thank you.
Was somehow thinking false mean do no require the file. But of course the bool parameter would be named `required` in such case.

**Comment by safern** [comment]
This is fixed and will be included in the 6.0.2 release. Closing.

**Comment by Kralizek** [comment]
@safern was the fix to this issue included in the 6.0.2 release?

**Comment by safern** [comment]
Yes, however the package version with the fix is: [6.0.1](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.UserSecrets/6.0.1)

So you just need to reference `Microsoft.Extensions.Configuration.UserSecrets 6.0.1`
