### ISSUE TITLE
Static abstract methods missing during runtime

### ISSUE THREAD

**Issue by budgetdevv** [dotnet/runtime#62920]
### Description

A `System.MissingMethodException: Method not found` exception is thrown when the static ctor of the interface runs. This seems to only happen when the generic parameter of the interface has a generic constraint that is itself

### Reproduction Steps

```csharp
    public interface IJob<ThisT>
        where ThisT: IJob<ThisT>
    {
        static IJob() //Or any static field initializer
        {
            ExecuteFromInterface();
        }
    
        public static abstract void Execute();

        public static void ExecuteFromInterface()
        {
            ThisT.Execute();
        }
    }

    public class Job: IJob<Job>
    {
        public static void Execute()
        {
            Console.WriteLine("Foo");
        }
    }
```

### Expected behavior

It shouldn't throw, since the implementing class implements the static abstract method

### Actual behavior

It should throw a ``System.MissingMethodException: Method not found: 'Void StaticAbstractBug.IJob`1.Execute()'``

### Known Workarounds

Use generic param(s) without a constraint that is of the calling interface

### Configuration

- .NET 6
- Windows 10 Pro 64-bit ( 20H2, build 19042.1415 )
- x64
- I don't think so

**Comment by wzchua** [comment]
This was fixed in https://github.com/dotnet/runtime/pull/59663

**Comment by budgetdevv** [comment]
Thanks

**Comment by BOBJohnson** [comment]
I ran into this today on a new project I'm working on. How do I get access to the fix? Barring access, is there a workaround?

**Comment by BOBJohnson** [comment]
I just tried commenting out the where and I still get the exception at runtime as soon as I try to create an structure variable that implements an interface that has a static abstract property so I am not sure if my issue is the same as the one mentioned here, but it seems related...

Specifically, as soon as I try to create the variable, it immediately throws the method not found exception on the getter of the static property - but the static property is very much present on the structure in question. I'll try and see if I can make a minimum code version that can duplicate the issue, and post it here. Please let me know if I should post it elsewhere.

**Comment by BOBJohnson** [comment]
Found my problem...This is probably bad code on my part. I have generic static helper methods in the interface which have method bodies inside of the interface. Inside this interface I was trying to use a private static lazy dictionary that the method bodies interact with. Having any kind of private static variable inside the interface causes the ctor on the interface to be called which causes it to throw a method not found exception.

IE:
`internal interface IDefault<out T>
{
    private static readonly Lazy<int> iBlowUp = new Lazy<int>(42);

    public static abstract T Default { get; }
}`

The iBlowUp variable just by being present causes the interface to blow up the applicaiton.

My use case that I was hoping to achieve with the new static abstract properties and static interface method bodies was 'inheritance on structures' - where I had these really similar structures that I didn't want to make as classes (cause I wanted the benefit of them not being null like class objects can be [unless of course the structure variable was a nullable]), but they had this shared logic that could be abstracted to generics, so I was trying to avoid having to duplicate the code on each structure, and instead implement at the interface level.

This is probably a really stupid way of going about it, but I was trying to see if I could with the new interface logic in .Net 6.0.

**Comment by wzchua** [comment]
Does the work around mention in https://github.com/dotnet/runtime/pull/59663#pullrequestreview-767285266 help you?
It doesn't work for this issue's case. The fix isn't backported. You'll have to wait for the release for .NET7 preview.

**Comment by BOBJohnson** [comment]
@wzchua In my test project I tried moving the abstract property to be first but having a private static variable causes it to break.

After a little testing, I can have one or the other but not both. Basically I can have an interface that has an abstract property / method but not private static helper variables - or vice versa.

The workaround is to split apart the interface - IE, move the abstract pieces into their own interface(s), or move the private static helper variables to a helper class or something.
