### ISSUE TITLE
crossgen2 --instruction-set has no apparent effect on .NET 6 class library

### ISSUE THREAD

**Issue by twest820** [dotnet/runtime#63241]
What is the currently preferred process for compiling a class library to instruction sets more recent than the SSE2 associated with the x64 build target? If this has been documented a link would be great. I'm not finding anything after quite a bit of looking through docs.microsoft.com, issues here, and other likely sources.

This issue is a follow up to #226. Per that issue, I'm publishing a C# dll to win-x64 with
```
<PublishReadyToRun>true</PublishReadyToRun>
<PublishReadyToRunCrossgen2ExtraArgs>--instruction-set Avx</PublishReadyToRunCrossgen2ExtraArgs>
```
and, as #226 is syntactically ambiguous for .csproj XML, also trying
```
<PublishReadyToRunCrossgen2Args>--instruction-set Avx</PublishReadyToRunCrossgen2Args>
```

in the .csproj but the .dll included in the resulting .nupkg is apparently identical to the one produced by the regular x64 build target. From #62065 it looks like this should, in fact, have an effect when publishing from Visual Studio 2022 17.0.4. The publishing process is seeing `PublishReadyToRun`, at least, as that box gets automatically ticked in the published wizard. However, I'm not seeing that VS 2022 includes anything from the publishing process in the output windows or writes log files which could be used to investigate further. I just need the .dll and .pdb so avoiding the overhead of extracting them from a .nupkg and .snupkg would be fine.

%USERPROFILE%\.nuget\packages\microsoft.netcore.app.crossgen2.win-x64\6.0.1\tools\crossgen2.exe is present but I'm not finding examples of well formed command lines which could be adjusted to verify calling crossgen2 directly can alter the assembly. My hello world attempts fail with `error: option -u requires a value` even if I specify a value for -u.

Since someone will probably want to know, this .dll already contains loops coded with AVX intrinsics and will crash if run on older processors. We don't have anything pre-AVX so we're not concerned by that. I can change more loops over to intrinsics but a look through the remaining scalar loops' disassembly suggests doing so will be fairly low return on investment. What I'm hoping to accomplish here is to measure how much the build tools can do on their own. (For similar code in C++ I've usually seen about 10% from /arch:AVX.)

**Comment by EgorBo** [comment]
Can you try:
```
<PublishReadyToRunCrossgen2ExtraArgs>--instruction-set:avx</PublishReadyToRunCrossgen2Args>
```
or
```
<PublishReadyToRunCrossgen2ExtraArgs>--instruction-set%3aavx</PublishReadyToRunCrossgen2Args>
```

**Comment by twest820** [comment]
Hi Egor, neither delimiter variant has any effect. Since I would expect at least one of the three combinations to yield a packaging error from invalid instruction set syntax on the command line this seems most consistent with crossgen2 not getting invoked during the packaging process.

**Comment by EgorBo** [comment]
> crossgen2 not getting invoked during the packaging process.

Are you on .NET 6.0 ?

**Comment by EgorBo** [comment]
You can use `dotnet publish ... -v:n` to obtain msbuild logs and check which arguments are passed to crossgen2 exe

**Comment by twest820** [comment]
> Are you on .NET 6.0 ?

Yes, see the issue title. ;-) The build logs which are available do show the csc calls both VS and dotnet emit reference 6.0 libraries as expected.

> You can use dotnet publish ... -v:n to obtain msbuild logs and check which arguments are passed to crossgen2 exe

Unfortunately  `dotnet publish -r win-64 -c Release -v:n` and equivalents don't honor the `<AllowUnsafeBlocks>true</AllowUnsafeBlocks>` in the .csproj and therefore fail to emit a correct call to csc.exe. So invoking the packaging process that way isn't able to get to where crossgen2 would be called. (This is one reason it would be nice if VS logged what it does in the packaging process.)

**Comment by filipnavara** [comment]
> ...and equivalents don't honor the <AllowUnsafeBlocks>true</AllowUnsafeBlocks> in the .csproj...

They definitely honor that, it is powered by the same MSBuild SDK as IDE builds. What error are you getting?

Additionally, `Visual Studio Project Tools` extension can be used to capture the same build logs from within the VS IDE.

**Comment by twest820** [comment]
> What error are you getting?
It's a whole stack of
```
     1>Project\File1.cs(26,35): error CS0227: Unsafe code may only appear if compiling with /unsafe [Project\foo.csproj]
     1>Project\File1.cs(35,35): error CS0227: Unsafe code may only appear if compiling with /unsafe [Project\foo.csproj]
     1>Project\File2.cs(10,47): error CS0227: Unsafe code may only appear if compiling with /unsafe [Project\foo.csproj]
     1>Project\File3.cs(57,47): error CS0227: Unsafe code may only appear if compiling with /unsafe [Project\foo.csproj]
     1>Project\File3.cs(88,47): error CS0227: Unsafe code may only appear if compiling with /unsafe [Project\foo.csproj]
     1>Project\File3.cs(130,47): error CS0227: Unsafe code may only appear if compiling with /unsafe [Project\foo.csproj]
     1>Project\File3.cs(152,47): error CS0227: Unsafe code may only appear if compiling with /unsafe [Project\foo.csproj]
     1>Project\File3.cs(179,47): error CS0227: Unsafe code may only appear if compiling with /unsafe [Project\foo.csproj]
```
So, er, no, the unsafe enable's clearly not being honored. I understand it's supposed to be honored, if that's what you were asking. I'm unsure of the details of how dotnet flows switches to csc but, at a glance, what's on the dotnet command line may be somewhat mismatched to what's in the [csc documentation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/language):
```
         C:\Program Files\dotnet\dotnet.exe exec "C:\Program Files\dotnet\sdk\6.0.101\Roslyn\bincore\csc.dll" /noconfig /unsafe- /checked- /nowarn:1701,1702,1701,1702 /fullpaths /nostdlib+ /platform:x64 /errorreport:prompt /warn:6 ...
```


> Additionally, Visual Studio Project Tools extension can be used to capture the same build logs from within the VS IDE.

Did you mean the Project System Tools 2022 extension? If so, turning on its recording causes publishing to fail with
```
System.AggregateException: One or more errors occurred. ---> Microsoft.WebTools.Shared.Exceptions.WebToolsException: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. 
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Microsoft.WebTools.Shared.Exceptions.WebToolsException: Publish has encountered an error. We were unable to determine the cause of the error. Check the output log for more details. <---
```
With the output log just having the uninformative
```
1>The build stopped unexpectedly because of an unexpected logger failure.
```
Since this happens after publishing has figured out it doesn't need to rebuild the class library but before any of the steps which should call crossgen2, attempting to use the extension unfortunately seems to prevent gaining insight into what happens when packaging does get far enough to form a .nupkg.

Hopefully this offers some insight as to why I opened this issue with a question about what is known to work. It seems like there's substantial fragility within the build tools' current state but, presumably, some pathway other than intrinsics exists for getting a .NET build to understand you don't care whether your code runs on processors more than 10–11 years old and it's therefore ok to use xmm8-15 to reduce register spilling.

**Comment by filipnavara** [comment]
> I understand it's supposed to be honored, if that's what you were asking.

My guess would be that it's only set conditionally in some project configuration and that the one on the command line is not the same one as the one in the IDE.

**Comment by twest820** [comment]
> My guess would be that it's only set conditionally in some project configuration and that the one on the command line is not the same one as the one in the IDE.

They're the same. The `/platform` and `/define` to csc were among the first things I checked, actually. Granted, it's a bit curious Visual Studio generates `AllowUnsafeBlocks` conditionally when you have to turn it on in any configuration where you want the project to build, but it does align .csproj XML to the project setting UX. It's conceivable the two toolchains could somehow be interpreting x64 release differently but the only other build configuration extant in the solution is x64 debug and it necessarily also has `<AllowUnsafeBlocks>true</AllowUnsafeBlocks>` in the .csproj.
```
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <PlatformTarget>x64</PlatformTarget>
    <OutputPath></OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <PlatformTarget>x64</PlatformTarget>
    <OutputPath></OutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
```

From a pragmatic perspective, if the command line and Visual Studio build chains are sufficiently sensitive they don't interoperate over the definition of x64 release I'm uncertain it's productive to try to fight that.

> Yes.

Thank you.

**Comment by filipnavara** [comment]
Can you run `dotnet build <path to csproj> /p:Configuration=Debug /p:Platform=x64` to rule out any issue there? In VS IDE you usually have a .sln that provides the configuration mapping and there is always some mapping provided. In CLI when building single .csproj you will likely get Debug/AnyCPU as default. When building .sln from the command line it may behave differently but I am not sure what is the default. It basically transforms the whole solution file into meta-project in the MSBuild syntax and runs that.

**Comment by twest820** [comment]
Cool, that works, děkuji! It's just [the, er, documented command line parameters](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build) which don't behave correctly. The logical equivalent (also undocumented) is
```
dotnet publish /p:Configuration=Release /p:Platform=x64 --no-self-contained -v:n
```
which fails with
```
     1>C:\Program Files\dotnet\sdk\6.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(293,5): error NETSDK1094: Unable to optimize assemblies for performance: a valid runtime package was not found. Either set the PublishReadyToRun property to false, or use a supported runtime identifier when publishing. [foo.csproj]
```

It appears one solution is to make partial use of documented parameters:
```
dotnet publish -r win-x64 --no-self-contained /p:Configuration=Release -v:n
```
along with hacking around `win-x64` being unable to see the `x64` unsafe conditionals.

This produces
```
         C:\Program Files\dotnet\sdk\6.0.101\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(463,5): error : error: invalid option --instruction-set avx [C:\Users\westjoh\source\repos\SEEM\Seem\Seem.csproj]
```
which is useful as it confirms `<PublishReadyToRunCrossgen2ExtraArgs>` is the correct .csproj element to use (malformed example XML in #226 makes this ambiguous) and not so great in that it rather suggests the documentation and command line help for `PublishReadyToRunCrossgen2ExtraArgs` is incorrect. I think @EgorBo already suggested the fix for that, though, as
```
<PublishReadyToRunCrossgen2ExtraArgs>--instruction-set:avx</PublishReadyToRunCrossgen2ExtraArgs>
```
is accepted and yields a dll actually different from the one produced by csc. The disassembly of the loops I was most interested in remains disappointing, but that's a separate issue.

I suspect all this means

1. `win-x64` isn't considered to be `x64` and therefore doesn't pick up the conditional `<AllowUnsafeBlocks>true</AllowUnsafeBlocks>`. I don't see the specifics of the semantics as especially important but it seems needful to know what they are.
2. Visual Studio's publishing wizard isn't checking the publishing targets it presents to the user are valid for the project being published.
3. With the unconditional `AllowUnsafeBlocks` Visual Studio is still either ignoring `PublishReadyToRun` and `PublishReadyToRunCrossgen2ExtraArgs` or hitting some other problem with crossgen2 and then proceeding to silently produce a .nupkg with the non-crossgen2ed version of the class library.

My interpretation of all this is the build toolchains do, in fact, have some disagreement about what x64 release means, there seems to be a bug farm of interoperability issues as a result, and that it's unclear if use of crossgen2 is supported when packaging from within Visual Studio.

**Comment by AntonLapounov** [comment]
Thank you for reporting these issues to us.  I noticed that some of them are caused by using an old-style project file.  With a new SDK-style project file, you will have just
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
```
Note that the `AllowUnsafeBlocks` setting is not placed under any `Condition`.  Furthermore, if you publish from Visual Studio, instead of setting `PublishReadyToRun` in the project file, you are expected to use the "Publish -> Show all settings -> File publish options -> Enable ReadyToRun compilation" UI setting, which becomes available only if you set "Target runtime" in "Profile settings" to something specific, e.g., "win-x64".  If you do that, you should be able to see all `crossgen2.exe` compiler arguments in the Output window, including the `--instruction-set:avx` argument if you specify it with
```xml
<PublishReadyToRunCrossgen2ExtraArgs>--instruction-set:avx</PublishReadyToRunCrossgen2ExtraArgs>
```
I have fixed the related example in https://github.com/dotnet/runtime/issues/226#issuecomment-656924560.  Please let us know if you have more questions.

**Comment by twest820** [comment]
> Note that the `AllowUnsafeBlocks` setting is not placed under any `Condition`.

This is how it still is in the .csproj which prompted opening this issue eight months ago. Same `<Project Sdk="...">` and `<PropertyGroup>` structure as shown, too.

> you are expected to use the "Publish -> Show all settings -> File publish options -> Enable ReadyToRun compilation" UI setting

Please refer to the explanation in the OP of why producing a .nupkg is a non-goal. I just packaged again a couple minutes ago and the .dll in the .nupkg still the same as the one from the regular build. So the instructions just given continue not to work, on multiple levels.

> Please let us know if you have more questions.

I think I have two main ones

1. Since the wrong .dll is still landing in the .nupkg and that a .nupkg isn't the needed build output anyways, why is this issue currently closed?
2. Considering #226 is from November 2019, is there any ETA for when C# will have an equivalent of C++'s /arch:AVX or /arch:AVX2 that just works?

I do understand C# builds don't follow hardware as closely as C++ but AVX has been in production for 11 years and AVX2 for nine years. While I'm sure there are cases where the SSE2 target of x64 builds is still important I'm having a hard time understanding why it remains difficult to ask C# builds to make use of features available on Intel Core 2nd gen or newer or 4th gen and newer. Not that I don't use `System.Runtime.Intrinsics.X86.Avx2` extensively in my own code or that framework code isn't checking `System.Runtime.Intrinsics.X86.Avx2.IsSupported` but the objectives for #226 are specific about enabling build assumptions such as `Avx2.IsSupported == true`.

**Comment by AntonLapounov** [comment]
> Please refer to the explanation in the OP of why producing a .nupkg is a non-goal.

When you create a publish profile, please choose "Folder" as the "Target".  In that case the .nupkg file will not be created.

> So the instructions just given continue not to work, on multiple levels.

Can you see the command line like below in the Output window when you publish (you may need to increase verbosity in Debug->Options->Project and Solutions->Build And Run->MSBuild project build output verbosity)?
```
2>C:\Users\<Username>\.nuget\packages\microsoft.netcore.app.crossgen2.win-x64\6.0.7\tools\crossgen2.exe --targetos:windows
2>--targetarch:x64
2>-O
2>--instruction-set:avx
```
If you do not see `crossgen2.exe` executed at all, try touching the sources to force rebuilding.  If that does not help, please share a small repro project and repro steps so we could investigate further.

Before replying here, I had verified that `--instruction-set` is properly passed to the `crossgen2.exe` compiler for a newly created console project.  You can specify the following instruction sets delimited by a comma:
```
base, sse, sse2, sse3, ssse3, sse4.1, sse4.2, avx, avx2, aes, bmi, bmi2, fma, lzcnt, pclmul, popcnt, avxvnni
```
Please note that the goal of ReadyToRun compilation is to improve startup time and latency.  It does not and will not produce the most efficient code as documented [here](https://docs.microsoft.com/en-us/dotnet/core/deploying/ready-to-run):
> Ahead-of-time generated code is not as highly optimized as code produced by the JIT. To address this issue, tiered compilation will replace commonly used ReadyToRun methods with JIT-generated methods.

Instead, the JIT compiler is expected to use all the instructions supported by the processor.

**Comment by twest820** [comment]
> When you create a publish profile, please choose "Folder" as the "Target". In that case the .nupkg file will not be created.

I wish. Every time in the past eight months I've done this it's been Target = Folder producing a .nupkg.

Tried both detailed and diagnostic verbosity. While there's clear Crossgen2 awareness in the spew, I'm not getting any search hits on `crossgen2.exe`. It may be the diversion to an unexpected output type results in packaging determining that, while crossgen2 is requested, it isn't needed. I'm lacking time to read all the logs at the moment but it's possible Visual Studio's ended up doing something not quite right with respect to the targets as the project's changed .NET versions over the years.

For repro, [copying this](https://github.com/OSU-MARS/SEEM/tree/develop/Seem), uncommenting `<PublishReadyToRunCrossgen2ExtraArgs>` in the .csproj (tried --instruction-set too, per above), and right clicking on the project to publish in VS 2022 should do. Only change I'm making from what the wizard generates is Portable -> win-x64 since, for whatever reason, that isn't picked up from the build configuration.

> Please note that the goal of ReadyToRun compilation is to improve startup time and latency. 

No worries, I'm well aware. You'll notice some comments about older Intel Core in the .csproj 😄 and the modest improvements are consistent with expectations set some years ago in discussions about this before #226 was created. (I should update those notes for SSE 4.2 and more recent processors with reduced SIMD transition penalties, actually—given how Intel's SIMD implementations work there's a feature hole in that you can't ask crossgen2 for just the 128 bit subset of AVX, AVX2, or FMA. But that's a separate issue and, under AVX512VL, might not be one where we've reason to request specific attention.)

**Comment by AntonLapounov** [comment]
Thank you, I can reproduce the issue now.  For some reason `crossgen2.exe` is not executed at all when publishing from Visual Studio and a `.nupkg` file is created instead.

**Comment by AntonLapounov** [comment]
For historical reasons, publishing a class library project from Visual Studio would execute the `pack` target instead of the `publish` target.  The fix is ready and will be included in Visual Studio 17.4 Preview 2.  Until then, publishing from a command line (`dotnet publish`) may be used as a workaround.

I verified that if I add `<OutputType>Exe</OutputType>` to the `Seem\Seem.csproj` file and put `static void Main() { }` in some class, publishing from the current version of Visual Studio works as expected.  Namely, it executes `crossgen2.exe` on the libraries and passes the `--instruction-set` argument if the `PublishReadyToRunCrossgen2ExtraArgs` property is uncommented in the project file.
