### ISSUE TITLE
Console.CancelKeyPress is not called when SIGQUIT is received

### ISSUE THREAD

**Issue by szmcdull** [dotnet/runtime#64969]
`Console.CancelKeyPress` is not called when `SIGQUIT` is received. According to https://github.com/dotnet/runtime/pull/55333/files#diff-ee123c812e95f8a8374e7c7f083cc37b3eaf2807df56d41d5cbc701dc92472b4 SIGQUIT should now be handled by CancelKeyPress.

```
> dotnet --version
6.0.200-preview.22055.15

> cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Comment by adamsitnik** [comment]
Hi @szmcdull 

Thank you for your bug report. It has been fixed by @tmds in https://github.com/dotnet/runtime/pull/64200

We are going to test #64200 for a while by using it in 7.0 bits and backport it to 6.0

**Comment by tmds** [comment]
> Thank you for your bug report. It has been fixed by @tmds in https://github.com/dotnet/runtime/pull/64200

Because `CancelKeyPress` is used, it is a different issue.

> Console.CancelKeyPress is not called when SIGQUIT is received.

We have a test for this: `HandlerInvokedForSigQuit`, so it should work.

**Comment by adamsitnik** [comment]
@tmds is there any chance you could take a look at this issue? We are very close to .NET 7 release now and I won't be able to fix it myself.

**Comment by tmds** [comment]
I can't reproduce the issue on .NET 6.0.107.

@szmcdull can you still reproduce this issue using .NET 6.0? If so, can you share your code + steps?

**Comment by szmcdull** [comment]
Yes i can still reproduce it.

```c#
	static async Task Init()
	{
		Console.CancelKeyPress += OnCancelKeyPressed;
		AppDomain.CurrentDomain.ProcessExit += OnAppExit;
		await Task.Delay(-1);
	}

		static void OnCancelKeyPressed(object sender, ConsoleCancelEventArgs e)
		{
			Console.WriteLine($"Got SIGINT/SIGQUIT tid={Thread.CurrentThread.ManagedThreadId}");
		}

		void OnAppExit(object sender, EventArgs e)
		{
			Console.WriteLine($"server stopped tid={Thread.CurrentThread.ManagedThreadId}");
		}
```
publish the program to linux
```
dotnet publish --self-contained -c Release -r linux-x64 --force
```
Run it.
Start a new Terminal, find the process of the program then kill it using the linux `kill` command.
Test if the program prints `Got SIGINT/SIGQUIT `.

**Comment by adamsitnik** [comment]
@tmds were you able to repro it with the provided instructions?

**Comment by tmds** [comment]
I just tried this with 8.0.

`kill` sends `SIGTERM` by default. If I use it with `-SIGINT`/`-SIGQUIT` then it prints the message: `Got SIGINT/SIGQUIT`.

I think this works as expected, so I'll close the issue.

**Comment by szmcdull** [comment]
> `SIGTERM` by default. If I use it with `-SIGINT`/`-SIGQUIT`

Hi tmds, how about SIGTERM? How to gracefully handle a SIGTERM in Linux+.Net?
