### ISSUE TITLE
Use createdump to collect crash dumps for libraries tests

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#65422]
System dumps on macOS are large - uploading them has been taking down helix queues. Using the runtime's coredump features should allow for configuration such that we can get smaller and still useful dumps.

I *think* we should just be able to update the libraries runner template to set the [dump configuration environment variables](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/docs/design/coreclr/botr/xplat-minidump-generation.md#configurationpolicy) for `DbgEnableMiniDump`, `DbgMiniDumpName`, and `DbgMiniDumpType` instead of using ulimit:
https://github.com/dotnet/runtime/blob/8cd701ae165be73a91ec907e9522819c50d4f0ba/eng/testing/RunnerTemplate.sh#L130-L136

See also:
https://github.com/dotnet/runtime/pull/65405#discussion_r807507914
https://github.com/dotnet/core-eng/issues/15333

**Comment by mikem8361** [comment]
I recommend setting the following env vars:
```
export COMPlus_DbgEnableMiniDump=1
export COMPlus_DbgMiniDumpName=/path/to/coredump.%p
export COMPlus_DbgMiniDumpType=2
```
This enables a heap dump which has everything needed to diagnose most managed and native problems. The path can also contain these special name formatting chars:

```
%p  PID of dumped process.
%e  The process executable filename.
%h  Hostname return by gethostname().
%t  Time of dump, expressed as seconds since the Epoch, 1970-01-01 00:00:00 +0000 (UTC).
```

**Comment by hoyosjs** [comment]
Type 2 was still somewhat big when we looked at it. It's the best fidelity, but it definitely can get big and we need to improve the doc on debugging coredumps that we include.

**Comment by mikem8361** [comment]
They are not going to be as big as a full or system dump (especially on MacOS). The other choices are that great. The "normal" and "triage" dump types only have enough for triaging a problem: only the "pe", "clrstack" and "clrthreads" commands will work for managed code.  There should be enough for native stacks and threads though.

**Comment by jkotas** [comment]
We often need full dumps to investigate crashes that only happen intermittently in the CI.

Should the problem be rather solved by throttling the dump uploads? If a PR generates many dumps or if many PRs generate same dump, skip uploading them. 

The system should be designed to handle and gracefully recover from situations when we suddenly end up with large volume of crash dumps. There are many ways we can end up in a situation like that. It may be even worth it to create a weekly chaos monkey job that tries to flood the system with many big dumps to validate that it is not killing the system.

**Comment by hoyosjs** [comment]
> We often need full dumps to investigate crashes that only happen intermittently in the CI.
> 
> Should the problem be rather solved by throttling the dump uploads? If a PR generates many dumps or if many PRs generate same dump, skip uploading them. 

That change is upcoming. They are capping it in 2 ways. Upload time capped, and total dump size capped to 6 gb. They have the telemetry to say in helix 6 gb is what's safely uploadable while still being able to do the work and report results without timing out. There's two issues still there. The first one is the disk can still get full if many tests in a work item crash. A more concerning one is 6 gb is big, but not crazy for a macOS system dump. CreateDump is a little better here, but often still too big, mini with private memory seems like what we want from a diagnosibility perspective. I just don't know yet if that is going to cap us. I guess the best to do here is run a few experiments.

**Comment by ericstj** [comment]
@hoyosjs would it make since to try to do this with the libraries crash symbolization effort?   What's involved?

**Comment by hoyosjs** [comment]
For crashes of libraries? It would be setting https://github.com/dotnet/runtime/issues/65422#issuecomment-1044923021 these variables if not present in the wrapper such that they store the dumps in the folder that helix uploads. You can then symbolize all different dumps. For macOS, Jeremy is already staging work for it https://github.com/dotnet/runtime/pull/92967/files

**Comment by ericstj** [comment]
I meant - are you planning on re-enabling dumps for the places it was disabled? Perhaps by adding these settings.  In cases where it still might be too expensive to pull the dumps off the machine maybe @ivdiazsa's tool might be used to just dump the relevant info to the log.
