### ISSUE TITLE
DependencyInjectionEventSource Memory leak

### ISSUE THREAD

**Issue by windhuan** [dotnet/runtime#73832]
.net core 6.0.400-preview.22330.6

my code

<img width="905" alt="image" src="https://user-images.githubusercontent.com/10775645/184289476-f4befc58-6637-45dd-a2ed-0820caa4aabc.png">

Memory analysis

<img width="514" alt="image" src="https://user-images.githubusercontent.com/10775645/184280008-06c6a6ec-74ce-428a-922a-c16013063be0.png">

reason , HubConnectionBuilder.Build function

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/10775645/184289808-1585fe2e-c5c9-4221-8649-24387f99bd1d.png">

Add instance to DependencyInjectionEventSource._providers when ServiceProvider is created，but it can't remove when serviceprovider has no reference

**Comment by eerhardt** [comment]
1. ServiceProvider is `IDisposable`. You should be disposing it when you are done. I don't see you disposing it above.
2. The reference you show above with DependencyInjectionEventSource is a WeakReference. Which means if there are no other references to the object, the GC is free to clean the object up.

**Comment by windhuan** [comment]
> 1. ServiceProvider is `IDisposable`. You should be disposing it when you are done. I don't see you disposing it above.
> 2. The reference you show above with DependencyInjectionEventSource is a WeakReference. Which means if there are no other references to the object, the GC is free to clean the object up.
1. i can't get ServiceProvider reference, because HubConnectionBuilder.Build() not return. (HubConnectionBuilder is SignalR client code https://github.com/dotnet/aspnetcore/blob/main/src/SignalR/clients/csharp/Client.Core/src/HubConnectionBuilder.cs)
2. gc can free WeakReference 's object,but it can't free List<WeakReference>  item

**Comment by eerhardt** [comment]
> i can't get ServiceProvider reference, because HubConnectionBuilder.Build() not return. (HubConnectionBuilder is SignalR client code

@davidfowl @BrennanConroy - thoughts on Disposing the `ServiceProvider` in HubConnectionBuilder?

**Comment by davidfowl** [comment]
The builder doesn't dispose the service provider, when you dispose the HubConnection itself the service provider gets disposed.

**Comment by windhuan** [comment]
> The builder doesn't dispose the service provider, when you dispose the HubConnection itself the service provider gets disposed.

I call the HubConnection.DisposeAsync ,but serviceprovider not disposed

<img width="975" alt="image" src="https://user-images.githubusercontent.com/10775645/184377955-4ff6b037-f488-4f9a-8ad6-e0a08a106f21.png">

**Comment by davidfowl** [comment]
Well you build your own service provider (which you aren't supposed to do). This is how you use the HubConnectionBuilder:

```C#
var hubConnectionBuilder = new HubConnectionBuilder();
hubConnectionBuilder.WithUrl($"http://{machnie.Address}/signalr/machineHub", (options) =>
{
    options.AccessTokenProvider = () => Task.FromResult(Common.AccessToken.Token);
});
var connection = hubConnectionBuilder.Build();
await connection.DisposeAsync();
```

**Comment by davidfowl** [comment]
You can see the code that disposes the connection here https://github.com/dotnet/aspnetcore/blob/7cb457bdaac8de9214391a9b9b273821d01c2300/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs#L558-L570

**Comment by windhuan** [comment]
> You can see the code that disposes the connection here https://github.com/dotnet/aspnetcore/blob/7cb457bdaac8de9214391a9b9b273821d01c2300/src/SignalR/clients/csharp/Client.Core/src/HubConnection.cs#L558-L570

HubConnection dispose the child service provider ,but root service provider is not dispose
DependencyInjectionEventSource  reference the root service provider
<img width="868" alt="image" src="https://user-images.githubusercontent.com/10775645/184382291-cbe8dbae-a321-417e-b911-e8f658488822.png">

**Comment by davidfowl** [comment]
I can reproduce this:

```C#
var services = new ServiceCollection();
var sp = services.BuildServiceProvider();
((IDisposable)sp.GetRequiredService<IServiceProvider>()).Dispose();
```

This doesn't dispose the service provider and I'm trying to figure out why.

**Comment by davidfowl** [comment]
I think it does dispose the services, but it doesn't dispose the `ServiceProvider` instance itself. This wasn't a problem before .NET 6 because we didn't do anything besides disposing the root scope itself, now we clean up the event source as well so there's a leak.

**Comment by eerhardt** [comment]
@davidfowl - if we don't think changing DI is the right call, another option is to not inject the `IServiceProvider` into HubConnection, but instead follow the same pattern that Hosting does and call the ctor directly with the actual `ServiceProvider` instance:

https://github.com/dotnet/runtime/blob/e71a9583b4d6c9bd97edd87cda7f98f232f63530/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.cs#L304-L308

Or do you think this pattern of "inject IServiceProvider into a `service` and let the service call Dispose on it" is the right pattern to support?

**Comment by davidfowl** [comment]
I think disposing the root IServiceProvider and ServiceProvider should be identical. Whether we change signalR as well is separate.

**Comment by davidfowl** [comment]
cc @BrennanConroy as an FYI

**Comment by tarekgh** [comment]
@davidfowl do you think this is critical to fix for .NET 7.0? or can it wait to 8.0? from reading looks we have this behavior in 6.0 too.

**Comment by davidfowl** [comment]
I think we should fix this in .NET 7 and 6

**Comment by ericstj** [comment]
Got it, this meets the bar for 7.0 if we'd service it in 6.0.  @eerhardt do we have enough info from @davidfowl's [suggestion](https://github.com/dotnet/runtime/issues/73832#issuecomment-1213313164) to try out a fix?  How risky would it be?

**Comment by eerhardt** [comment]
> do we have enough info from @davidfowl's https://github.com/dotnet/runtime/issues/73832#issuecomment-1213313164 to try out a fix?

Yes, I believe so.

> How risky would it be?

Fairly low risk. If someone was Disposing the "root" ServiceProviderEngineScope, but not the `ServiceProvider`, and was still trying to use the `ServiceProvider` in their application, they could still get Singleton services from it. So disposing the `ServiceProvider` along with the "root" ServiceProviderEngineScope may break something that currently works today, but isn't supposed to work.

**Comment by davidfowl** [comment]
Where do we track the backport?

**Comment by tarekgh** [comment]
> Where do we track the backport?

I'll start the backport now. will tag you on that. The backport will be for .NET 7.0 and .NET 6.0 too.
