### ISSUE TITLE
[jitstress] HardwareIntrinsics_ro fails with "process cannot access the file" error

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#83298]
Seems to be failing widely.

```scala
01:45:37.661 Passed test: global::JIT.HardwareIntrinsics.X86._Ssse3.Program.SignInt32()
01:45:37.661 Running test: JIT/HardwareIntrinsics/General/Vector256_1/Vector256_1_ro/Vector256_1_ro.cmd
App Exit Code: 259
Expected: 100
Actual: 259
END EXECUTION - FAILED
FAILED
Unhandled exception. System.IO.IOException: The process cannot access the file 'C:\h\w\AE5609E1\w\B7AD09EA\e\JIT\HardwareIntrinsics\HardwareIntrinsics_ro\HardwareIntrinsics_ro.testStats.csv' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.ReadLines(String path)
   at XUnitLogChecker.Main(String[] args) in D:\a\_work\1\s\src\tests\Common\XUnitLogChecker\XUnitLogChecker.cs:line 77
```

@ivdiazsa Could this be related to #78742? Could also likely be #83261.

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=201133
Build error leg or test failing: HardwareIntrinsics_ro.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/83005

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "csv' because it is being used by another process",
  "ExcludeConsoleLog": false
}
```

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[204788](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204788)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/204788/logs/2295)|dotnet/runtime#83427|
|[204784](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204784)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/204784/logs/2330)|dotnet/runtime#83050|
|[204543](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204543)|dotnet/runtime|coreclr  Pri0 Runtime Tests Run  osx x64 checked|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/204543/logs/2239)|dotnet/runtime#82970|
|[204345](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204345)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/204345/logs/12)||
|[204427](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204427)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/204427/logs/1379)|dotnet/runtime#83413|
|[204428](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204428)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/204428/logs/2435)||
|[204376](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204376)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/204376/logs/2320)|dotnet/runtime#83412|
|[204340](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204340)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/204340/logs/1123)|dotnet/runtime#83411|
|[204044](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204044)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/204044/logs/2247)|dotnet/runtime#83354|
|[203973](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203973)|dotnet/runtime|coreclr  Pri0 Runtime Tests Run  osx arm64 checked|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/203973/logs/1686)|dotnet/runtime#79283|
|[203855](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203855)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/203855/logs/2207)|dotnet/runtime#83050|
|[203876](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203876)|dotnet/runtime|osx-x64 Release AllSubsets_Mono_Interpreter_RuntimeTests monointerpreter|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/203876/logs/1266)|dotnet/runtime#83337|
|[203547](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203547)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/203547/logs/797)|dotnet/runtime#83380|
|[203800](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203800)|dotnet/runtime|coreclr  Pri0 Runtime Tests Run  linux arm checked|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/203800/logs/1228)|dotnet/runtime#83388|
|[203765](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203765)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/203765/logs/2388)|dotnet/runtime#83299|
|[203621](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203621)|dotnet/runtime|coreclr  Pri0 Runtime Tests Run  linux arm checked|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/203621/logs/2223)|dotnet/runtime#80154|
|[203583](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203583)|dotnet/runtime|coreclr  Pri1 Runtime Tests Run  linux x64 release|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/203583/logs/306)||
|[203537](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203537)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/203537/logs/1242)|dotnet/runtime#82827|
|[203341](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203341)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/203341/logs/2373)|dotnet/runtime#83354|
|[203507](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203507)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/203507/logs/178)|dotnet/runtime#82954|
|[203473](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203473)|dotnet/runtime|coreclr  Pri0 Runtime Tests Run  osx x64 checked|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/203473/logs/2364)|dotnet/runtime#80154|
|[203478](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203478)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/203478/logs/515)|dotnet/runtime#83371|
|[203421](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203421)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/203421/logs/12)||
|[203382](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203382)|dotnet/runtime|coreclr  Pri1 Runtime Tests Run  linux x64 release|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/203382/logs/765)||
|[203384](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203384)|dotnet/runtime|coreclr  Pri0 Runtime Tests Run Composite osx x64 checked|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/203384/logs/512)||
|[203348](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203348)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/203348/logs/1000)||
|[203352](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203352)|dotnet/runtime|coreclr  Pri0 Runtime Tests Run  linux arm checked|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/203352/logs/1666)|dotnet/runtime#80154|
|[203328](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203328)|dotnet/runtime|coreclr  Pri0 Runtime Tests Run  linux arm64 checked|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/203328/logs/1920)|dotnet/runtime#79334|
|[203275](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203275)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/203275/logs/2199)|dotnet/runtime#82045|
|[203108](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203108)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/203108/logs/689)|dotnet/runtime#82779|
|[202951](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202951)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/202951/logs/2167)|dotnet/runtime#83356|
|[202862](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202862)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/202862/logs/2309)|dotnet/runtime#82045|
|[202821](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202821)|dotnet/runtime|coreclr  Pri0 Runtime Tests Run  osx x64 checked|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/202821/logs/1961)|dotnet/runtime#80154|
|[202706](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202706)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/202706/logs/12)||
|[202648](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202648)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/202648/logs/222)|dotnet/runtime#83334|
|[202622](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202622)|dotnet/runtime|coreclr  Pri0 Runtime Tests Run  osx arm64 checked|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/202622/logs/2294)|dotnet/runtime#82045|
|[202588](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202588)|dotnet/runtime|coreclr  Pri0 Runtime Tests Run  osx arm64 checked|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/202588/logs/1691)|dotnet/runtime#79283|
|[202432](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202432)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/202432/logs/47)|dotnet/runtime#79169|
|[202394](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202394)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/202394/logs/2255)|dotnet/runtime#79169|
|[202373](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202373)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/202373/logs/1219)|dotnet/runtime#83335|
|[202281](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202281)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/202281/logs/2418)|dotnet/runtime#83300|
|[202216](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202216)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/202216/logs/2295)|dotnet/runtime#83253|
|[202211](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202211)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/202211/logs/183)|dotnet/runtime#82049|
|[202132](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202132)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/202132/logs/1216)|dotnet/runtime#83094|
|[202065](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202065)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/202065/logs/12)||
|[202081](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202081)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/202081/logs/2561)||
|[202049](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202049)|dotnet/runtime|Send tests to Helix (Windows)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/202049/logs/325)||
|[202048](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202048)|dotnet/runtime|coreclr  Pri1 Runtime Tests Run  linux arm64 release|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/202048/logs/777)||
|[202046](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202046)|dotnet/runtime|coreclr  Pri0 Runtime Tests Run Composite osx arm64 checked|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/202046/logs/500)||
|[202034](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202034)|dotnet/runtime|Send tests to Helix (Unix)|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/202034/logs/1006)||

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[205173](https://dev.azure.com/dnceng-public/public/_build/results?buildId=205173)|dotnet/runtime|[HardwareIntrinsics_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=205173&view=ms.vss-test-web.build-test-results-tab&runId=3822819&resultId=116406)||
|[205061](https://dev.azure.com/dnceng-public/public/_build/results?buildId=205061)|dotnet/runtime|[HardwareIntrinsics_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=205061&view=ms.vss-test-web.build-test-results-tab&runId=3820242&resultId=116402)||
|[205036](https://dev.azure.com/dnceng-public/public/_build/results?buildId=205036)|dotnet/runtime|[HardwareIntrinsics_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=205036&view=ms.vss-test-web.build-test-results-tab&runId=3820083&resultId=116422)||
|[204901](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204901)|dotnet/runtime|[HardwareIntrinsics_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204901&view=ms.vss-test-web.build-test-results-tab&runId=3818625&resultId=116402)||
|[204829](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204829)|dotnet/runtime|[HardwareIntrinsics_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204829&view=ms.vss-test-web.build-test-results-tab&runId=3816981&resultId=116422)|dotnet/runtime#83402|
|[204444](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204444)|dotnet/runtime|[HardwareIntrinsics_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204444&view=ms.vss-test-web.build-test-results-tab&runId=3812292&resultId=116406)|dotnet/runtime#83413|
|[204050](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204050)|dotnet/runtime|[HardwareIntrinsics_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204050&view=ms.vss-test-web.build-test-results-tab&runId=3812144&resultId=122364)|dotnet/runtime#83354|
|[204232](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204232)|dotnet/runtime|[HardwareIntrinsics_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204232&view=ms.vss-test-web.build-test-results-tab&runId=3809587&resultId=116675)||
|[204227](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204227)|dotnet/runtime|[HardwareIntrinsics_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=204227&view=ms.vss-test-web.build-test-results-tab&runId=3809963&resultId=116422)|dotnet/runtime#83402|
|[203486](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203486)|dotnet/runtime|[HardwareIntrinsics_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203486&view=ms.vss-test-web.build-test-results-tab&runId=3799644&resultId=116666)||
|[203487](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203487)|dotnet/runtime|[HardwareIntrinsics_r.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203487&view=ms.vss-test-web.build-test-results-tab&runId=3799445&resultId=104951)||
|[203369](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203369)|dotnet/runtime|[HardwareIntrinsics_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203369&view=ms.vss-test-web.build-test-results-tab&runId=3797976&resultId=116666)|dotnet/runtime#83372|
|[203349](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203349)|dotnet/runtime|[HardwareIntrinsics_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203349&view=ms.vss-test-web.build-test-results-tab&runId=3797723&resultId=116666)||
|[203347](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203347)|dotnet/runtime|[HardwareIntrinsics_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203347&view=ms.vss-test-web.build-test-results-tab&runId=3797735&resultId=116476)|dotnet/runtime#83354|
|[203308](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203308)|dotnet/runtime|[HardwareIntrinsics_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203308&view=ms.vss-test-web.build-test-results-tab&runId=3797443&resultId=116406)||
|[203201](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203201)|dotnet/runtime|[HardwareIntrinsics_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203201&view=ms.vss-test-web.build-test-results-tab&runId=3796042&resultId=116406)||
|[203096](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203096)|dotnet/runtime|[HardwareIntrinsics_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203096&view=ms.vss-test-web.build-test-results-tab&runId=3794817&resultId=116476)|dotnet/runtime#83354|
|[203089](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203089)|dotnet/runtime|[global::JIT.HardwareIntrinsics.X86._Avx512F.Program.XorInt64()](https://dev.azure.com/dnceng-public/public/_build/results?buildId=203089&view=ms.vss-test-web.build-test-results-tab&runId=3794629&resultId=102617)|dotnet/runtime#83354|
|[202848](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202848)|dotnet/runtime|[HardwareIntrinsics_r.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202848&view=ms.vss-test-web.build-test-results-tab&runId=3791236&resultId=104951)||
|[202653](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202653)|dotnet/runtime|[HardwareIntrinsics_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202653&view=ms.vss-test-web.build-test-results-tab&runId=3789650&resultId=116422)||
|[202124](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202124)|dotnet/runtime|[HardwareIntrinsics_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202124&view=ms.vss-test-web.build-test-results-tab&runId=3781341&resultId=116421)||
|[202123](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202123)|dotnet/runtime|[HardwareIntrinsics_r.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202123&view=ms.vss-test-web.build-test-results-tab&runId=3781034&resultId=104950)||
|[202035](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202035)|dotnet/runtime|[HardwareIntrinsics_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202035&view=ms.vss-test-web.build-test-results-tab&runId=3779544&resultId=116665)||
|[202030](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202030)|dotnet/runtime|[HardwareIntrinsics_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=202030&view=ms.vss-test-web.build-test-results-tab&runId=3779437&resultId=122255)||
|[201969](https://dev.azure.com/dnceng-public/public/_build/results?buildId=201969)|dotnet/runtime|[HardwareIntrinsics_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=201969&view=ms.vss-test-web.build-test-results-tab&runId=3779172&resultId=116665)||
|[201955](https://dev.azure.com/dnceng-public/public/_build/results?buildId=201955)|dotnet/runtime|[HardwareIntrinsics_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=201955&view=ms.vss-test-web.build-test-results-tab&runId=3778789&resultId=116421)||
|[201953](https://dev.azure.com/dnceng-public/public/_build/results?buildId=201953)|dotnet/runtime|[HardwareIntrinsics_ro.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=201953&view=ms.vss-test-web.build-test-results-tab&runId=3778734&resultId=122255)||
|[201952](https://dev.azure.com/dnceng-public/public/_build/results?buildId=201952)|dotnet/runtime|[HardwareIntrinsics_r.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=201952&view=ms.vss-test-web.build-test-results-tab&runId=3778508&resultId=104950)|dotnet/runtime#83250|
|[201883](https://dev.azure.com/dnceng-public/public/_build/results?buildId=201883)|dotnet/runtime|[HardwareIntrinsics_r.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=201883&view=ms.vss-test-web.build-test-results-tab&runId=3778045&resultId=104950)|dotnet/runtime#82744|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|18|79|79|

**Comment by EgorBo** [comment]
@ivdiazsa could you please take a look if that was your PR, this broke many outerloop pipelines

**Comment by ivdiazsa** [comment]
I just checked the failures and the Linux ones seem to be because of the test taking too long. Do we expect these tests to last more than 5 minutes? If yes, then that's an adjustment to make to the watcher. If not, then we can confirm the watcher is doing its job of preventing potential freezes.

As for the Windows ones, I have no idea. Seems like potentially a problem with Windows liking to hold on to resources for whatever reason. However, it seems to be working on my machine so far. I will continue trying to repro it.

**Comment by trylek** [comment]
I think that we have two different issues here:

1) In general 5 minutes sounds like not a lot especially in JIT stress mode; IIRC @davidwrighton originally implemented these tests and we actually recently discussed their performance on another issue thread but I think 5 minutes is just too drastic. In the YAML pipelines there used to be this property <code>TimeoutPerTestInMinutes</code> that ultimately translates to the environment variable <code>__TestTimeout</code> in Helix, ideally we should fix the watcher to use that instead of hard-coding the timeout as @BruceForstall pointed out in the PR thread https://github.com/dotnet/runtime/pull/78742.

2) While the test timeout may have been caused by too aggressive setting of the timeout value, the infrastructure should be still capable of dealing with such real-life situations. It seems to me that the error message quoted in the title of this issue got hit due to the fact that, as the app was forcibly terminated due to the presumed timeout, the <code>*.testStats.csv</code> file wasn't properly closed at the test side and subsequently the XUnit log checker failed to open it for reading. My initial thinking is that we should either allow read-share for the file write in the Roslyn-generated wrapper assuming incomplete reads from the file are treated as benign or introduce some back-off logic that would wait for the file handle to be released in a couple of seconds as part of "process GC" in Windows somewhat akin to directory deletion which is also asynchronous in Win32.

Hope that helps

Tomas

**Comment by ivdiazsa** [comment]
I've been trying to repro this all day, but to no avail. I think @trylek's explanation makes total sense so what I will do next is to make the watcher use that environment variable to determine the timeouts if set.

**Comment by BruceForstall** [comment]
In the merged tests case, like HardwareIntrinsics_ro, *all* the tests run under a *single* invocation of corerun.exe, so it's not surprising at all that the total time would exceed 5 minutes.

> Do you mean like, have the log checker wait a couple seconds before executing on Windows?

That make sense to me: if the log read fails, then wait a few seconds, try again, wait a few seconds, try again. Maybe wait as much as a minute or more?

**Comment by ivdiazsa** [comment]
> In the merged tests case, like HardwareIntrinsics_ro, _all_ the tests run under a _single_ invocation of corerun.exe, so it's not surprising at all that the total time would exceed 5 minutes.
> 
> > Do you mean like, have the log checker wait a couple seconds before executing on Windows?
> 
> That make sense to me: if the log read fails, then wait a few seconds, try again, wait a few seconds, try again. Maybe wait as much as a minute or more?

Got it! Yes, I also think 1 minute of retrying every couple seconds or so to read the log is reasonable. If we still can't read it after that then maybe it's safe to assume something went terribly wrong that would require a developer to look at.

**Comment by trylek** [comment]
@ivdiazsa - for debugging the locked csv file issue I bet it should suffice to set the watcher timeout to something ridiculous like 1 second, then you should be surely able to hit the timeout and forced app termination and I assume you'll immediately also see the locked file issue, I'm hitting it locally all the time on my Windows machine whenever I forcibly kill an app, all files it held on to remain locked for something like10~30 more seconds (subjective guess, I haven't actually measured it).

**Comment by trylek** [comment]
For the directory deletion example I mentioned, this is how I implemented it in R2RTest (by porting my previous fix for .NET Native where it also used to crash lab runs about 8 years back):

https://github.com/dotnet/runtime/blob/1c8d37af80667daffb3cb80ce0fe915621e8f039/src/coreclr/tools/r2rtest/PathHelpers.cs#L162

**Comment by trylek** [comment]
(It's a tad overcomplicated due to using the async logic to delete subtrees concurrently, that's something you thankfully don't need.)

**Comment by BruceForstall** [comment]
@ivdiazsa @trylek @hoyosjs Given that this is causing all "outerloop" runs to fail, and many other pipelines as well, can we immediately revert the watcher change (or disable it, if that is trivial to do)?

**Comment by hoyosjs** [comment]
Revert PR is up - it doesn't make sense to block others.

**Comment by hoyosjs** [comment]
I updated the issue - it was running against a pretty broad string.

**Comment by ivdiazsa** [comment]
Closing after being addressed by PR #83427.
