### ISSUE TITLE
SerialPort is not supported on Android ?

### ISSUE THREAD

**Issue by Strawberrybeans** [dotnet/runtime#86619]
### Description

when open serialport Exception : System.DllNotFoundException: 'libSystem.IO.Ports.Native'

### Reproduction Steps

1.Create a SerialPort class
2.Configure the serial port settings
3.Open the serial port

### Expected behavior

open serialport success

### Actual behavior

monodroid-assembly Shared library 'libSystem.IO.Ports.Native' not loaded, p/invoke 'SystemIoPortsNative_SerialPortOpen' may fail

### Configuration

.net core7.0
android 7.1
arm

**Comment by steveisok** [comment]
@akoeplinger we should at least thrown a PNSE if it's not implemented as opposed to failing to pinvoke.

**Comment by wfurt** [comment]
This also may be just packaging. We ship serial port as separate package on Unix https://www.nuget.org/packages/System.IO.Ports/
But we missed some platforms there - like ARM on Alpine.
Fix may be as simple as #92145 but I don't have Android to test on.

**Comment by BaY1251** [comment]
Devices that can use serial ports are actually all customized systems.
The issues with SELinux do not need to be treated as obstacles

**Comment by akoeplinger** [comment]
Ok yeah as long as users will know what to do when they run into the SELinux issues I guess it doesn't hurt.

@BaY1251 do you have a way to test a fix? I don't have an Android device with serial ports.

**Comment by lkhore** [comment]
[akoeplinger](https://github.com/akoeplinger) You can use usb type c otg cable for the test with Android device

**Comment by akoeplinger** [comment]
Thanks, I've merged the PR and in a few hours we should get packages to test.

**Comment by BaY1251** [comment]
@akoeplinger I am happy to test it, Please let me know when the test package is available

This address may be helpful, 

https://[github.com](https://github.com/NevermindZZT/SocketAssistant)/NevermindZZT/SocketAssistant

**Comment by wfurt** [comment]
https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet9/NuGet/System.IO.Ports/versions/9.0.0-ci

You will probably need to add this to you Nuget config. The packages are not pushed to NuGet.org.
```
<add key="dotnet9" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet9/nuget/v3/index.json" />
```

But it seems like the current `9.0.0-alpha.1.23607.6` still does not have the change.

**Comment by BaY1251** [comment]
Yes. Thank you. i will try later

**Comment by akoeplinger** [comment]
`9.0.0-alpha.1.23608.10` does have the change.

**Comment by akoeplinger** [comment]
Hmm but I just saw that the corresponding runtime.android-arm64.runtime.native.System.IO.Ports package doesn't seem to be on the feed, while the linux-bionic added in the same PR is...

**Comment by akoeplinger** [comment]
I figured out the issue, it is related to DefaultPrimaryRuntimeFlavor being CoreCLR on Android and it skips building the RID specific packages in the Mono leg then. This will need a bit more thinking to not break anything :)

**Comment by BaY1251** [comment]
Yes.
Unable to resolve dependency 'runtime.android-arm.runtime.native.System.IO.Ports'. 
So currently it is still unavailable..

**Comment by akoeplinger** [comment]
@BaY1251 would you mind trying again with version 9.0.0-alpha.1.23614.10? it should work now.

**Comment by lkhore** [comment]
Hi @akoeplinger ,
I am getting below error so how i can utilize the io function

```
{DeviceDriver.CommunicationException: 4223: Unable to connect to , Access was denied.
 ---> System.UnauthorizedAccessException: Access to the port '/dev/ttyUSB0' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.Ports.SafeSerialDeviceHandle.Open(String portName)
   at System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   at System.IO.Ports.SerialPort.Open()
   at DeviceDriver.Connections.SerialConnection.Open() in D:\Repo\Xamerin\MESP\DeviceDriver\Connection\SerialConnection.vb:line 151
   --- End of inner exception stack trace ---
   at DeviceDriver.Connections.SerialConnection.Open() in D:\Repo\Xamerin\MESP\DeviceDriver\Connection\SerialConnection.vb:line 160
   at DeviceDriver.Connections.SerialConnection.Open() in D:\Repo\Xamerin\MESP\DeviceDriver\Connection\SerialConnection.vb:line 163
   at DeviceDriver.Connections.SerialConnection.Open() in D:\Repo\Xamerin\MESP\DeviceDriver\Connection\SerialConnection.vb:line 163
   at DeviceDriver.Connections.SerialConnection.Open() in D:\Repo\Xamerin\MESP\DeviceDriver\Connection\SerialConnection.vb:line 163
   at DeviceDriver.Connections.SerialConnection.Open() in D:\Repo\Xamerin\MESP\DeviceDriver\Connection\SerialConnection.vb:line 163
   at DeviceDriver.Connections.SerialConnection.Open() in D:\Repo\Xamerin\MESP\DeviceDriver\Connection\SerialConnection.vb:line 163
   at DeviceDriver.Connections.SerialConnection.Open() in D:\Repo\Xamerin\MESP\DeviceDriver\Connection\SerialConnection.vb:line 163
   at DeviceDriver.Connections.SerialConnection.Open() in D:\Repo\Xamerin\MESP\DeviceDriver\Connection\SerialConnection.vb:line 163
   at DeviceDriver.Connections.SerialConnection.Open() in D:\Repo\Xamerin\MESP\DeviceDriver\Connection\SerialConnection.vb:line 163
   at DeviceDriver.Connections.SerialConnection.Open() in D:\Repo\Xamerin\MESP\DeviceDriver\Connection\SerialConnection.vb:line 163
   at DeviceDriver.Connections.SerialConnection.Open() in D:\Repo\Xamerin\MESP\DeviceDriver\Connection\SerialConnection.vb:line 163
   at DeviceDriver.Connections.SerialConnection.Open() in D:\Repo\Xamerin\MESP\DeviceDriver\Connection\SerialConnection.vb:line 163
   at DeviceDriver.Connections.SerialConnection.Open() in D:\Repo\Xamerin\MESP\DeviceDriver\Connection\SerialConnection.vb:line 163
   at DeviceDriver.Connections.SerialConnection.Open() in D:\Repo\Xamerin\MESP\DeviceDriver\Connection\SerialConnection.vb:line 163
   at DeviceDriver.Connections.SerialConnection.Open() in D:\Repo\Xamerin\MESP\DeviceDriver\Connection\SerialConnection.vb:line 163
   at DeviceDriver.Connections.SerialConnection.Open() in D:\Repo\Xamerin\MESP\DeviceDriver\Connection\SerialConnection.vb:line 163
   at DeviceDriver.Connections.SerialConnection.Open() in D:\Repo\Xamerin\MESP\DeviceDriver\Connection\SerialConnection.vb:line 163
   at DeviceDriver.Connections.SerialConnection.Open() in D:\Repo\Xamerin\MESP\DeviceDriver\Connection\SerialConnection.vb:line 163
   at DeviceDriver.Connections.SerialConnection.Open() in D:\Repo\Xamerin\MESP\DeviceDriver\Connection\SerialConnection.vb:line 163
   at DeviceDriver.Connections.SerialConnection.Open() in D:\Repo\Xamerin\MESP\DeviceDriver\Connection\SerialConnection.vb:line 163
   at DeviceDriver.Connections.SerialConnection.Open() in D:\Repo\Xamerin\MESP\DeviceDriver\Connection\SerialConnection.vb:line 163
   at DeviceDriver.Commands.Dispenser.InitializationCommand.TryCreateConnection(String& ADataLinkName, Int32 ADatalinkBaudrate, BaseConnection& AConnection) in D:\Repo\Xamerin\MESP\DeviceDriver\Commands\Dispenser\InitializationCommand.vb:line 81}
```

**Comment by akoeplinger** [comment]
@lkhore yeah as explained in https://github.com/dotnet/runtime/issues/86619#issuecomment-1843502371 SELinux will block this by default, you need to disable it (only possible on rooted phones or custom Android builds)

**Comment by BaY1251** [comment]
@akoeplinger I test 'GetPortNames','Open','Write','Read','DiscardInBuffer','DiscardOutBuffer' .  It Works! 
The third-party library can finally be laid off

**Comment by akoeplinger** [comment]
Awesome, thanks for the confirmation!
