### ISSUE TITLE
Unable to break on callback from unmanaged thread

### ISSUE THREAD

**Issue by mayuki** [dotnet/runtime#89292]
### Description

If a managed callback function is called from an unmanaged thread, the debugger cannot break at the beginning of the callback.

The behavior is unstable, as it can break after the second line, or it may break after many calls. In complex scenarios, stepping through the debugger using mixed mode may cause AccessViolationException or ExecutionEngineException to be thrown.

This problem only occurs when using the traditional Delegate (GetFunctionPointerForDelegate) method and not when using the function pointer (`delegate*`).

### Managed
```csharp
NativeMethods.mylib_callback(Callback);

static void Callback()
{
    Console.WriteLine("Callback"); // <-- Set a breakpoint on this line.
}

unsafe static class NativeMethods
{
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void mylib_callback_callback();

    [DllImport("Dll1", EntryPoint = "mylib_callback", CallingConvention = CallingConvention.Cdecl)]
    public static extern void mylib_callback(mylib_callback_callback callback);
}
```

### Native
```cpp
typedef void (cdecl* MYLIB_CALLBACK)();
extern "C" __declspec(dllexport) cdecl void mylib_callback(MYLIB_CALLBACK callback);

DWORD WINAPI MyLibCallbackThread(LPVOID lpParameter)
{
	((MYLIB_CALLBACK)lpParameter)();
	return 0;
}

void mylib_callback(MYLIB_CALLBACK callback) {
	DWORD threadId;
	HANDLE hThread = CreateThread(nullptr, NULL, &MyLibCallbackThread, (LPVOID)callback, NULL, &threadId);
	WaitForSingleObject(hThread, INFINITE);
}
```

### Expected behavior

The debugger breaks at the breakpoint

### Actual behavior

The debugger passes breakpoint

### Regression?

If the codes are running on .NET Framework 4.x, the debugger breaks as expected.

### Configuration

- Build configuration: Debug
- .NET 7.0.306 (x64)
- Microsoft Visual Studio 2022 Version 17.6.5
- Microsoft Windows 10 Pro 22H2

**Comment by tommcdon** [comment]
@hoyosjs @AaronRobinsonMSFT I placed this in .NET 9 milestone though feel free to pull back to .NET 8 if we have time to fix

**Comment by hoyosjs** [comment]
I am unable to repro this - on debug setting a break in Callback on win-x64 both on .NET 8 and 7 I get regular break behavior regardless of JMC state.

**Comment by mayuki** [comment]
I have tried to reproduce the problem in several environments, but the problem seems to occur when "Enable native code debugging" is enabled. Platform, OS, and JMC settings do not seem to affect this.

**Comment by AaronRobinsonMSFT** [comment]
> I have tried to reproduce the problem in several environments, but the problem seems to occur when "Enable native code debugging" is enabled. OS and JMC settings do not seem to affect this.

Ah. There was a recent fix for mixed mode debugging - https://github.com/dotnet/runtime/pull/88683. Perhaps this has been fixed.

**Comment by f2bo** [comment]
I've experienced similar problems when placing a breakpoint in a method invoked via an unmanaged function pointer, though I'm not sure whether it is exactly the same problem as reported by @mayuki.

For example, here's an example with two identical methods, the first one is invoked with a delegate and the other one with an unmanaged function pointer. If you place a breakpoint on the closing brace of each method, only the breakpoint on the method invoked via the delegate is triggered. The breakpoint is hit in the `[UnmanagedCallersOnly]` case when placed on the previous line, but single-stepping after that returns to the caller, which makes it very inconvenient if you need to examine state before exiting the method.

```C#
static int value;

static void UpdateManaged()
{
    value = Random.Shared.Next(1, 10); // <== placing a breakpoint here and single-stepping advances to closing brace
}  // <=== breakpoint here IS triggered

[UnmanagedCallersOnly]
static void UpdateUnmanaged()
{
    value = Random.Shared.Next(1, 10); // <== placing a breakpoint here and single-stepping exits the method
    //return;                           // <== add a return statement for expected behavior
}  // <=== breakpoint here IS NOT triggered

static unsafe void Main()
{
    Action managedCall = UpdateManaged;
    managedCall();

    delegate* unmanaged<void> unmanagedCall = &UpdateUnmanaged;
    unmanagedCall();
}
```

**Comment by AaronRobinsonMSFT** [comment]
@hoyosjs There is some corruption here. I can reproduce this with mixed mode debugging on HEAD.

```
Assert failure(PID 14560 [0x000038e0], Thread: 14204 [0x377c]): HasReturnFrame(true)

CORECLR! DebuggerStepper::TriggerSingleStep + 0x2AB (0x00007ffe`c5965bbb)
CORECLR! DebuggerController::ScanForTriggers + 0x11A6 (0x00007ffe`c595c7c6)
CORECLR! DebuggerController::DispatchPatchOrSingleStep + 0xD6F (0x00007ffe`c5954e3f)
CORECLR! DebuggerController::DispatchNativeException + 0x9EF (0x00007ffe`c5953eef)
CORECLR! Debugger::FirstChanceNativeException + 0x586 (0x00007ffe`c59743b6)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x15C (0x00007ffe`c527724c)
CORECLR! CLRVectoredExceptionHandler + 0xD0F (0x00007ffe`c52770af)
CORECLR! CLRVectoredExceptionHandlerShim + 0x1B5 (0x00007ffe`c5277b25)
NTDLL! RtlGetLengthWithoutLastFullDosOrNtPathElement + 0x3DA (0x00007fff`90687a9a)
NTDLL! RtlFindCharInUnicodeString + 0x872 (0x00007fff`9062e232)
    File: ...\runtime\src\coreclr\debug\ee\controller.cpp Line: 341
    Image: ...\runtime\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\corerun.exe
```

**Comment by mikelle-rogers** [comment]
I was unable to reproduce the issue with mixed mode debugging in Visual studio using .NET8 version 8.0.0-rc.2.23479.6. @f2bo will you please try to repro with version 8.0.0-rc.2.23479.6 and let us know?

**Comment by f2bo** [comment]
Hi @mikelle-rogers,

Yes. I still see the same behavior when tested with Visual Studio 17.8.0 Preview 4.0 and .NET 8.0.0-rc.2.23479.6. Note that I'm not the author of this thread. I mention this in case you meant to tag @mayuki since my issue seems related but I'm not sure whether it's exactly the same. Perhaps his issue no longer repros.

I created a new console app targetting .NET 8 with the code I included [above](https://github.com/dotnet/runtime/issues/89292#issuecomment-1648321799). I placed breakpoints on the lines tagged with `// <===  breakpoint here ...` (i.e. **on** the closing brace).  Only the breakpoint in the `UpdateManaged` method is hit. This happens with or without mixed-mode debugging.

Please let me know if there's any other information that you need.
